### ISSUE TITLE
Add combined Wilderness layer to SGID from BLM and USFS

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#100]
New combined BLM/USFS wilderness BOUNDARIES.UtahWildernessAreas to replace outdated BOUNDARIES.USFSWilderness

# Summary

- **Proposed Dataset Name**: UtahWildernessAreas
- **Proposed ArcGIS Online Name**: Utah Wilderness Areas
- **Proposed ISO Category**: BOUNDARIES
- **Data Description**: Combined BLM/USFS wilderness areas
- **Source Agency/Entity**: BLM and USFS
- **Contact**: Zach Beck (for now)
- **Update Frequency**: As needed

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# We are introducing data

The data was or will be added on `2020/12/10` to the following areas

- [x] Internal SGID
- [x] ArcGIS Online

# The data is high quality

- [x] Sweeper checks have run and passed
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] ArcGIS Online
- [x] Internal SGID (assigned to @ZachBeck)
- [x] Open SGID
- [x] Open Data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)
- [x] `SGID.META.AGOLItems`
- [ ] `AGOLItems_shelved` [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) (AGOL version of the metatable for any `static` or `shelved` items)

# We have verified the data is live

- [x] ArcGIS Online (@ZachBeck on `12/21/2020`)
- [x] Internal SGID (@ZachBeck on `12/10/2020`)
- [x] Open SGID (@ZachBeck on `12/22/2020`)
- [x] [Open data](https://opendata.gis.utah.gov) (@ZachBeck on `12/21/2020`)
- [x] gis.utah.gov data pages (@ZachBeck on `12/21/2020`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@ZachBeck on `12/21/2020`)
- [x] `SGID.META.AGOLItems` (@ZachBeck on `12/21/2020`)
- [x] `SGID.META.ChangeDetection` (@steveoh  on `01/06/2021`)
- [x] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on `01/07/2021`)

# Notification

- [ ] Blog post (@assigned)
- [x] Twitter (@steveoh)

**Comment by ZachBeck** [comment]
Entries in META.AGOLItems and sgid-index were started, waiting for AGOL_ID

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 100

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| steveoh has completed **3** out of **3** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| ZachBeck has completed **8** out of **8** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for BOUNDARIES.UtahWildernessAreas

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |

**Comment by ZachBeck** [comment]
Endpoint has been updated

**Comment by steveoh** [comment]
Nice! Are we done or waiting on the last @jacobdadams checkbox? The scheduled run should have happened this morning. Did that work properly?

**Comment by jacobdadams** [comment]
It completed but threw an error during clean up (working on that now). 

Looking at the log, all the checks for this item were good, though.
