### ISSUE TITLE
Remove Geolocators from mapserv

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#102]
# Summary

http://mapserv.utah.gov/arcgis/rest/services/Geolocators

Mapserv has long hosted our geocoders in this folder. I wonder if they were originally used to back the web API geocoder? Now-a-days, the web API has it's own, dedicated ArcGIS Server instance and does not hit mapserv. No one has been updating these locators so they are likely years out-of-date. I propose that we deprecate them in favor of the web API or the [downloadable locators on our website](https://gis.utah.gov/data/address-geocoders-locators/#RoadsAddressLocatorPackage) that Greg keeps up-to-date.

There is likely a bit of research that needs to be done to see what, if anything, is using these.

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

~- [ ] Internal SGID (assigned to)~
~- [ ] SGID10 (assigned to)~
- [x] Mapserv (@stdavis on 12/23/2022)

# Update information in the following areas

- [x] gis.utah.gov data pages (search for links on our website) (@gregbunce merged on 12/23/2022)
- [x] Stewardship doc and sgid-index (@gregbunce on 12/12/2022)

# Is there a map service?

- [x] Stop (@stdavis on 12/09/2022)
- [x] Delete (@stdavis on 12/22/2022)

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh)

# Notification

- [x] Intent Twitter (@steveoh)

**Comment by steveoh** [comment]
My only concern is arcgis only clients that cannot access the web api

**Comment by stdavis** [comment]
Great point. I forgot to mention that we may want to wait until [masquerade](https://github.com/agrc/masquerade) is ready for prime time.

**Comment by steveoh** [comment]
Let's block this until masquerade is available.

In the mean time should we start to maintain that locator?

**Comment by steveoh** [comment]
These are actually being maintained by forklift. Should we continue to provide them?

**Comment by stdavis** [comment]
I feel like that masquerade will give much better results overall once it's up-to-snuff so we should deprecate these at that point.

**Comment by stdavis** [comment]
The next step for this might be to check the (perhaps unreliable?) ArcGIS Server usage stats for these services.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 102

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **3** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 102

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **3** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 102

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **3** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |

**Comment by stdavis** [comment]
What is the appropriate messaging for this deprecation? Tweet + email? Here is some possible verbiage:

>Heads up! We are deprecating our geolocator services "AddressPoints_AddressSystem" and "Roads_AddressSystem_STREET" on mapserv.utah.gov in favor of Masquerade (https://github.com/agrc/masquerade#readme) on Monday, December 5th. Please upgrade any of your projects before then.

@steveoh Can you help with getting this info out there? Does 4 weeks seem like a reasonable timeframe?

**Comment by steveoh** [comment]
What email addresses would you use? 

I'm fine to proceed without notification but a tweet seems normal and your message is good.

@brigsz, when is the next newsletter?

**Comment by brigsz** [comment]
I don't think it is until January, around the week of the 17th is what I have on the calendar

**Comment by stdavis** [comment]
I'm good with just a tweet. I'm not sure that the usage is enough to justify a separate spam to our newsletter email list.

**Comment by steveoh** [comment]
/remind someone to remove the locators on december 5th

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 102

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **3** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |

**Comment by stdavis** [comment]
I stopped the locators on both machines today.

/remind me to delete the locators in two weeks

**Comment by steveoh** [comment]
I only saw a handful of failed requests in the logs. Hopefully everyone has migrated.

**Comment by gregbunce** [comment]
i'm reading that i can remove the reference to desktop locators on our website now.  is that correct?  sounds like we've made the appropriate notices and announcements.  just want to confirm before i do so.

**Comment by gregbunce** [comment]
verified that there were no references to the arcgis 10x locators/geocoders in the stewardship sheet and/or sgid index

**Comment by gregbunce** [comment]
[PR 2174](https://github.com/agrc/gis.utah.gov/pull/2174) removes references to the arcgis 10x locators from gis.utah.gov

**Comment by steveoh** [comment]
@stdavis will you merge the above pr when you remove the locators on the 23rd? I won't be working then.

**Comment by stdavis** [comment]
Locators have been removed from mapserv and the associated gis.utah.gov PR has been merged.

**Comment by gregbunce** [comment]
thanks for checking the box for me, @stdavis.  you beat me to it. 
`gis.utah.gov data pages (search for links on our website)`
