### ISSUE TITLE
Add UDOT ALRS from UDOT hosted feature service

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#103]
# Summary

This [new hosted feature layer](https://opendata.gis.utah.gov/datasets/uplan::udot-routes-alrs) will replace the existing SGID.Transportation.UDOTRoutes_LRS layer, as described in porter [issue 104](https://github.com/agrc/porter/issues/104). This new layer represents UDOT's new Advanced LRS system. UDOT will maintain the feature service and AGRC will point SGID Open Data users to their service. Additionally, AGRC will host this layer in Internal and Open SGID.
Note: This is one of three existing SGID layers that we will be replacing using this method (LRS, mile point measures, freeway exit locations). 

- **Proposed Dataset Name**: UDOT ALRS Routes
- **UDOT's ArcGIS Online Name**: [UDOT Routes (ALRS)](https://opendata.gis.utah.gov/datasets/uplan::udot-routes-alrs)
- **Proposed ISO Category**: Transportation
- **Data Description**: Primary Routes from UDOT Roads and Highways
- **Source Agency/Entity**: UDOT
- **Contact**: Kelli Bacon at UDOT
- **Update Frequency**: as needed

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage (@rkelson)~

# We are introducing data

The data should be added at our earliest convince (after @gregbunce runs sweeper) to the following areas

- [x] Internal SGID (wait until sweeper checks pass)
~- [ ] Load data into SGID ()~
~- [ ] SGID10~
~- [ ] ArcGIS Online~

# The data is high quality

- [x] Sweeper checks have run and passed (@gregbunce)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] ArcGIS Online (@gregbunce)
- [x] Internal SGID (@stdavis)
- [x] Open SGID (@steveoh)
- [x] Open Data (@gregbunce)
- [x] `SGID.META.ChangeDetection` (@steveoh)

# References to the data need to be manually added to

- [x] gis.utah.gov data pages (@gregbunce)
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) (@gregbunce)
- [x] `SGID.META.AGOLItems` (@stdavis)
~- [ ] `AGOLItems_shelved` [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) (AGOL version of the metatable for any `static` or `shelved` items)~

# We have verified the data is live

- [x] ArcGIS Online (@gregbunce on `01/05/2021`)
- [x] Internal SGID (@gregbunce on '01/19/2021')
- [x] Open SGID (@gregbunce  on '01/28/2021' )
- [x] [Open data](https://opendata.gis.utah.gov) (@gregbunce on `01/05/2021`)
- [x] gis.utah.gov data pages (@gregbunce on ``)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@gregbunce on `01/05/2021`)
~- [ ] `SGID.META.AGOLItems` (``)~
- [ ] `SGID.META.ChangeDetection` (@steveoh on ``)
~- [ ] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on )~

# Notification

- [x] Twitter (@steveoh)

**Comment by gregbunce** [comment]
@stdavis this data passed the sweeper checks and is ready to be brought into Internal (forklift pallet).  let me know if you have any questions.

**Comment by steveoh** [comment]
If the schema is the same or a superset of what we are serving we do not need to deal with porter. 

rule 1. no one cares

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 103

| check | status |
| - | :-: |
| @gregbunce has completed **7** out of **12** tasks | :no_entry: |
| @steveoh has completed **3** out of **6** tasks | :no_entry: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesALRS

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship | :no_entry: Did not find Transportation.UDOTRoutesALRS in the worksheet |

**Comment by stdavis** [comment]
> @stdavis this data passed the sweeper checks and is ready to be brought into Internal (forklift pallet). let me know if you have any questions.

Forklift doesn't create datasets in SGID. It only updates existing ones. @ZachBeck would need to load it first. I'll add a task to the issues description for it.

**Comment by steveoh** [comment]
> This checked box "- [x] Internal SGID (wait until sweeper checks pass)" made me think that you had already added it to internal SGID.

The verification heading is where you should look to know what has been added where.

**Comment by ZachBeck** [comment]
This has been loaded into internal-sgid but the permissions have not been shared out to the internal user. The source UDOT data had a stale `OBJECTID` field that I deleted and a field named `SUB_ROUTE_` that I renamed to `SUB_ROUTE`. I don't know if that will foul things up on the forklift side of things. There was no metadata that came with the shapefile download either.

**Comment by steveoh** [comment]
While I agree that the dangling underscore should go and is probably not necessary, unless it's a reserved sql term, it might cause more issue with the import than it is worth to remove it.

**Comment by ZachBeck** [comment]
Too late, I put the underscore back

**Comment by stdavis** [comment]
This PR will complete the wiring up of forklift for this pallet: https://github.com/agrc/warehouse/pull/125

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 103

| check | status |
| - | :-: |
| @gregbunce has completed **7** out of **12** tasks | :no_entry: |
| @steveoh has completed **3** out of **6** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesALRS

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship | :no_entry: Did not find Transportation.UDOTRoutesALRS in the worksheet |

**Comment by steveoh** [comment]
blocked by SGID sharing.

**Comment by gregbunce** [comment]
this dataset now as the appropriate sgid sharing permissions.  it should be ready for the open sgid db.

**Comment by steveoh** [comment]
Has your triage finished @gregbunce?

**Comment by gregbunce** [comment]
yup, i'm just working on getting udot to add a little more metadata and also i need to update our data page (tomorrow).  but, that should be everything on my end.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 103

| check | status |
| - | :-: |
| @gregbunce has completed **10** out of **12** tasks | :no_entry: |
| @steveoh has completed **4** out of **6** tasks | :no_entry: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesALRS

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by steveoh** [comment]
> this dataset now as the appropriate sgid sharing permissions.  it should be ready for the open sgid db.

We're missing all the meta table information. Will you add that so the other automation will run.

**Comment by gregbunce** [comment]
the metatable has been updated.  i'm not sure if i added the correct agol name - i removed the [parenthesis](https://opendata.gis.utah.gov/datasets/uplan::udot-routes-alrs) b/c that's what i had to do to get [data page to work ](https://github.com/agrc/gis.utah.gov/pull/1634/files).  if that doesn't work, I'll include the parens.

**Comment by steveoh** [comment]
You could try to quote the string containing the parens to get them in the website? But the open data url does not contain the parens so I think you used the correct text for the meta table. Did you also set the geometry type?

**Comment by stdavis** [comment]
Hey @gregbunce. Next time put something like `hosted by UDOT` in the `AGOL_ITEM_ID` field. If there's a valid guid in that field, then forklift attempts to update it. It threw an error in this case because the item is owned by UDOT. I've updated the table to look like this:
![image](https://user-images.githubusercontent.com/1326248/106015227-7ed40480-607b-11eb-9ef5-b9b5fdcdd8cf.png)
Yes, @steveoh the geometry type is in there.

**Comment by gregbunce** [comment]
thanks, @stdavis.   and yup, @steveoh i did set the geom type.

**Comment by steveoh** [comment]
> [🚜] threw an error in this case because the item is owned by UDOT.

Does this need a manual push or will 🚜 pick it up tomorrow?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 103

| check | status |
| - | :-: |
| @gregbunce has completed **11** out of **13** tasks | :no_entry: |
| @steveoh has completed **4** out of **5** tasks | :no_entry: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesALRS

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by gregbunce** [comment]
kelli bacon and i are meeting this week to iron out the final details for the wording of the metadata and the agrc transportation page's lrs section

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 103

| check | status |
| - | :-: |
| @gregbunce has completed **11** out of **13** tasks | :no_entry: |
| @steveoh has completed **4** out of **5** tasks | :no_entry: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesALRS

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :no_entry: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |
