### ISSUE TITLE
Deprecate UDOT LRS Routes from SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#104]
# Summary

[This SGID LRS layer](https://github.com/agrc/porter/issues/104#issue-779277783) was replaced by UDOT's newer [Advanced LRS (ALRS) hosted feature service](https://opendata.gis.utah.gov/datasets/uplan::udot-routes-alrs) described in porter [issue 103](https://github.com/agrc/porter/issues/103). Please migrate all existing maps and app at your earliest convenience.  A notification of this change was also sent via [Twitter](https://twitter.com/MapUtah/status/1358847265826238464)

AGRC will perform a brownout on this layer on **March 5th, 2021** with a complete deprecation on **March 8th, 2021**.

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage (@rkelson)~

# Remove data from the following areas

- [x] ArcGIS Online (@gregbunce on '03/08/2021'- and backed up the layer in AGRC google drive [deprecated data directory](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).)
- [x] Internal SGID (@gregbunce on '03/10/2021' - and backed up the layer in AGRC google drive [deprecated data directory](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).)
- [x] Open SGID (@gregbunce confirmed it has been removed '03/17/2021' )
- [x] Open data (brownout on @gregbunce on '03/05/2021')

# Update information in the following areas

- [x] gis.utah.gov data pages (@gregbunce on '02/04/2021')
- [x] Stewardship doc and sgid-index (@gregbunce on '03/08/2021')
- [x] `SGID.META.AGOLItems` (@gregbunce on '03/08/2021' )
- [x] `SGID.META.ChangeDetection` (assigned to @steveoh )

# Notification

- [x] Intent Twitter (@steveoh)

**Comment by steveoh** [comment]
blocked by #103

**Comment by steveoh** [comment]
If the schema is the same or a superset of what we are serving we do not need to deprecate or brownout. We can wire up forklift and be on our way.

**Comment by steveoh** [comment]
meeting update

- generate 30-day notice 
- choose brownout date
- choose deprecation date

still blocked by #103

**Comment by gregbunce** [comment]
@steveoh can we get a tweet out (or maybe we did already) saying we're deprecating this LRS layer in 30 days on March 5th?

we're deprecating this LRS layer:
https://opendata.gis.utah.gov/datasets/utah-udot-routes-lrs

it's been replaced by this ALRS (Advanced) layer:
https://opendata.gis.utah.gov/datasets/uplan::udot-routes-alrs

More info on the newest layer can be found here:
https://gis.utah.gov/data/transportation/roads-system/#HighwayLinearReferencingSystemRoutes

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 104

| check | status |
| - | :-: |
| @gregbunce has completed **2** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| stdavis has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UDOTRoutesLRS

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find Transportation.UDOTRoutesLRS in the worksheet |

**Comment by gregbunce** [comment]
a brownout on this layer is now in effect.  if all goes as expected, this layer will be removed from the sgid Monday, March 8, 2021.

**Comment by gregbunce** [comment]
this layer has been removed from AGOL and has been backed up in the AGRC google drive in the [deprecated directory](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).

**Comment by gregbunce** [comment]
i just realized that i did a brownout only on the AGOL item, but forgot to brownout the Internal SGID layer. I just removed the "Internal" privileges from this layer now.  I'll let that sit for a day and then delete it from the db tomorrow if there were no internal dependencies.

**Comment by gregbunce** [comment]
@steveoh am i safe to delete the AGOLItems record for this layer?  
![image](https://user-images.githubusercontent.com/16906316/110390311-091c6a80-8023-11eb-8131-1cc5cc68ec3f.png)

**Comment by gregbunce** [comment]
right, i see what you're saying.  good point.  

also, i just notice the agol items table was assigned to @stdavis.  Scott, let me know if you want me to stand back, but, i'm also happy to take this task.  i already have my hands dirty.  either way, just let me know.

**Comment by jacobdadams** [comment]
For the record, Auditor will run it's fixes on any row in the metatable with a valid AGOL_ITEM_ID value (it tries parsing the GUID, and if it can't it ignores the row). If you want Auditor to ignore a row, replace the id with text (like `Removed from AGOL` or something like that). 

Also, Auditor will share any item it finds a proper group for (which currently comes from the category portion of `SGID.GROUPNAME.TableName`) to both the group and everyone else. So, if you unshare something that is being picked up by Auditor, Auditor will reshare it.

**Comment by gregbunce** [comment]
@steveoh looks like we can close this out once the SGID.META.ChangeDetection process/table is satisfied.

**Comment by steveoh** [comment]
well i think i deleted the advanced change detection row as well but that will resolve itself.
