### ISSUE TITLE
Deprecate SOCIETY.Libraries in favor of new layer

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#105]
# Summary

Deprecate SOCIETY.Libraries and replace with #106

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- ~[ ] Cadastre Team Triage (@rkelson)~

# Remove data from the following areas

- [x] ArcGIS Online (@ZachBeck)
- [x] Internal SGID (@ZachBeck)
- ~[ ] SGID10 (assigned to)~
- [x] Open SGID (@steveoh)
- [x] Google Drive (@ZachBeck)
- [x] Open data (@ZachBeck)
- ~[ ] Mapserv (assigned to)~
- ~[ ] Retire application-specific prod and test SQL Databases (assigned to)~
- ~[ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (assigned to)~

# Shelve/Static

- ~[ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
      or
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (@ZachBeck)
      or
- ~[ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- [x] gis.utah.gov data pages (@ZachBeck)
- [x] Stewardship doc and sgid-index (@ZachBeck)
- [x] `SGID.META.AGOLItems` (@ZachBeck)
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (@ZachBeck)
- [x] `SGID.META.ChangeDetection` (@stdavis on `2021/02/15`)
- [x] [Backseat Driver](https://github.com/agrc/backseat-driver) (@stdavis on `2021/02/15`)

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
      or
- ~[ ] Replace app with a static page with information (assigned to)~
      or
- ~[ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~

# Is there a forklift pallet? (@stdavis couldn't find any)

- ~[ ] Remove repo (assigned to @stdavis @steveoh )~
- ~[ ] Remove stale data from forklift hashing and receiving (assigned to @stdavis @steveoh )~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (assigned to @stdavis @steveoh )~

# Are there service dependencies?

- ~[ ] Validate that the web api does not query it (assigned to)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

- ~[ ] Intent Twitter (@steveoh)~

**Comment by steveoh** [comment]
Since we are deprecating and introducing the same table, I propose we chose a unique table name which might be difficult but does anyone have ideas or opinions?

**Comment by gregbunce** [comment]
Public Libraries?

**Comment by steveoh** [comment]
I vote that we block this issue and do the PublicLibraries data introduction first. Any objections?

**Comment by jacobdadams** [comment]
Just FYI, Auditor added the shelved note and tag on the AGOL item this morning. It would have done the thumbnail, too, but I misnamed the thumbnail image. It should get a thumbnail image tomorrow morning.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 105

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| ZachBeck has completed **9** out of **9** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Libraries

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 105

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| ZachBeck has completed **9** out of **9** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Libraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 105

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| ZachBeck has completed **9** out of **9** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Libraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 105

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **7** tasks | :no_entry: |
| ZachBeck has completed **9** out of **9** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Libraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |
