### ISSUE TITLE
Add SOCIETY.PublicLibraries from Utah State Libraries Division

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#106]
PublicLibraries was geocoded from locations provided by the Utah State Libraries Division. This will replace the exiting version of SOCIETY.Libraries since it has a new schema.

- **Proposed Dataset Name**: PublicLibraries
- **Proposed ArcGIS Online Name**: Utah Public Libraries
- **Proposed ISO Category**: SOCIETY
- **Data Description**: Utah public library and bookmobile locations.
- **Source Agency/Entity**: Utah State Libraries Division
- **Contact**: Bar Baz
- **Update Frequency**: As needed

# Triage

- [ ] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- ~[ ] Cadastre Team Triage (@rkelson)~

# We are introducing data

The data was or will be added on `2021/01/06` to the following areas

- [x] Internal SGID
- [x] ArcGIS Online

# The data is high quality

- [x] Sweeper checks have run and passed
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] ArcGIS Online
- [x] Internal SGID (@ZachBeck)
- [x] Open SGID
- [x] Open Data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)
- [x] `SGID.META.AGOLItems`
- ~[ ] `AGOLItems_shelved` [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) (AGOL version of the metatable for any `static` or `shelved` items)~

# We have verified the data is live

- [x] ArcGIS Online (@ZachBeck  on `01/12/2021`)
- [x] Internal SGID (@ZachBeck on `01/06/2021`)
- [x] Open SGID (@steveoh on `2021/01/07`)
- [x] [Open data](https://opendata.gis.utah.gov) (@ZachBeck on `01/12/2021`)
- [x] gis.utah.gov data pages (@ZachBeck on `01/12/2021`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@ZachBeck on `01/06/2021`)
- [x] `SGID.META.AGOLItems` (@ZachBeck on `01/06/2021`)
- [x] `SGID.META.ChangeDetection` (@steveoh  on `2021/01/07`)
- [x] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams  on `01/13/2021`)

# Notification

- [x] Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 106

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| @ZachBeck has completed **4** out of **8** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.PublicLibraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
meeting update

- need item name in agol table
- unblock cloudb and forklift

**Comment by stdavis** [comment]
I couldn't find an existing row for this dataset in AGOLItems so I added a new row with the table name and the public name.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 106

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **4** out of **7** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.PublicLibraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
I updated the stewardship doc to have a website and endpoint 👍🏼

**Comment by steveoh** [comment]
@ZachBeck you completed the sgid index on 01/06/2021, but it was incomplete. Next time please don't mark it as done until all the parts are complete. 🎯

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 106

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| ZachBeck has completed **7** out of **7** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.PublicLibraries

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |
