### ISSUE TITLE
Add Tax Entities 2020 from Utah State Tax Commission 

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#110]
# Summary

- **Proposed Readable Name**: Utah Tax Entities 2020 
- **Proposed Internal Dataset Name**: TaxEntities2020
- **Proposed External Dataset Name**: Tax_Entities_2020 
- **Proposed Data Category**: Economy
- **Data Description**: Incorporated bodies that have the power to levy a local property tax such as school districts, counties, cities, special service districts, redevelopment districts, etc.
- **Source Agency/Entity**: Utah State Tax Commission
- **Contact**: Terri Chidester
- **Update Frequency**: Yearly

_Introduce your data, where it comes from, why it is being added etc._

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@ZachBeck on `2021/01/21`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@ZachBeck on `2021/01/21`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@ZachBeck on `2021/01/21`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@ZachBeck, completed: `2021/01/21`)
- ~[ ] Configure forklift for Farm from AGOL (name, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck, completed: `2021/01/26`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2021/01/26`)
- [x] Complete a `SGID.META.AGOLItems` record (@ZachBeck, completed: `2021/01/26`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2021/02/08`)
- [x] ArcGIS Online via forklift (@ZachBeck on `2021/01/26`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/01/23`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@ZachBeck on `2021/01/26`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck on `2021/01/26`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/01/26`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 110

| check | status |
| - | :-: |
| @ZachBeck has completed **4** out of **9** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Economy.TaxEntities2020

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :no_entry: |
| open data | :+1: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 110

| check | status |
| - | :-: |
| ZachBeck has completed **10** out of **10** tasks | :+1: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Economy.TaxEntities2020

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 110

| check | status |
| - | :-: |
| ZachBeck has completed **10** out of **10** tasks | :+1: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Economy.TaxEntities2020

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :no_entry: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 110

| check | status |
| - | :-: |
| ZachBeck has completed **10** out of **10** tasks | :+1: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Economy.TaxEntities2020

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :no_entry: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by steveoh** [comment]
@ZachBeck open sgid is failing because the meta table geometry type is incorrect
