### ISSUE TITLE
Add UTA Routes & Most Recent Ridership from UTA 

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#113]
# Summary

- **Proposed Readable Name**: UTA Routes & Most Recent Ridership 
- **Proposed Internal Dataset Name**: UTA_RoutesAndRidership
- **Proposed External Dataset Name**: uta_routes_and_ridership 
- **Proposed Data Category**: TRANSPORTATION
- **Data Description**: UTA bus, trax, and commuter rail routes and ridership
- **Source Agency/Entity**: UTA
- **Contact**: Sumerset Ellis
- **Update Frequency**: Biannual

This is UTA data that has been shared with the Transportation group in agol. This data will replace the existing TRANSPORTATION.BusRoutes_UTA in internal-sgid.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [ ] ArcGIS Online
- [ ] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (name on `2021/01/28`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (name on `2021/01/28`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (name on `2021/01/28`)

## Where is the data source

_Choose one._

- [ ] Internal SGID
- [x] Farm from AGOL (https://utah.maps.arcgis.com/home/item.html?id=4347f3565fbe4d5dbb97b016768b8907)

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@ZachBeck, completed: `2021/02/10`)
- [x] Configure forklift for Farm from AGOL (@stdavis, completed: `2021/02/16`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck, completed: `2021/02/22`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2021/02/22`)
- [x] Complete a `SGID.META.AGOLItems` record (@ZachBeck, completed: `2021/02/02`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2021/02/22`)
- ~[ ] ArcGIS Online via forklift (@stdavis on `2021/00/00`)~
- ~[ ] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/00/00`)~
- ~[ ] [Open Data](https://opendata.gis.utah.gov) (name on `2021/00/00`)~
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck on `2021/02/22`)
- [ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
> This data will replace the existing TRANSPORTATION.BusRoutes_UTA in internal-sgid.

the data is exactly the same?

**Comment by ZachBeck** [comment]
The schema is a little different. The main difference is this data has the routes for buses, trax, and front runner, otherwise I'd modify the schema in sde for the BusRoutes_UTA and use the existing FC.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 113

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 113

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @ZachBeck has completed **1** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UTA_RoutesAndRidership

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :no_entry: |
| open data | :+1: |
| arcgis online | :no_entry: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 113

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @ZachBeck has completed **1** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UTA_RoutesAndRidership

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :no_entry: |
| open data | :+1: |
| arcgis online | :no_entry: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 113

| check | status |
| - | :-: |
| @ZachBeck has completed **2** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UTA_RoutesAndRidership

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :no_entry: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 113

| check | status |
| - | :-: |
| @ZachBeck has completed **2** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.UTA_RoutesAndRidership

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :no_entry: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |
| - Endpoint | :+1: |

**Comment by ZachBeck** [comment]
done
