### ISSUE TITLE
Remove TaxAreas2019 from SGID

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#115]
# Summary

- SGID.ECONOMY.TaxAreas2019:
- opensgid.economy.tax_areas_2019:
- https://utah.maps.arcgis.com/home/item.html?id=7232bbbfdb8a485b972f0b89d264716c:

Deprecate and shelve TaxAreas2019, it has been replaced by TaxAreas2020

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from the Internal SGID (@ZachBeck, completed: `2021/02/03`)
- [x] Delete ArcGIS Online item (@ZachBeck, completed: `2021/02/03`)
  - [x] Add `deprecated` tag to ArcGIS Online item (@ZachBeck, completed: `2021/02/03`)
  - [x] Add `Deprecated` to ArcGIS Online item title(@ZachBeck, completed: `2021/02/03`)
- [x] Unshare item from Open Data (@ZachBeck, completed: `2021/00/00`)
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)~
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2021/02/03`)
- [x] Update `SGID.META.AGOLItems` table (@ZachBeck, completed: `2021/02/03`)
  - delete row if removing from both
  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
- ~[ ] Delete Google Drive data (name, completed: `2021/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2021/02/08`)
- [x] Remove json file from [Backseat Driver](https://github.com/agrc/backseat-driver) (@stdavis, completed `2021/02/15`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2021/02/04`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2021/02/04`)

### Shelve/Static

_Choose one._

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (name, completed: `2021/00/00`)~
- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (@ZachBeck, completed: `2021/02/03`)
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2021/02/08`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/02/08`)

## Are there service dependencies

- Does an application depend on this data?
  - not that i can think of - steve

- Are clients querying this data with the WebAPI?
  - they could be but stats do not show any usage - steve

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 115

| check | status |
| - | :-: |
| ZachBeck has completed **7** out of **7** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxAreas2019

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by jacobdadams** [comment]
FYI, auditor is wired to remove the deprecated tag from shelved items. I'm thinking that deprecated means "Don't use this, it's no longer valid/authoritative" while shelved means "this is old but might still be useful.

**Comment by steveoh** [comment]
We should have coordinated this removal a little better. There are dependencies and broken services now because of the speed of the removal. 

Should we not make any updates until everyone has triaged the issue?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 115

| check | status |
| - | :-: |
| ZachBeck has completed **7** out of **7** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxAreas2019

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
> If the layer is being shelved, an entry needs to be added to the `AGOLItems_shelved` table in AGOL so that auditor knows it should be shelved.

This layer should be shelved. Please make sure this happens. Do we need to update the template for this?

**Comment by ZachBeck** [comment]
The shelved table was updated on 2/3

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 115

| check | status |
| - | :-: |
| ZachBeck has completed **7** out of **7** tasks | :+1: |
| @steveoh has completed **4** out of **5** tasks | :no_entry: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxAreas2019

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
this shelved data needs to be discoverable somewhere.
