### ISSUE TITLE
Deprecate PLPCO Roads Viewer application

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#118]
# Summary

- **Application Name**: PLPCO Roads Viewer
- **Application Url**: roads.utah.gov

PLPCO has implemented Esri Enterprise Portal, and Scott has built some custom applications for them to host on their own infrastructure, and to replace this app. The DNS will be maintained, and already redirects to their [new application](https://publiclands.utah.gov/accessmap360/).

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- ~Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)~
- ~[ ] Remove forklift pallet (@stdavis, completed: `2021/00/00`)~ (this will go away with the machine)
- ~[ ] Remove application-specific Databases @stdavis, completed: `2021/00/00`)~ (this is a Jason thing and was likely done when they did their enterprise deployment)
- ~AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)~ (no specific drive folder found for this project -NK)

### Is there a website?

-  ~Remove DNS entry (name, completed: `2021/00/00`)~
- [x] Archive [source code repository](https://github.com/agrc/roads.utah.gov) (@stdavis, completed: `2021/02/18`)

_Choose one._

- ~[ ] Remove from the web server (@stdavis, completed: `2021/00/00`)~ (this will go away with the machine)
- ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [x] Redirect somewhere else (@nathankota, complete)

### Is there a map service?

- ~[ ] Stop (@stdavis, completed: `2021/00/00`)~
- ~[ ] Delete (@stdavis, completed: `2021/00/00`)~

### Is there a forklift pallet?

- ~[ ] Remove repo (@stdavis, completed: `2021/00/00`)~
- ~[ ] Remove stale data from forklift hashing and receiving (@stdavis, completed: `2021/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2021/00/00`)~

### Are there service dependencies?

- ~[ ] Validate that the web api does not query it (@stdavis, completed: `2021/00/00`)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (@stdavis, completed: `2021/00/00`)~

### Retire server

- [x] Copy image server data to their new machine (@stdavis, completed: `2021/02/22`)
- [x] Ask for a backup of the machine for Jason to stick somewhere (Jason submitted clone request INC1436818)
- [x] Submit a request to decommission the machine (Jason will do this)

## Notification

- ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- ~Cadastre Team (@rkelson)~

**Comment by stdavis** [comment]
I updated the tasks for this issue. There's not much more to do other than decommission the machine.

**Comment by steveoh** [comment]
I agree that jason should handle the backup and decommission requests

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 118

| check | status |
| - | :-: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **1** out of **1** tasks | :+1: |

**Comment by stdavis** [comment]
I've started the data copying. Should be done within the hour.

**Comment by nathankota** [comment]
I'll get Jason going on the backup request.

**Comment by nathankota** [comment]
/remind me to check on the server clone 3/1/2021 after 11 a.m. INC1436818

**Comment by nathankota** [comment]
/remind me to check in with Jason again about the server clone (INC1436818) and decommissioning on March 8, 2021 INC1436818

**Comment by nathankota** [comment]
/remind me to check in with Jason again about the server clone (INC1436818) and decommissioning on March 11, 2021

**Comment by steveoh** [comment]
Can we close this?

**Comment by nathankota** [comment]
not quite yet...still waiting to hear back about a couple things 
![image](https://user-images.githubusercontent.com/15659642/110378233-95726180-8012-11eb-94bd-db48bd2fa4c5.png)

**Comment by steveoh** [comment]
Isn't that all jason's deal?
