### ISSUE TITLE
Remove SGID.TRANSPORTATION.BusStops_UTA from SGID

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#120]
# Summary

- **Internal Dataset Name**: TRANSPORTATION.BusStops_UTA
- **External Dataset Name**: transportation.uta_bus_stops_wasatch_front
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=b047cfbab53f4b579756169aa45e94d4

TRANSPORTATION.BusStops_UTA is out of date and has been replaced by TRANSPORTATION.UTA_StopsAndRidership.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from the Internal SGID (@ZachBeck, completed: `2021/04/13`)
- [x] Delete ArcGIS Online item (@ZachBeck, completed: `2021/04/13`)
  - [x] Add `deprecated` tag to ArcGIS Online item (@ZachBeck, completed: `2021/02/23`)
  - [x] Add `Deprecated` to ArcGIS Online item title(@ZachBeck, completed: `2021/02/23`)
- [x] Unshare item from Open Data (@ZachBeck, completed: `2021/04/13`)
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck, completed: `2021/02/23`)
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2021/02/23`)
- [x] Update `SGID.META.AGOLItems` table (@ZachBeck, completed: `2021/04/13`)
  - delete row if removing from both
  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
- [x] Delete Google Drive data (@ZachBeck, completed: `2021/02/23`)
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2021/04/19`)
- [x] Remove json file from [Backseat Driver](https://github.com/agrc/backseat-driver) (@stdavis, completed `2021/04/19`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2021/04/19`) (waiting on AGOLItems table row to be removed)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2021/04/19`) (waiting on AGOLItems table row to be removed)

### Shelve/Static

_Choose one._

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (name, completed: `2021/00/00`)~
- ~[ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (name, completed: `2021/00/00`)~
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2021/04/19`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/04/19`)

## Are there service dependencies

- Does an application depend on this data?
- Are clients querying this data with the WebAPI?

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
Decent usage

![image](https://user-images.githubusercontent.com/325813/108894676-cf357800-75cf-11eb-99a0-c12b9c19597a.png)

**Comment by steveoh** [comment]
/remind us to start removing these items in 30 days

**Comment by steveoh** [comment]
@ZachBeck will you get the AGOL/Open Data deprecation warning + name change added ASAP?

I think we can update the website and sgid index early to remove the discoverability but let's hold off until the 25th for the rest of the removals.

**Comment by ZachBeck** [comment]
@steveoh what is the AGOL/Open Data deprecation warning & name change? Is it the tag and marking it as deprecated?

**Comment by steveoh** [comment]
```
Add deprecated tag to ArcGIS Online item (@ZachBeck, completed: 2021/00/00)
Add Deprecated to ArcGIS Online item title(@ZachBeck, completed: 2021/00/00)
```

**Comment by jacobdadams** [comment]
FYI, Auditor removed the deprecated name and tag this morning for both this and #119 because the current issue template is not consistent with how Auditor works. I'm working on an update to the template to better guide people in the process, and I'll do the necessary deprecation fixes on these two AGOL items.

**Comment by jacobdadams** [comment]
Ok, Auditor will now keep the `Deprecated` tag on both these items; name edits are still WIP per #122 .

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 120

| check | status |
| - | :-: |
| @ZachBeck has completed **4** out of **8** tasks | :no_entry: |
| @steveoh has completed **1** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 120

| check | status |
| - | :-: |
| @ZachBeck has completed **4** out of **8** tasks | :no_entry: |
| @steveoh has completed **1** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.BusStops_UTA

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 120

| check | status |
| - | :-: |
| @ZachBeck has completed **4** out of **8** tasks | :no_entry: |
| @steveoh has completed **1** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.BusStops_UTA

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
What's the status of this?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 120

| check | status |
| - | :-: |
| ZachBeck has completed **8** out of **8** tasks | :+1: |
| @steveoh has completed **1** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.BusStops_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by stdavis** [comment]
I've got my tasks completed for this issue.
