### ISSUE TITLE
Add 2020 Census data from US Census Bureau

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#123]
# Summary
This porter issue encompasses 6 new census layers for Demographics.SGID: 

    - CensusBlock2020
    - CensusBlockGroups2020
    - CensusTracts2020
    - CensusPlaces2020
    - CensusCounties2020
    - CensusState2020

- **Proposed Data Category**: Demographics
- **Data Description**: 2020 Census geographies
- **Source Agency/Entity**: US Census Bureau
- **Contact**: Greg Bunce
- **Update Frequency**: aside from adding demographic stats when they become available in sept 2021, there will be no updates to these layers.

This data includes census geographies from the 2020 census and will complement our existing 2000 and 2010 census data. As of now, this is just the geographies.  The bureau will release the demographic info in Sept 2021.  At that time, I will add some key demographic fields to these datasets.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@gregbunce on `2021/02/24`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on `2021/02/24`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on `2021/02/24`)

## Where is the data source

_Choose one._

- [x] Internal SGID

## Action items

- [x] Add data to the Internal SGID @gregbunce, completed: `2021/02/24`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2021/02/23`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@gregbunce, completed: `2021/03/02`)
- [x] Complete a `SGID.META.AGOLItems` record (@gregbunce, completed: `2021/02/25`)

## :robot: Automation validation

- [x] Open SGID via cloudb (@steveoh on `2021/02/01`)
- [x] ArcGIS Online via forklift (@stdavis on `2021/03/01`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/03/01`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@gregbunce on `2021/03/02`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce on `2021/02/03`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh  on `2021/03/03`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
i added the 6 tables to the `SGID.META.AGOLItems` table.  @jacobdadams I left the `AGOL_Item_ID` field null.  I need to manually populate that after the layers are in AGOL, right?
![image](https://user-images.githubusercontent.com/16906316/109179757-74bf2780-7747-11eb-91c4-857098cb94ac.png)

**Comment by stdavis** [comment]
> I need to manually populate that after the layers are in AGOL, right?

No, forklift will do this for you.

**Comment by jacobdadams** [comment]
> > I need to manually populate that after the layers are in AGOL, right?
> 
> No, forklift will do this for you.

I thought forklift only updated existing datasets...?

**Comment by gregbunce** [comment]
awesome, you guys are making these tools a joy to use.  nice work!

**Comment by stdavis** [comment]
@jacobdadams https://github.com/agrc/warehouse/blob/013b5b734bbccd36c6fa671b0a423cc804f7c671/sgid/AGOLPallet.py#L164
🤞

**Comment by jacobdadams** [comment]
Oh good, I'm only 9 months behind 😆 

So if I've got this right, Forklift will publish it, and then Auditor will handle the folder, groups, etc. Ideally Auditor would also handle metadata (description, etc) as well, but I don't know how consistently the metadata update is working.

**Comment by steveoh** [comment]
> I thought forklift only updated existing datasets...?

you might be thinking of farm from agol where forklift only updates tables that already exist in internal

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 123

| check | status |
| - | :-: |
| @gregbunce has completed **8** out of **10** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by jacobdadams** [comment]
The AGOL items look good post-Auditor 👍

**Comment by steveoh** [comment]
OpenSGID has been populated. @gregbunce i'll need those sgid index records to finish my last check.

**Comment by gregbunce** [comment]
everything has been checked and completed.  i'm closing this baby out.  Thanks, everyone!  #porterrocks

**Comment by steveoh** [comment]
sgid index hasn't been verified yet.
