### ISSUE TITLE
Remove Utah Total IC and Reservation Tribal Land from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#126]
# Summary

- **Internal Dataset Name**: `environment.Total_IC_and_ReservationTribalLand`
- **External Dataset Name**: `Utah Total IC and Reservation Tribal Land`
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=d10c077c857c41818ecf6237b6812e7d

Jake [recently pointed out](https://agrc.slack.com/archives/C018YQ6J14N/p1617031451018200) that this dataset seems to be a derivative of LandOwnership and possibly other old data. No one seems to know where it came from originally. The [ogm pallet](https://github.com/agrc/ogm-pallets/blob/717eb5ef6772dfeba5c44d53da178ada7eeb10d9/OGMPallet.py#L266) references the source data which is on a DEQ server. deq.enviro.utah.gov used to reference it but it was [removed last year](https://github.com/agrc/deq-enviro/issues/384).

I wonder if this dataset could be removed from SGID? ~**Please don't remove anything until we have made a final decision**.~ We are good to go.

## Migration Guide

It sounds like Land Ownership is an alternative to this dataset.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Add note to ArcGIS Online description noting when layer will be deleted and any replacement layer (@gregbunce, completed: `2021/04/26`)
- [x] Unshare item from Open Data (@gregbunce, completed: `2021/04/26`)
- ~[ ] Remove the SGID Index item (name, completed: `2021/00/00`)~
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@gregbunce, completed: `2021/04/26`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist though one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2021/04/26`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@gregbunce, completed: `2021/04/28`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@gregbunce, completed: `2021/05/10`)
  - Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]
- [x] Remove ArcGIS Online item: (@gregbunce, completed: `2021/05/10`)
  - Manually delete the AGOL item
  -  -OR- 
  - ~Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - -OR-
  - ~Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~ 
  - Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS). 
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2021/00/00`)~
- ~[] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@gregbunce, completed: `2021/00/00`)~
- ~[ ] Update `SGID.META.AGOLItems` table (@gregbunce, completed: `2021/00/00`)~
  - ~cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  - ~set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  - ~set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
- ~[ ] Delete Google Drive data (@gregbunce, completed: `2021/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2021/05/10`)
- [x] Remove json file from [Backseat Driver](https://github.com/agrc/backseat-driver) (@stdavis, completed `2021/05/11`) (it wasn't there)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2021/05/11`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2021/05/11`)

### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2021/00/00`)~
~- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2021/00/00`)~
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2021/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2021/05/10`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/05/10`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2021/05/17`)

## Are there service dependencies

- [x] Does an application depend on this data? (@stdavis)
- [x] Are clients querying this data with the WebAPI? (@steveoh)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
This should be blocked until a decision is made about the removal of this layer.

**Comment by steveoh** [comment]
Has there been any conversations about the removal of this layer?

**Comment by stdavis** [comment]
None that I know of. Maybe that means we should remove it?

**Comment by nathankota** [comment]
I missed seeing this before the combined team meet. I will bring it up in the data team next week, unless you want a decision sooner.

**Comment by stdavis** [comment]
There's no rush on this.

**Comment by nathankota** [comment]
No active maintenance. Data Team discussed and encouraged deprecation. SITLA  landownership is more current.

**Comment by stdavis** [comment]
I think that we are good to move forward on this removal. I've updated the description and put my name next to a few items. It's probably time for the triagers (@steveoh, @gregbunce, & @rkelson) to go through it.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 126

| check | status |
| - | :-: |
| @steveoh has completed **2** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.Total_IC_and_ReservationTribalLand

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship | :no_entry: Did not find environment.Total_IC_and_ReservationTribalLand in the worksheet |

**Comment by jacobdadams** [comment]
Auditor has labeled this as deprecated as of this morning.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 126

| check | status |
| - | :-: |
| @gregbunce has completed **6** out of **12** tasks | :no_entry: |
| @steveoh has completed **2** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.Total_IC_and_ReservationTribalLand

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find environment.Total_IC_and_ReservationTribalLand in the worksheet |

**Comment by gregbunce** [comment]
this issue is scheduled to be closed out on 5/10/2021

**Comment by steveoh** [comment]
Is that when the internal data will also be removed?

**Comment by gregbunce** [comment]
Yeah, that's a good question.  Do you have a preference on when I remove it from Internal?  I could remove it now or wait till when I remove it from AGOL.

**Comment by gregbunce** [comment]
I think I'm done making a mess here - my part should be complete.  let me know if I can help with anything else.

**Comment by steveoh** [comment]
I'm done. @stdavis and @jacobdadams for the finish.

**Comment by stdavis** [comment]
I've completed my tasks. @steveoh Does this need to be removed? https://github.com/agrc/api.mapserv.utah.gov/blob/7c308a1b841ed32252ae128388f680727ef08cfb/WebAPI.API/Models/TableMapping.cs#L211

**Comment by steveoh** [comment]
good find! But no, i'm not updating those.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 126

| check | status |
| - | :-: |
| gregbunce has completed **8** out of **8** tasks | :+1: |
| @steveoh has completed **5** out of **6** tasks | :no_entry: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.Total_IC_and_ReservationTribalLand

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find environment.Total_IC_and_ReservationTribalLand in the worksheet |
