### ISSUE TITLE
Replace existing Municipalities with new version with muni_code field

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#127]
# Summary

- **Proposed Readable Name**: Utah Municipal Boundaries
- **Proposed Internal Dataset Name**: Municipalities
- **Proposed External Dataset Name**: municipal_boundaries
- **Proposed Data Category**: BOUNDARIES
- **Data Description**: Municipalities with added muni_code field
- **Source Agency/Entity**: UGRC
- **Contact**: Mike Heagin
- **Update Frequency**: On going

This data will swapping out the existing BOUNDARIES.Municipalities and is essentially the same, the only difference is a new field has been added to hold a 3 character municipal code as per Bert's request.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x ] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (name on `2021/04/06`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (name on `2021/04/06`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (name on `2021/04/06`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] Add data to the Internal SGID (name, completed: `2021/00/00`)
- [ ] Configure forklift for Farm from AGOL (name, completed: `2021/00/00`)
- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)
- [ ] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2021/00/00`)
- [ ] Complete a `SGID.META.AGOLItems` record (name, completed: `2021/00/00`)
- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [ ] Open SGID via cloudb (@steveoh on `2021/00/00`)
- [ ] ArcGIS Online via forklift (@stdavis on `2021/00/00`)
- [ ] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/00/00`)
- [ ] [Open Data](https://opendata.gis.utah.gov) (name on `2021/00/00`)
- [ ] [gis.utah.gov](https://gis.utah.gov/data) data pages (name on `2021/00/00`)
- [ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [ ] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by ZachBeck** [comment]
I'm hoping that once I replace the data in Internal no other action will be needed since this data is a replacement rather than an addition or removal.

**Comment by steveoh** [comment]
I don't think porter is required for adding a field to a table.

**Comment by steveoh** [comment]
Anyone, please reopen this if you disagree.

**Comment by eneemann** [comment]
I had the same thought as Steve.  But on another note, should we review the codes in the Data team meeting?  It might help to have multiple eyes on them to make sure fit the munis as best as possible.

**Comment by ZachBeck** [comment]
I thought I'd error on the safe side... I'll swap out the data in Internal and leave the old version with the db privileges revoked in there in case we need to roll back. This will be happening to MetroTownships as well.

**Comment by steveoh** [comment]
> should we review the codes in the Data team meeting? It might help to have multiple eyes on them to make sure fit the munis as best as possible.

That makes sense to me. I assumed that had happened since there were multiple values for municipalities and it seemed like some discussion was required from the different stakeholders.
