### ISSUE TITLE
Deprecate mapserv.utah.gov/enterprisezones

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#128]
# Summary

- **Application Name**: Utah Enterprise Zones
- **Application Url**: http://mapserv.utah.gov/enterprisezones

_A short summary of the situation._

Currently, this is a redirect on mapserv that points to this AGOL app: https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=d097ba0c4a3242d6bcbff92f52d82f98

I have vague memories that this used to be a custom app that was so simple that we replaced it with an AGOL map. I recently updated the AGOL app to fix the Chrome map click bug.

@nathankota has spoken with GOED and they said that they don't use it. I don't see any advantages that it has over locate.utah.gov.

I vote that we just get rid of the redirect on mapserv and retire the web app on AGOL. Here's the recent usage:
![image](https://user-images.githubusercontent.com/1326248/114608753-3e882980-9c5b-11eb-9842-7a0a516ff2a7.png)

The other option would be to redirection mapserv to locate.utah.gov but that seems a little much for so little use.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@steveoh, completed: `2021/04/20`)
~- [ ] Remove forklift pallet (name, completed: `2021/00/00`)~
~- [ ] Remove application-specific Databases (name, completed: `2021/00/00`)~
~- [ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)~

### Is there a website?

~- [ ] Remove DNS entry (name, completed: `2021/00/00`)~
~- [ ] Archive source code repository (name, completed: `2021/00/00`)~

_Choose one._

- [x] Remove from the web server (@stdavis, completed: `2021/04/21`)
~- [ ] Replace app with a static page with information (name, completed: `2021/00/00`)~
~- [ ] Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

~- [ ] Stop (name, completed: `2021/00/00`)~
~- [ ] Delete (name, completed: `2021/00/00`)~

### Is there a forklift pallet?

~- [ ] Remove repo (name, completed: `2021/00/00`)~
~- [ ] Remove stale data from forklift hashing and receiving (name, completed: `2021/00/00`)~
~- [ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

### Are there service dependencies?

It's built on the existing [SGID Utah Enterprise Zones hosted feature service](https://utah.maps.arcgis.com/home/item.html?id=dc4539cb9d1548e1a1f31cf5b63e3ad5) so that should stay.

- [x] Deprecate and retire the web map (@stdavis, completed: `2021/05/21`)
    - https://utah.maps.arcgis.com/home/item.html?id=967621d926014900ab075692dfc80056
    - Marked as deprecated on `2021/04/21`
- [x] Deprecate and retire the app (@stdavis, completed: `2021/05/21`)
    - https://utah.maps.arcgis.com/home/item.html?id=d097ba0c4a3242d6bcbff92f52d82f98
    - Marked as deprecated on `2021/04/21`

~- [ ] Validate that the web api does not query it (name, completed: `2021/00/00`)~
~- [ ] Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

~- [ ] Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
I agree to get rid of this.

**Comment by stdavis** [comment]
/remind me to act on this issue in one week if no one has any issues.

**Comment by stdavis** [comment]
I think that it's official. No one cares. :)

Let's go ahead and kill this app.

**Comment by steveoh** [comment]
a quick grep of the website shows hits in these pages

- data/economy/index.html
- data/economy/enterprise-zones/index.html
- data/sgid-index/index.html

**Comment by stdavis** [comment]
> Do we want to remove that as well?

I vote to remove that as well.

**Comment by stdavis** [comment]
I removed the redirect from our webserver and marked the two AGOL items as deprecated.

/remind me to delete the agol items in 30 days

**Comment by stdavis** [comment]
I'm going to assume that @rkelson has looked this issue over and is good with everything. I finished up the last two tasks today.
