### ISSUE TITLE
Remove "Utah Retail Culinary Water Service Areas" AGOL Item

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#130]
# Summary

- **Internal Dataset Name**: `Utilities.CulinaryWaterServiceAreas` (we want to keep this)
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=1d2535e8c31247b9aaff664f6ac9c45d

_A short summary of the situation._

`SGID.Utilities.CulinaryWaterServiceAreas` has grown stale. Water Resources (DNR) now hosts this data in [AGOL](https://utah.maps.arcgis.com/home/item.html?id=dc62a286013f447e88fc45480077c944) and has already shared this data with our org. I propose that we remove our duplicate AGOL item and wire up forklift to farm the data from the DNR AGOL service into internal SGID.

I've compared the schemas between the DNR AGOL item and internal and the only difference is the `COLOR4` field which shows up in internal but it's been all nulls for as long as @rkelson's hair. The only other difference that I could find was that the DNR AGOL item doesn't have the field aliases that we have which don't translate to open SGID anyways.

## Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_

The migration guide is to use the DNR feature layer in arcgis online. If there was a dependency on color4 that will be a breaking change. The open sgid layer and everything else should continue to be the same except it will now be updated from the steward.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Add note to ArcGIS Online description noting when layer will be deleted and any replacement layer (@gregbunce, completed: `2021/04/26`)
- [x] Unshare item from Open Data (@gregbunce, completed: `2021/04/26`)
- [x] Mark the SGID Index item as Deprecated (@gregbunce, completed: `2021/04/26`)
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@gregbunce, completed: `2021/04/26`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2021/04/26`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@gregbunce, completed: `2021/04/28`)

### Hard Delete

_Hard deletes are final. It is recommend to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- ~[ ] Manually remove data from the Internal SGID (@gregbunce, completed: `2021/00/00`)~
  - Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]~ (we want to keep it around to wire up to farm from agol)
- [x] Remove ArcGIS Online item: (@gregbunce, completed: `2021/05/10`)
  - Manually delete the AGOL item
  -  -OR- 
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note. 
  - Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS). 
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- [ ] ~Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)~
- [ ] ~Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2021/00/00`)~
- [x] Update `SGID.META.AGOLItems` table (@stdavis, completed: `2021/04/21`)
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
  - ~set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  - ~set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
- ~[ ] Delete Google Drive data (name, completed: `2021/00/00`)~
- ~[ ] Remove row from `SGID.META.ChangeDetection` (name, completed: `2021/00/00`)~
- ~[ ] Remove json file from [Backseat Driver](https://github.com/agrc/backseat-driver) (name, completed `2021/00/00`)~
- [x] Remove data from forklift hashing and receiving (so that we get the updated schema on the next run) (@stdavis, completed: `2021/04/27`)
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

### Shelve/Static

_Choose one based on situation._

Not that we want to shelve this data. Probably none? @jacobdadams any thoughts?

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2021/00/00`)~
- ~[ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2021/00/00`)~
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2021/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- ~[ ] Remove data from Open SGID (name on `2021/00/00`)~
- ~[ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)~
- ~[ ] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2021/00/00`)~

## Are there service dependencies

- Does an application depend on this data?
- Are clients querying this data with the WebAPI?
- locate.utah.gov uses this data. [Scott] will need to find a way to work around the COLOR4 field in locate.utah.gov. Maybe just add borders to the layer and don't worry about symbolizing by different colors? Or add the COLOR4 field in a post process in the pallet.

## Other Tasks

- [x] Wire up forklift to harvest this data from the DNR AGOL item into internal (@stdavis on `2021/04/21`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 130

| check | status |
| - | :-: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by jacobdadams** [comment]
Auditor has labeled this deprecated as of this morning.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 130

| check | status |
| - | :-: |
| @gregbunce has completed **7** out of **8** tasks | :no_entry: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
this issue is scheduled to be closed out on 5/10/2021

**Comment by steveoh** [comment]
What is the replacement url?

**Comment by steveoh** [comment]
This should not have been marked as deprecated in the stewardship sheet since it was a replacement.

**Comment by stdavis** [comment]
I think that we screwed this deprecation up a little bit. I shouldn't have included this task:
![image](https://user-images.githubusercontent.com/1326248/128933165-778febbf-2548-43b8-996c-d726c4bd9d77.png)

That removed the table from open sgid. I found out today because DEQ is attempting to query that table via our web API.

I also noticed that there is a version of this data in SGID called `SGID.UTILITIES.RetailCulinaryWaterServiceAreas`. Should that have been removed? I've verified that [forklift is updating `SGID.UTILITIES.CulinaryWaterServiceAreas`](https://github.com/agrc/warehouse/blob/bff297dc414a7fac8632d22d1d77b8204302e9e8/sgid/AGOLtoSGIDPallet.py#L52). Can we just trash `SGID.UTILITIES.RetailCulinaryWaterServiceAreas` or should we open a new porter issue?

**Comment by stdavis** [comment]
@ZachBeck Was able to delete `SGID.UTILITIES.RetailCulinaryWaterServiceAreas` today so I think that everything should be wrapped up now.

**Comment by steveoh** [comment]
/remind me tomorrow to look for culinary water service areas in the open sgid

**Comment by stdavis** [comment]
Looks good. 
![image](https://user-images.githubusercontent.com/1326248/129751649-a5050f8a-5047-40dd-ae63-dbbede6fe6ad.png)
