### ISSUE TITLE
Deprecate old Print Proxy Service

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#132]
# Summary

I believe that [this](66d9a0537ae0146d2c94683f64e7310a96f0b52e) was the last place that this service was being used. Everything should now be pointed at the [new service](https://github.com/agrc/serverless-print-proxy). I propose that we shut it off for 30 days and then delete it. Does anyone have any issues with this? Please don't act on any action items until we have decided to move forward.

Service: http://mapserv.utah.gov/arcgis/rest/services/PrintProxy/GPServer

## Action items

- [x] Shut off service (@stdavis, completed: `2021/05/20`)
- [x] Delete service (@stdavis, completed: `2021/06/10`)

## Notification

- [x] Twitter (@steveoh) (not sure if this is worth tweeting about?)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
✅ I'm ok with this

**Comment by gregbunce** [comment]
I have no valuable input in this issue. Have at it.

**Comment by gregbunce** [comment]
Should I be reaching out to anyone to see if they have dependencies?

**Comment by stdavis** [comment]
> Should I be reaching out to anyone to see if they have dependencies?

I believe that the only users of this service would be our own apps. I'm pretty sure that I've transitioned everyone else to the newer solution. Maybe I'll checkout the analytics next week to see if it's still being used.

/remind me to check the analytics next Thursday

**Comment by stdavis** [comment]
/remind me to check the analytics next Thursday

**Comment by stdavis** [comment]
There has only been one request to this service over the past 7 days. I'm going to shut it off today and then delete it in two weeks.

**Comment by stdavis** [comment]
/remind me to delete this service in two weeks
