### ISSUE TITLE
Deprecate mapserv.utah.gov/pointcompare

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#133]
# Summary

- **Application Name**: Address Points Compare
- **Application Url**: http://mapserv.utah.gov/pointcompare/

@gregbunce, can you give us the background and help flesh this out?

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)
- ~[ ] Remove forklift pallet (name, completed: `2021/00/00`)~
- ~[ ] Remove application-specific Databases (name, completed: `2021/00/00`)~
- [ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)

### Is there a website?

- ~[ ] Remove DNS entry (name, completed: `2021/00/00`)~
- [x] Archive source code repository (@stdavis, completed: `2021/08/03`) (couldn't find one)

_Choose one._

- [x] Remove from the web server (@stdavis, completed: `2021/08/03`)
- ~[ ] Replace app with a static page with information (name, completed: `2021/00/00`)~
- ~[ ] Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

- ~[ ] Stop (@stdavis, completed: `2021/00/00`)~
- ~[ ] Delete (@stdavis, completed: `2021/00/00`)~

### Is there a forklift pallet?

- ~[ ] Remove repo (@stdavis, completed: `2021/00/00`)~
- ~[ ] Remove stale data from forklift hashing and receiving (@stdavis, completed: `2021/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2021/00/00`)~

### Are there service dependencies?

- ~[ ] Validate that the web api does not query it (name, completed: `2021/00/00`)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
sure.  i can't speak specifically to the mapserv app, but i can explain what i know and what my role has been in the 'compare sgid address points with vista points' project. 

i adopted this project from keaton after he took on his new cloud architect role in dts.  since then, i believe i ran the process once.

I sat down with keaton before he left and these are my notes on [what it is and how it all works](https://docs.google.com/document/d/1L51xhApEaJAALo86PF5Th7UBFrdOyDo91bATZCbMK9M/edit).

**Comment by stdavis** [comment]
@gregbunce Are there any plans to run this process again in the future?

**Comment by steveoh** [comment]
## conductor results for tasks - 133

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
Pinging @gregbunce :point_up:

**Comment by steveoh** [comment]
/remind gregbunce to answer the question next week

**Comment by steveoh** [comment]
## conductor results for tasks - 133

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by nathankota** [comment]
@gregbunce is going to get in touch with Lt. Gov's Elections Office when he returns to determine if the tool is still needed

**Comment by steveoh** [comment]
## conductor results for tasks - 133

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 133

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 133

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
@gregbunce Did you hear back from the Lt. Gov. Office about this?

**Comment by gregbunce** [comment]
looking at this issue again, i'm beginning to wonder if my process/role (that i described above) has anything to do with this pointcompare app.  

@ZachBeck do you have info on this app?  Who uses is, and for what?  Where does the backend data come from?

FYI: once we have a better idea of what it's used for and by who, then I'm happy to reach out to the Lt Gov's office to see if we can deprecate it.

**Comment by ZachBeck** [comment]
I'm no help. I didn't know this app existed until the deprecate task was opened.

**Comment by stdavis** [comment]
It doesn't appear that it has any analytics set up. I'll hit up Keaton and see if he can shed some light on what it was used for.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/128044513-af6828bf-fea8-4cd3-9659-748c3c055b02.png)

I vote that we move forward with deprecation.

**Comment by gregbunce** [comment]
I support your motion.  But, let's hold off until I hear back from Mark (since I reached out).  I'll let him know we filled in some gaps on its original purpose and it sounds like it's no longer being used.

**Comment by gregbunce** [comment]
It sounds like the vista process I was running (as described at the top of this issue) was somehow linked to this app, but I'm not sure how the output data got into the app.  

response from Mark in the Lt. Gov's office:

> That's a tough one.  It was developed to be used statewide, but SLCo was the test bed.  Pam, whom we worked with in SLCo, has retired.  It was basically an app that took the XY from VISTA and the XY from your geospatial database and then gave us a distance value.  In effect, the user could say, I want to review those with a distance greater than 150, since those may not even be on the same property.
> 
> With redistricting coming up, I'm not sure it won't come up in discussions again, but I'll leave it to you whether it's something worth holding on to a bit longer or not.

**Comment by gregbunce** [comment]
my thoughts are that there's value in the overall purpose of the project (aka: resolving the differences between vista x,y and sgid x.y) but maybe it's time to look for a new solution. 

maybe we lightly deprecate this app with the notation that something newer could replace it - after we better understand the process and need.

**Comment by stdavis** [comment]
I vote that we remove it from the webserver and archive the project. We can always put it back if there is some issue. It's old and needs to be rewritten anyway. If there is a need for something similar in the future, we can certainly come up with a better solution.

**Comment by gregbunce** [comment]
I second that motion.

**Comment by steveoh** [comment]
My triage is completed. There is a vista map service being used in the website. I am unsure if that is used outside of this app and my hunch is that it is so I left the map service section open until further comment.

**Comment by stdavis** [comment]
> I am unsure if that is used outside of this app and my hunch is that it is

That's correct. It's used in mapserv.utah.gov/vista so we need to keep it around. I've updated the summary.

**Comment by stdavis** [comment]
I couldn't [find a repo](https://github.com/search?q=org%3Aagrc+point) for this app in our organization. I looked through the code on the server and it appears that it was just a copy of atlas.

I moved the code to the `_archives` folder on the server. I seriously doubt that there's anything related to this app in google drive or the website. From my perspective, this issue could be closed.
