### ISSUE TITLE
Deprecate QGIS Geocoding Toolbox

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#134]
# Summary

- **Application Name**: QGIS UGRC Geocoding Toolbox
- **Application Url**: https://plugins.qgis.org/plugins/AGRCGeocodingToolbox/ & https://github.com/agrc/qgis-geocoding-toolbox

This [needs some work to transition to QGIS v3](https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3). I'm not sure that anyone uses it although the analytics show thousands of downloads:
![image](https://user-images.githubusercontent.com/1326248/121094884-8be0cd00-c7ac-11eb-8117-caf4a6e5442b.png)

Although, I've always been suspicious of them. 2000 downloads for v0.1 in one month before v1.0.0 was published? Doesn't seem correct to me.

I'm not 100% sure that it still works and I've only had one email related to it in a strange way (they were asking about the license).

My vote is to retired this project. Although if someone thinks that it's useful, I enjoyed working on it and would be happy to upgrade it to v3.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@stdavis, completed: `2021/07/05`)

### Repo

- [x] Add a message about deprecation and invite others to fork if they want to upgrade it (@stdavis, completed: `2021/07/05`)
- [x] Archive source code repository (@stdavis, completed: `2021/07/05`)

### Other Tasks

- [x] Remove plugin from qgis registry: https://plugins.qgis.org/plugins/AGRCGeocodingToolbox/ (@stdavis, completed: `2021/07/05`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
## conductor results for tasks - 134

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 134

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 134

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
@brigsz or @nathankota: Last chance to save the project. Otherwise, it's going to the graveyard.

**Comment by nathankota** [comment]
Given your thorough consideration of it @stdavis, I vote in favor of deprecation and one less source of technical debt to pay

**Comment by steveoh** [comment]
## conductor results for tasks - 134

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
I believe that the only outstanding item is the PR that I submitted to the website repo related to this issue.

**Comment by steveoh** [comment]
## conductor results for tasks - 134

| check | status |
| - | :-: |
| @stdavis has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
I'm going to close this issue for now assuming that @gregbunce and @rkelson don't have anything to add and that @steveoh doesn't want to tweet about this.
