### ISSUE TITLE
Deprecate mapserv dojo widgets cdn

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#135]
# Summary

- **Application Name**: Dojo Widgets on mapserv
- **Application Url**: http://mapserv.utah.gov/cdn/...

I don't believe that these are being used at all.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@stdavis, completed: `2021/06/08`)

### Is there a website?

- [x] Archive source code repository (@stdavis, completed: `2021/06/08`)

_Choose one._

- [x] Archive files on the web server so that we can easily replace them if we break someone's app (@stdavis, completed: `2021/06/08`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [ ] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
I cleared with barry that they stopped using these. That was the only external consumer that I was aware of.

**Comment by stdavis** [comment]
I moved all repos in the agrc-widgets org to the agrc org and then deleted the agrc-widgets org. I don't think that we need to tweet about this so I'm calling it done. 🏁
