### ISSUE TITLE
Deprecate Backseat Driver

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#136]
# Summary

- **Application Name**: Backseat Driver
- **Application Url**: https://github.com/agrc/backseat-driver

Everything that Backseat Driver pushes to Google Drive should be available in Open Data. @ZachBeck & @rkelson Do you use this Backseat Driver anymore?

Looks like we are almost done replacing links on our website. Here are the two outstanding issues:

- [x] https://github.com/agrc/gis.utah.gov/issues/1521
- [x] https://github.com/agrc/gis.utah.gov/issues/1565

**Nothing below should be acted upon until the issues above are closed**

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] backseat driver upload drive folder (@stdavis, completed: `2021/05/12`)

### Is there a website?

- [x] Archive source code repository (@stdavis, completed: `2021/07/12`)

### Other tasks

- [x] Update [porter issue template](https://github.com/agrc/porter/blob/7d3f71ad6df076dd17f3b63651bec49fa011f765/.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md#L67) (@stdavis, completed: `2021/07/12`)
- [x] Delete scheduled tasks on server (@stdavis, completed: `2021/07/12`)
- [x] Delete the GCP Service Account & Project associated with this account (@stdavis, completed: `2021/11/23`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

~- [ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
~- [ ] Cadastre Team (@rkelson)~

**Comment by steveoh** [comment]
## conductor results for tasks - 136

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 136

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
Even though https://github.com/agrc/gis.utah.gov/issues/1565 isn't yet closed, we can move forward with this issue. I've gone through all of the links and non are related to backseat driver.

**Comment by stdavis** [comment]
The service account looks like it comes from a one-off personal project that neither Steve nor I have access to. I've pinged Keaton about it. He's out of the office until Friday.

**Comment by stdavis** [comment]
Waiting on the agrc@utah.gov credentials so that I can clean up the drive links. Also waiting on Keaton to get back in town and hopefully get rid of the GCP project.

**Comment by steveoh** [comment]
Any updates on this @stdavis?

**Comment by stdavis** [comment]
@gregbunce Do you have the google credentials for the agrc@utah.gov account? If so, would you mind adding them to Bitwarden? I need them to clean up the back seat driver stuff.

**Comment by stdavis** [comment]
I was unable to find a GCP project or a service account related to this project. Perhaps we already deleted it? I searched projects for "back" and then searched the "utahkoopserver" project service accounts.

**Comment by steveoh** [comment]
Yeah, it may have been deleted. I'd move forward with that assumption.

**Comment by stdavis** [comment]
> @gregbunce Do you have the google credentials for the [agrc@utah.gov](mailto:agrc@utah.gov) account? If so, would you mind adding them to Bitwarden? I need them to clean up the back seat driver stuff.

Disregard! Steve reminded me that I have [already asked and answered this question in SO teams](https://stackoverflow.com/c/ugrc/questions/78).

**Comment by stdavis** [comment]
Looks like this SN incident was just forgotten: INC1568606. I pinged him in SN and chat.

**Comment by stdavis** [comment]
[RITM0201027](https://utah.service-now.com/sc_req_item.do?sys_id=135ebbd887df0510cf9f437d0ebb35fa&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog)

**Comment by stdavis** [comment]
Finally deleted the files.
