### ISSUE TITLE
Deprecate SBI mapserv application

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#137]
# Summary
UGRC is moving applications from the mapserv server to the cloud. The SBI Locate app has been successfully migrated to [sbilocate.ugrc.utah.gov](sbilocate.ugrc.utah.gov) and the mapserv application can now be deprecated. The DHS contact has been informed of the change to the new application DNS.

- **Application Name**: SBI Locate
- **Application Url**: mapserv.utah.gov/sbi

_A short summary of the situation._
(See summary section above)

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] ~Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)~
- [ ] ~Remove forklift pallet (@steveoh, completed: `2021/00/00`)~
- [ ] ~Remove application-specific Databases (@steveoh, completed: `2021/00/00`)~
- [x] AGRC Projects team drive - active maintenance agreement will remain in the [folder](https://drive.google.com/drive/folders/1xwuSKb0jkJ8Yv4co4FeaEKzrBSRdVrbA) (@nathankota , completed: `2021/06/21`)

### Is there a website?

- [ ] ~Remove DNS entry (@nathankota, completed: `2021/00/00`)~
- [ ] ~Archive source code repository (@steveoh , completed: `2021/00/00`)~

_Choose one._

- [x] Remove from the web server (@steveoh, completed: `2021/06/22`)
- [ ] ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [ ] ~Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

- [ ] ~Stop (name, completed: `2021/00/00`)~
- [ ] ~Delete (@steveoh, completed: `2021/00/00`)~

### Is there a forklift pallet?

- [ ] ~Remove repo (@steveoh, completed: `2021/00/00`)~
- [ ] ~Remove stale data from forklift hashing and receiving (@steveoh, completed: `2021/00/00`)~
- [ ] ~Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2021/00/00`)~

### Are there service dependencies?

- [ ] ~Validate that the web api does not query it (name, completed: `2021/00/00`)~
- [ ] ~Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

- [ ] ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- [ ] ~Cadastre Team (@rkelson)~

**Comment by steveoh** [comment]
I don't see a reason to delete a map service, or archive any source code since this is a migration. I also don't know of any DNS that needs to be removed. We were using a slash address from mapserv before. I will update the issue unless I am missing something.

**Comment by steveoh** [comment]
/remind me in one week to destroy the website

**Comment by steveoh** [comment]
/remind me to destroy the website in one week

**Comment by steveoh** [comment]
/remind me to destroy the website in one week

**Comment by steveoh** [comment]
/remind me to destroy the website on 6/28

**Comment by steveoh** [comment]
There is no forklift or app specific database. I am also going to skip twitter.

**Comment by steveoh** [comment]
Ok, this has been completed
