### ISSUE TITLE
Deprecate deq spills mapserv application

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#138]
# Summary

- **Application Name**: deq spills
- **Application Url**: https://mapserv.utah.gov/deqspills

Deq spills has been migrated to the cloud so the mapserv application should be removed. This task is blocked until the end users have migrated to the new url. @nathankota will you notify us when we are ok to act on this deprecation?

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] ~Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)~
- [ ] ~Remove forklift pallet (name, completed: `2021/00/00`)~
- [ ] ~Remove application-specific Databases (name, completed: `2021/00/00`)~
- [ ] ~AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)~

### Is there a website?

- [ ] ~Remove DNS entry (name, completed: `2021/00/00`)~
- [ ] ~Archive source code repository (name, completed: `2021/00/00`)~

_Choose one._

- [x] Remove from the web server (@stdavis, completed: `2022/05/02`)
- [ ] ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [ ] ~Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

- [ ] ~Stop (name, completed: `2021/00/00`)~
- [ ] ~Delete (name, completed: `2021/00/00`)~

### Is there a forklift pallet?

- [ ] ~Remove repo (name, completed: `2021/00/00`)~
- [ ] ~Remove stale data from forklift hashing and receiving (name, completed: `2021/00/00`)~
- [ ] ~Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

### Are there service dependencies?

- [ ] ~Validate that the web api does not query it (name, completed: `2021/00/00`)~
- [ ] ~Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

- [ ] ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- [ ] ~Cadastre Team (@rkelson)~

**Comment by nathankota** [comment]
Mr. Scott Davis contacted the DEQ dev (Marc) 6/21/2021 about migrating to the new url.

**Comment by steveoh** [comment]
/remind stdavis to check in with marc in 6/28

**Comment by steveoh** [comment]
## conductor results for tasks - 138

| check | status |
| - | :-: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
@stdavis it also looks like the nag thingy got the tasks wrong

**Comment by stdavis** [comment]
I hit up Marc on chat this morning. Maybe he's out of town. He's usually great at responding.

**Comment by stdavis** [comment]
> it also looks like the nag thingy got the tasks wrong

What's wrong? The word "in"? I wonder if it would have dropped it if you would have posted "on 6/28".

**Comment by steveoh** [comment]
## conductor results for tasks - 138

| check | status |
| - | :-: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |

**Comment by stdavis** [comment]
Still waiting on Marc to switch his apps to point to the new DNS. He hurt his back pretty bad. I believe that he was meeting with a surgeon last week. We may just want to wait on this for a while.

**Comment by stdavis** [comment]
Marc is making slow progress: https://github.com/agrc/deq-spills/issues/64

**Comment by steveoh** [comment]
Any updates on this @stdavis?

**Comment by stdavis** [comment]
Just sent Marc another email requesting a status update. He did ask me to create a redmine issue for this last year. [I did](https://redmine-deq.utah.gov/redmine/issues/3461) but there hasn't been any movement on it.

**Comment by stdavis** [comment]
Marc finally got everything updated as of this morning. I removed the app from our web server.
