### ISSUE TITLE
Deprecate elections widget

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#139]
# Summary

- **Application Name**: lt governors voting districts widget
- **Application Url**: https://mapserv.utah.gov/LtGovVotingDistricts_Widget

This widget has been migrated to the cloud so the mapserv application should be removed. This task is blocked until the end users have migrated to the new url on https://elections.utah.gov/map/district-maps. @nathankota will you notify us when we are ok to act on this deprecation?

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] ~Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)~
- [ ] ~Remove forklift pallet (name, completed: `2021/00/00`)~
- [ ] ~Remove application-specific Databases (name, completed: `2021/00/00`)~
- [ ] ~AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)~

### Is there a website?

- [ ] ~Remove DNS entry (name, completed: `2021/00/00`)~
- [ ] ~Archive source code repository (name, completed: `2021/00/00`)~

_Choose one._

- [x] Remove from the web server (@stdavis, completed: `2021/07/01`)
- [ ] ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [ ] ~Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

- [ ] ~Stop (name, completed: `2021/00/00`)~
- [ ] ~Delete (name, completed: `2021/00/00`)~

### Is there a forklift pallet?

- [ ] ~Remove repo (name, completed: `2021/00/00`)~
- [ ] ~Remove stale data from forklift hashing and receiving (name, completed: `2021/00/00`)~
- [ ] ~Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

### Are there service dependencies?

- [ ] ~Validate that the web api does not query it (name, completed: `2021/00/00`)~
- [ ] ~Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

- [ ] ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- [ ] ~Cadastre Team (@rkelson)~

**Comment by nathankota** [comment]
message sent to Elections Office 6/23/2021

**Comment by steveoh** [comment]
/remind @nathankota to check up on this in one week

**Comment by nathankota** [comment]
Dinged Clint about it this morning and he is trying to find out who manages the elections site. The reminder will keep me in line if I don't hear back soon.

**Comment by stdavis** [comment]
https://elections.utah.gov/map/district-maps has been upgraded to point to the cloud-hosted version of the widget. 🎉

**Comment by steveoh** [comment]
Should we wait until the reminder to remove the widget from mapserv?

**Comment by stdavis** [comment]
I couldn't see any reason to. I've put the app in `_archives` on the server.

**Comment by steveoh** [comment]
ok lets hope for no bad browser cache tickets 🤞🏼
