### ISSUE TITLE
Deprecate health facilities

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#141]
# Summary

- **Application Name**: health facilities
- **Application Url**: https://mapserv.utah.gov/healthfacilities

Health facilities has been migrated to the cloud so the mapserv application should be removed. This task is blocked until the end users have migrated to the new url. @nathankota will you notify us when we are ok to act on this deprecation?

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] ~Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2021/00/00`)~
- [ ] ~Remove forklift pallet (name, completed: `2021/00/00`)~
- [ ] ~Remove application-specific Databases (name, completed: `2021/00/00`)~
- [ ] ~AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2021/00/00`)~

### Is there a website?

- [ ] ~Remove DNS entry (name, completed: `2021/00/00`)~
- [ ] ~Archive source code repository (name, completed: `2021/00/00`)~

_Choose one._

- [x] Remove from the web server (@steveoh, completed: `2021/07/14`)
- [ ] ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [ ] ~Redirect somewhere else (name, completed: `2021/00/00`)~

### Is there a map service?

- [ ] ~Stop (name, completed: `2021/00/00`)~
- [ ] ~Delete (name, completed: `2021/00/00`)~

### Is there a forklift pallet?

- [ ] ~Remove repo (name, completed: `2021/00/00`)~
- [ ] ~Remove stale data from forklift hashing and receiving (name, completed: `2021/00/00`)~
- [ ] ~Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

### Are there service dependencies?

- [ ] ~Validate that the web api does not query it (name, completed: `2021/00/00`)~
- [ ] ~Validate that AGRC or applications widgets do not reference it (name, completed: `2021/00/00`)~

## Notification

- [ ] ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- [ ] ~Cadastre Team (@rkelson)~

**Comment by steveoh** [comment]
/remind nathankota to decide what to do with this next monday

**Comment by steveoh** [comment]
## conductor results for tasks - 141

| check | status |
| - | :-: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by nathankota** [comment]
Looks like the basemap works on the new [dev](https://health-facilities.dev.utah.gov/) site, but not [production](https://health-facilities.ugrc.utah.gov/). I am in contact with DOH about how they will migrate to the new app and, therefore, when we can deprecate, repoint, or whatever.

**Comment by nathankota** [comment]
/remind me if I haven't heard back from DOH by July 1, 2021

**Comment by steveoh** [comment]
> Looks like the basemap works on the new [dev](https://health-facilities.dev.utah.gov/) site, but not [production](https://health-facilities.ugrc.utah.gov/).

base map is fixed.

**Comment by steveoh** [comment]
## conductor results for tasks - 141

| check | status |
| - | :-: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |

**Comment by nathankota** [comment]
One final message sent to DOH today. I gave them until the end of this week to decide to keep and redirect the existing DNS to the new site, or fully deprecate in favor of new DNS. 

/remind me on Monday, July 12

**Comment by nathankota** [comment]
Ha! Final, final message sent. Just need confirmation that users are aware of the new site and we can decommission the old one.

**Comment by nathankota** [comment]
Last chance today to hear from Health. 
/remind me to initiate deprecation on 7/15/2021

**Comment by nathankota** [comment]
Last day to hear back from Health.

/remind me on Thursday, July 15

**Comment by nathankota** [comment]
/remind me on Thursday, July 15, 2021

**Comment by nathankota** [comment]
Deprecation may commence. DOH is aware of the new app. @steveoh I told them to migrate away from the old DNS, so can its entry be removed or were there plans to redirect to the new DNS?

![image](https://user-images.githubusercontent.com/15659642/125677076-1dbf9e07-8c87-4b7f-9046-7d86bbf2c45b.png)

**Comment by steveoh** [comment]
Are you suggesting we remove the mapserv.utah.gov dns?

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/125682674-4fbb8702-84c5-46cd-a010-0a2af3c3e8c8.png)

This shows what I someone thought the route should be but if you want a redirect then please update the issue.

**Comment by nathankota** [comment]
> Are you suggesting we remove the mapserv.utah.gov dns?

Nope, brainfart

**Comment by steveoh** [comment]
This has been completed. 404's for old health facilities link.
