### ISSUE TITLE
Deprecate Surface Water Quality on mapserv

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#142]
# Summary

- **Application Name**: Surface Water Quality
- **Application Url**: [mapserv.utah.gov/surfacewaterquality](https://mapserv.utah.gov/surfacewaterquality/)

This application has been switched to firebase hosting at [surface-water-quality.ugrc.utah.gov](https://surface-water-quality.ugrc.utah.gov/). We need to retire the version that is hosted on mapserv being careful not to break people's bookmarks.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@steveoh, completed: `2021/07/26`)
- [x] Let Mark Stanger know about the new DNS (@nathankota, completed: `2021/07/26`)

### Is there a website?

- [x] ~Remove~ Inform DEQ that `wq.deq.utah.gov` needs to be pointed at new DNS, or retired in favor of new DNS (@nathankota , completed: `2021/07/26`)
- [x] Add a redirect on mapserv to point to the new DNS (@stdavis, completed: `2021/06/23`)
- [x] Remove from the web server 30 days after the redirect is implemented (@stdavis, completed: `2021/07/26`)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
I got the redirect on mapserv set up.

**Comment by stdavis** [comment]
/remind me to remove this app from the web server in 30 days

**Comment by steveoh** [comment]
/remind @stdavis to remove this app from the web server in 30 days

**Comment by steveoh** [comment]
> I got the redirect on mapserv set up.

Did you set this up to redirect to https? @nathankota has some comment about http that I think this might be related to?

**Comment by stdavis** [comment]
Yes, the redirect goes to https.

**Comment by steveoh** [comment]
## conductor results for tasks - 142

| check | status |
| - | :-: |
| @nathankota has completed **0** out of **2** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
Appy has been removed from the webserver.

**Comment by steveoh** [comment]
Any reason not to close?

**Comment by nathankota** [comment]
I don't see anywhere that we have the following DNS entry as part of our records, as it looks more like a DEQ dns?
 

> - [ ] Remove old DNS entry: wq.deq.utah.gov (@nathankota , completed: 2021/00/00)

**Comment by steveoh** [comment]
Should we notify them that it is orphaned?

**Comment by nathankota** [comment]
> Should we notify them that it is orphaned?

done

**Comment by steveoh** [comment]
it appears the redirect to the incorrect dns is still active.

**Comment by nathankota** [comment]
Yes, they are aware of the issue now and working to resolve it.

**Comment by steveoh** [comment]
Ok, then I will close. If you disagree then please reopen.
