### ISSUE TITLE
Deprecate mapserv.utah.gov/vista in favor of vista-map.ugrc.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#146]
# Summary

- **Application Name**: Vista
- **Application Url**: https://mapserv.utah.gov/vista/

_A short summary of the situation._

This is another project that has been migrated to GCP.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### gis.utah.gov
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@stdavis, completed: `2021/07/19`)
    - Couldn't find any references.

### Client communication
- [x] Ask Gary Ray to point to the new DNS (@nathankota, completed: `2021/07/15`)
	- This should be a pretty simple replacement: `https://mapserv.utah.gov/vista` should be replaced with `vista-map.ugrc.utah.gov`
	- I know that Gary prefers to have tickets to work from.

### Is there a website?
- [x] Remove from the web server (@stdavis, completed: `2021/07/19`)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
## conductor results for tasks - 146

| check | status |
| - | :-: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 146

| check | status |
| - | :-: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| steveoh has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by nathankota** [comment]
Justin J. and Gary R. contacted today about switching to the new DNS.

**Comment by nathankota** [comment]
/remind me to check in with Justin and Gary if I haven't heard from them by Wednesday, July 14

**Comment by nathankota** [comment]
The changes are in VISTA test, awaiting a schedule for a push to prod.

**Comment by nathankota** [comment]
The VISTA app now uses vist-map.ugrc.utah.gov and deprecation of the mapserv app may continue.
