### ISSUE TITLE
Update github issue templates

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#148]
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

**Comment by jacobdadams** [comment]
👀 
I did a first draft of new templates to complement the sharing page updates back in January (#112). Might be a good opportunity to rework them with forms.

**Comment by steveoh** [comment]
I'm not sure the forms are the right feature for us. We might need to rework our approach. I'd be curious to hear your thoughts once you look into it.

**Comment by steveoh** [comment]
test reminder action
