### ISSUE TITLE
Deprecate mapserv.utah.gov/broadband in favor of firebase deployment

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#150]
# Summary

- **Application Name**: Broadband Residential
- **Application Url**: https://mapserv.utah.gov/broadband

_A short summary of the situation._

This app has been ported to GCP/Firebase. We need to ask GOED to point to the new URL and then remove it from our web server.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@steveoh, completed: `2021/07/26`)
- [x] Ask GOED to update their link on https://business.utah.gov/broadband/ from `https://mapserv.utah.gov/broadband` to `https://broadband.ugrc.utah.gov` (@nathankota, completed: `2021/07/26`)

### Is there a website?

- [x] Redirect somewhere else (@stdavis, completed: `2021/07/26`)
- [x] Remove from the web server (30 days after the redirect is set up) (@stdavis, completed: `2021/08/25`)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
/remind me to remove the redirect from the server if GOED has updated their link in 30 days

**Comment by nathankota** [comment]
GOEO link updated to new dns

**Comment by stdavis** [comment]
Done and done.
