### ISSUE TITLE
Deprecate the Crashmapping app

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#155]
# Summary
DPS and UDOT have contracted with [Numetric](https://numetric.com/) to present and interact with Utah vehicle collision summary data and information. Therefore, we no longer need to support the Utah Vehicle Collision application that was built and maintained by UGRC. Because many users have become accustomed to the crashmapping site over the years, DPS DTS has built a lightweight application to redirect to the Numetric solution. However, while the transfer of ownership of the crashmapping DNS occurs over the next couple of weeks, UGRC will do a temporary redirect from the UGRC crashmapping app to the Numetric app, after which DPS DTS will utilize the crashmapping DNS for their own redirect app. 

- **Application Name**: Utah Vehicle Collisions (a.k.a Crashmapping)
- **Application Url**: [crashmapping.utah.gov](https://crashmapping.utah.gov/)

This is the Numetric app UGRC will redirect to temporarily.

https://udps.numetric.net/utah-crash-summary#/

This is the app that DPS DTS built to handle the redirect once they take ownership of the crashmapping DNS.
http://dps-gov-utah-crashmapping.s3-website-us-west-2.amazonaws.com/

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@steveoh, completed: `2021/09/22`)
- [x] Remove forklift pallet (@steveoh, completed: `2021/09/22`)
- [x] Remove application-specific Databases _DDACTS_ (@nathankota & @MichaelAGRC , taken offline by dbase `2021/09/22`, completed: `2021/10/01`)
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (@nathankota, completed: `2021/09/22`)

### Is there a website?

- [ ] ~Remove DNS entry (name, completed: `2021/00/00`)~
- [x] Archive source code repositories (@steveoh, completed: `2021/09/22`)
- [x] Transfer DNS to DPS - INC1540589 (@nathankota, completed `2021/09/28`)
- [x] Release the crashmapping.dev.utah.gov DNS - INC1540608 (@nathankota, completed `2021/09/23`)
- [x] Remove cloud infrastructure (@steveoh, completed `2021/10/05`)
- [x] Remove SFTP storage and users - INC1540618 (@nathankota, completed `2021/09/22`)

_Choose one._

- [ ] ~Remove from the web server (name, completed: `2021/00/00`)~
- [ ] ~Replace app with a static page with information (name, completed: `2021/00/00`)~
- [x] Redirect somewhere else (@steveoh, completed: `2021/09/22`)

### Is there a map service?

- [ ] ~Stop (name, completed: `2021/00/00`)~
- [x] Delete (@steveoh, completed: `2021/09/22`)

### Is there a forklift pallet?

- [x] Remove repo (@steveoh, completed: `2021/09/22`)
- [ ] ~Remove stale data from forklift hashing and receiving (@steveoh, completed: `2021/00/00`)~
- [ ] ~Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2021/00/00`)~

### Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh, completed: `2021/09/22`)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh, completed: `2021/09/22`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- [ ] ~Cadastre Team (@rkelson)~

**Comment by steveoh** [comment]
Thanks @nathankota, I triaged and assigned you a few tasks.

**Comment by steveoh** [comment]
Do we want to replace this app with another on the main page?

![image](https://user-images.githubusercontent.com/325813/134417664-f32c3c66-d098-47ad-8e11-03c24ac587ed.png)

**Comment by steveoh** [comment]
I archived https://github.com/agrc/crash-web and https://github.com/agrc/crash-db.

**Comment by nathankota** [comment]
Good call on replacing the app on the main page. I will make a task for that. Also think we should track the 30 day redirect in here, even if simply as a reminder once it is implemented.

**Comment by steveoh** [comment]
I removed the pallet from the forklift config and deleted it from the warehouse.

**Comment by steveoh** [comment]
map services are gone and redirect pages are live in firebase hosting.

**Comment by steveoh** [comment]
/remind me in 30 days to tear down the entire gcp project

**Comment by steveoh** [comment]
@nathankota you can release the crashmapping.dev.utah.gov DNS

**Comment by steveoh** [comment]
> greetings! I double-checked with Michael and dbase yesterday about DDACTs database and neither knew of or found a test database, but production db has been removed, so you should be able to proceed with crashmapping cloud infrastructure removal at your convenience - even if you want to before your 2021/10/22 reminder. Totally up to you. https://github.com/agrc/porter/issues/155

**Comment by steveoh** [comment]
ok this is done.
