### ISSUE TITLE
Remove duplicate Utah LiDAR Extents from AGOL

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#157]
# Summary

- **Internal Dataset Name**: n/a
- **External Dataset Name**: Utah LiDAR Extents
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=d2eeeee47ae24afab9db91daf0d1c7ba#overview

We have two different Utah LiDAR Extents datasets on AGOL. This one, which was published from a shapefile uploaded to AGOL in 2014, is horribly out of date. The [other](https://utah.maps.arcgis.com/home/item.html?id=90556bb0e09640648be66013a6ab56e6#overview) is pulling from SDE and updating apporpriately.

## Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_

Just using a Porter issue because this older duplicate is shared publicly. The up-to-date layer will remain and should continue to be used.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Hard Delete

Skipping soft delete due to lack of use and duplicate nature.

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- ~[ ] Manually remove data from the Internal SGID (name, completed: `2021/00/00`)~
  - ~Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]~
- [x] Remove ArcGIS Online item: (@jacobdadams , completed: `2021/00/00`)
  - Manually delete the AGOL item
  -  -OR- 
  - ~Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - -OR-
  - ~Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  - ~Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).~
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)~
- ~[ ] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2021/00/00`)~
- ~[ ] Update `SGID.META.AGOLItems` table (name, completed: `2021/00/00`)~
- ~[ ] Delete Google Drive data (name, completed: `2021/00/00`)~
- ~[ ] Remove row from `SGID.META.ChangeDetection` (name, completed: `2021/00/00`)~
- ~[ ] Remove data from forklift hashing and receiving (name, completed: `2021/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- ~[ ] Remove data from Open SGID (name on `2021/00/00`)~
- ~[ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)~
- ~[ ] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2021/00/00`)~

## Are there service dependencies

- Does an application depend on this data?
- Are clients querying this data with the WebAPI?

## Notification

- ~[ ] Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
@stdavis will you make sure everything is good with regards to the raster app and check off our assignment?

**Comment by jacobdadams** [comment]
Accompanying uploaded shapefile should also be deleted as well: https://utah.maps.arcgis.com/home/item.html?id=9bb6712288a645a5b9451214dfe3d9bf

**Comment by stdavis** [comment]
raster.utah.gov does not touch AGOL so it should be unaffected by this issue. Thanks!
