### ISSUE TITLE
Rename `AGRC Shelf` AGOL group to `UGRC Shelf`, AGRC_Shelved folder to UGRC_Shelved

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#159]
# Summary

- **Name**: `AGRC Shelf`

We need to rename the `AGRC Shelf` AGOL group to `UGRC Shelf` and the `AGRC_Shelved` folder to `UGRC_Shelved` to replace any references to `AGRC` in Auditor per https://github.com/agrc/auditor/issues/61. I'm pretty sure Auditor is the only tool that touches the shelf, but just want to put this out there in case I'm wrong.

## Action items

1. _Assign a person who should complete the task._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Check if any automated Data Team tools would break by changing the name (@gregbunce)
- [x] Check if any automated Dev Team tools would break by changing the name (@steveoh)

**Comment by steveoh** [comment]
## conductor results for tasks - 159

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
done.  nice work switching this stuff over

**Comment by steveoh** [comment]
## conductor results for tasks - 159

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 159

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 159

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 159

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by jacobdadams** [comment]
@steveoh, do you have any heartache with this? I'm seeing @stdavis's work on Sweeper and it's giving me the kick in the pants to get this and auditor sorted so his work doesn't go for naught once the data hit AGOL.

**Comment by steveoh** [comment]
I do not. Item id's shouldn't change so I can't think of any issues. There maybe links to the agrc shelf somewhere that may need updating but I'm sure someone thought of that already.

**Comment by jacobdadams** [comment]
Changes made.
