### ISSUE TITLE
Add Utah US Congressional Districts 2022 to 2032

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#162]
# Summary

- **Proposed Readable Name**: Utah US Congress Districts 2022 to 2032
- **Proposed Internal Dataset Name**: USCongressDistricts2022to2032
- **Proposed External Dataset Name**: Utah US Congress Districts 2022 to 2032
- **Proposed Data Category**: Political
- **Data Description**: Polygons depicting the newly passed US Congressional Districts for Utah. 
- **Source Agency/Entity**: Utah Legislative Redistricting Committee
- **Contact**: Utah Legislative Redistricting Committee
- **Update Frequency**: Decenial

## Background

Recently, the Utah Legislative body voted to approve/pass the US Cong Dist created by the Utah Legislative Redistricting Committee.  Much like in 2000, there are 4 districts in Utah.  These districts show where the 4 Utah Congressmen represent our great state in DC. 

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@gregbunce on `2021/12/03`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on 2021/11/20)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on 2021/11/20)

## Where is the data source

_Choose one._

- [x] Internal SGID

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@mheagin, completed: `2021/11/19`)
~- [ ] Configure forklift for Farm from AGOL (@stdavis, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@mheagin, completed: `2021/12/01`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@mheagin, completed: `2021/12/01`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2021/11/19`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@gbunce on `2022/01/26`)
- [x] ArcGIS Online via forklift (@stdavis on `2021/11/29`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/11/23`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@nathankota  on `2021/11/30`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce on `2021/12/02`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@gbunce on `2022/01/26`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
I removed the farm from AGOL task since the source of this data will be internal.

**Comment by gregbunce** [comment]
we should work through any concerns before we rename the existing layers (as outlined above).  

also, I'd like to use the same naming and renaming convention for the other 3 layers we'll be introducing in porter soon (utah state house; utah state senate, utah school board).  the boundaries for these four layers were recently adopted by the utah leg and signed off on by the gov.  they complete the once-every-10-years data that the state of Utah is responsible for during redistricting.        

the whole idea of adding the end date, is that the data makes more sense.  to me, the single, beginning date is super confusing.

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
the task of renaming these layers has moved to a separate, new porter issue ([167](https://github.com/agrc/porter/issues/167)).

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
The name for this layer should have Utah in front of it. 

- https://opendata.gis.utah.gov/datasets/utah-us-congress-districts/explore
- https://opendata.gis.utah.gov/datasets/utah-us-congress-districts-2002/explore

**Comment by gregbunce** [comment]
@stdavis can I add "Utah" in front of the name in the meta agol items table?  aka: will that kick off the processes to rename the agol data - and also not blow anything else up? 
![image](https://user-images.githubusercontent.com/16906316/144161056-0ced9017-a2f9-4016-8945-26895fcaf002.png)

**Comment by stdavis** [comment]
@gregbunce Changing the value in the `AGOL_PUBLISHED_NAME` field will not mess anything up but it will not automatically update the corresponding AGOL item either. You'll have to do that manually.

**Comment by jacobdadams** [comment]
Auditor will update the title if it's changed in the metatable ☝️

**Comment by gregbunce** [comment]
thanks for the clarification, @stdavis and @jacobdadams   
i'm going to rename the layer in metastable and watch the magic happen from there.  
I'll update the info above in this porter issue to match the new name (the addition of 'Utah').

**Comment by gregbunce** [comment]
/remind me on 12/3/2021 to update the gis.utah.gov data page to match the new name (so the URL to opendata works)

**Comment by jacobdadams** [comment]
The AGOL name was changed to `Utah US Congress Districts 2022 to 2032` in this morning's Auditor run 👍

**Comment by gregbunce** [comment]
[pull request](https://github.com/agrc/gis.utah.gov/pull/1893) to fix ugrc data page link - adding utah back into the layer name.

**Comment by gregbunce** [comment]
@eneemann do you know if sweeper has checked the new political district layers?

**Comment by eneemann** [comment]
Yeah, they were swept on 20 Nov.  The metadata could be improved, the 2 issues below were identified.  Otherwise, they looked good.

1. Summary is longer than Description!
2. Description is missing link to gis.utah.gov data page.

**Comment by mheagin** [comment]
We need to update the download link for the Geodatabase and Shapefiles, they are still going to the 2012 data

**Comment by gregbunce** [comment]
@mheagin are you able to resolve the two issues erik pointed out about the metadata for the 4 new political district layers?  it would only need fixing in the Internal database metadata (aka: ArcCatalog or Pro).   maybe just switch the summary and description and then add a link to the open data URLs.  let me know if you are swamped and i'll take a shot at it. 

> Yeah, they were swept on 20 Nov. The metadata could be improved, the 2 issues below were identified. Otherwise, they looked good.
1. Summary is longer than Description!
2. Description is missing link to gis.utah.gov data page.

**Comment by mheagin** [comment]
Just looking at that, I can add the web link. Not sure about the summary and description they look close but Desc look longer?
![metadata](https://user-images.githubusercontent.com/10677659/144496913-540055f4-0c15-4c88-8a07-32dbca57968c.JPG)

**Comment by gregbunce** [comment]
yeah, that's a little confusing to me, too.  maybe @eneemann can shed light on that.  also, maybe that piece is just fine.  but, adding the links would be good.  maybe that's all we need to do for these.

**Comment by mheagin** [comment]
I could refine the summary a little more and move the parts about it creation to the description.

**Comment by eneemann** [comment]
I think that is more of a warning that the summary and description might be
switched around.  The links are more important.

**Comment by mheagin** [comment]
Take a look now. Is this better?
Summary

This feature class represents 4 Congressional Districts Utah currently comprises for purposes of electing members to the US House of Representatives and defining constituent areas for each seat.



Description

This dataset includes the political districts used for the United States Congressional districts in Utah (US House of Representatives). The US Congress Districts 2022 to 2032 will be used for election purposes beginning January 1, 2022. Elected officials began representing these districts in January 2023. These boundaries supersede the US Congressional Districts that were used in 2012-2021Statewide Political District Boundaries are drawn by the Utah Legislature and adopted into state law as part of the decennial redistricting process that began in 2021. These districts represent US House of Representatives (Congressional) Districts as per Census Block Assignment file enrolled with HB2004.For information and downloads on all political districts check UGRC data page https://gis.utah.gov/data/political/2022-2032-house-senate-congressional-districts/

**Comment by gregbunce** [comment]
it looks good.  thanks, @mheagin
are you able to do that for the reaming 3 political datasets? thanks again

**Comment by mheagin** [comment]
If everyone is fine with that wording I will change the others too.

**Comment by mheagin** [comment]
I have updated all the political districts metadata.

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 162

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
i propose we close this out.  any objections?
