### ISSUE TITLE
Add Utah House Districts 2022 to 2032

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#164]
# Summary

- **Proposed Readable Name**: Utah House Districts 2022 to 2032
- **Proposed Internal Dataset Name**: UtahHouseDistricts2022to2032
- **Proposed External Dataset Name**: Utah House Districts 2022 to 2032
- **Proposed Data Category**: Political
- **Data Description**: Polygons depicting the newly passed Utah State House districts.
- **Source Agency/Entity**: Utah Legislative Redistricting Committee
- **Contact**: Utah Legislative Redistricting Committee
- **Update Frequency**: Decenial

## Background

Recently, the Utah Legislative body voted to approve/pass the Utah State House districts created by the Utah Legislative Redistricting Committee.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@gregbunce on `2021/12/03`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on 2021/11/20)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on 2021/11/20)

## Where is the data source

_Choose one._

- [x] Internal SGID

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@mheagin, completed: `2021/11/19`)
~- [ ] Configure forklift for Farm from AGOL (@stdavis, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@mheagin, completed: `2021/12/01`)
- [x] Add a [Stewardship] (https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@mheagin, completed: `2021/12/01`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2021/11/19`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@gbunce on `2022/01/26`)
- [x] ArcGIS Online via forklift (@stdavis on `2021/11/29`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/11/23`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@nathankota  on `2021/11/30`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce on `2021/12/02`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@gbunce on `2022/01/26`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| stewardship | :no_entry: Did not find POLITICAL.UtahHouseDistricts2022to2032 in the worksheet |

**Comment by mheagin** [comment]
We need to update the download link for the Geodatabase and Shapefiles, they are still going to the 2012 data

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by nathankota** [comment]
Color 4 field will need to be addressed as per https://github.com/agrc/porter/issues/165#issuecomment-1009229077

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahHouseDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
## conductor results for tasks - 164

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
i propose we close this out.  any objections?
