### ISSUE TITLE
Add Utah Senate Districts 2022 to 2032

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#165]
# Summary

- **Proposed Readable Name**: Utah Senate Districts 2022 to 2032
- **Proposed Internal Dataset Name**: UtahSenateDistricts2022to2032
- **Proposed External Dataset Name**: Utah Senate Districts 2022 to 2032
- **Proposed Data Category**: Political
- **Data Description**: Polygons depicting the newly passed Utah State Senate districts.
- **Source Agency/Entity**: Utah Legislative Redistricting Committee
- **Contact**: Utah Legislative Redistricting Committee
- **Update Frequency**: Decenial

## Background

Recently, the Utah Legislative body voted to approve/pass the Utah State Senate districts created by the Utah Legislative Redistricting Committee.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@gregbunce on `2021/12/03`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on 2021/11/20)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on 2021/11/20)

## Where is the data source

_Choose one._

- [x] Internal SGID

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@mheagin, completed: `2021/11/19`)
~- [ ] Configure forklift for Farm from AGOL (@stdavis, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@mheagin, completed: `2021/12/01`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1 to tables(@mheagin, completed: `2021/12/01`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2021/11/19`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@gbunce on `2022/01/26`)
- [x] ArcGIS Online via forklift (@stdavis on `2021/11/29`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/11/23`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@nathankota on `2021/11/30`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce on `2021/12/02`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@gbunce on `2022/01/26`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
@gregbunce I wonder if the table rename tasks for this and the other political districts issues should be moved to their own porter issue. There is potentially a significant amount of impact with renaming tables in SGID and I worry that it could get lost if they are combined with the introduction of new data. They could probably all be grouped into a single issue since they are all very similar.

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
good thinking, @stdavis 

i'll pull it out and get a separate issue going.  thanks for the suggestion.

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @mheagin has completed **1** out of **3** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| stewardship | :no_entry: Did not find POLITICAL.UtahSenateDistricts2022to2032 in the worksheet |

**Comment by mheagin** [comment]
We need to update the download link for the Geodatabase and Shapefiles, they are still going to the 2012 data

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Type | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Type | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by ZachBeck** [comment]
Color4 field has been populated incorrectly. Polygons sharing a common boundary shouldn't have the same color 4 numeric value, in other words neighboring polygons should always have a different color than their neighbor.

**Comment by steveoh** [comment]
@ZachBeck et all, has anyone fixed the color 4 field and the missing item on the stewardship tab?

**Comment by ZachBeck** [comment]
I can't speak to the stewardship tab but I noticed the color 4 field problem for the first time this morning. It looks like this is possibly a problem in all the new political boundary data.

**Comment by mheagin** [comment]
This is no longer possible too many situations where up to six districts come together. Set as best as possible right now.

**Comment by steveoh** [comment]
@mheagin you signed off on the spreadsheet part but it's missing some data that will need to be corrected. The details are in the automatic response.

So do we replace the field with more colors then? Are 4 colors still useful or problematic if there are collisions?

**Comment by ZachBeck** [comment]
The values in the color 4 field need to be updated so there aren't collisions. I have a map request from Senator Anderegg that needs to be printed by tomorrow afternoon that relies on this field.

**Comment by mheagin** [comment]
Yes the four color field does not work for the House or the Senate. Those need to be fix. My machine is not working today so you all are on your own.

**Comment by ZachBeck** [comment]
@mheagin, I updated the Color4 field values so that they're working properly now. Lets chat about the other political feature classes next week if you have time.

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Type | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Type | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |

**Comment by gregbunce** [comment]
i propose we close this out.  any objections?

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/151257143-cb92fe51-b140-4b58-b85a-ed5cf2b2dc15.png)

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| gbunce has completed **2** out of **2** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| gbunce has completed **2** out of **2** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Type | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |

**Comment by stdavis** [comment]
I made this update this morning on the steward ship spreadsheet:
![image](https://user-images.githubusercontent.com/1326248/152831273-43a5037a-5f60-4329-aa83-ee7a4f0a3401.png)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 165

| check | status |
| - | :-: |
| gregbunce has completed **5** out of **5** tasks | :+1: |
| mheagin has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| gbunce has completed **2** out of **2** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.UtahSenateDistricts2022to2032

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
Go team!
