### ISSUE TITLE
Rename existing political districts in SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#167]
# Summary

Rename existing political district layers (this would be the data that's prior to the 2022 data)

We are currently adding the 4 new political districts into the SGID ([US Congressional](https://github.com/agrc/porter/issues/162), [Utah State House](https://github.com/agrc/porter/issues/164), [Utah State Senate](https://github.com/agrc/porter/issues/165), and [Utah School Board Districts](https://github.com/agrc/porter/issues/163)) and using the naming convection of layername and then start date to end date (ex: UtahSchoolBoardDistricts2022to2032).

I propose that we rename the existing corresponding political districts to match this naming convection. This will make the data much more user-friendly and explicit for not only us but the end-user.  I propose we rename the layers in the Internal SGID and the rename will propagate from there.

We should address any concerns and talk through any hesitations in the comments below. 

## School Board

- [ ] rename 'UtahSchoolBoardDistricts2015' to 'UtahSchoolBoardDistricts2012to2022' (@gregbunce on `2021/00/00`)

## Utah House

- [ ] rename 'UtahSenateDistricts2002' to 'UtahSenateDistricts2002to2012' (@gregbunce on `2021/00/00`)
- [ ] rename 'UtahSenateDistricts2012' to 'UtahSenateDistricts2012to2022' (@gregbunce on `2021/00/00`)

## Utah Senate

- [ ] rename 'UtahHouseDistricts2002' to 'UtahHouseDistricts2002to2012' (@gregbunce on `2021/00/00`)
- [ ] rename 'UtahHouseDistricts2012' to 'UtahHouseDistricts2012to2022' (@gregbunce on `2021/00/00`)

## US Congressional

- [ ] rename 'USCongressDistricts2002' to 'USCongressDistricts2002to2012' (@gregbunce on `2021/00/00`)
- [ ] rename 'USCongressDistricts2012' to 'USCongressDistricts2012to2022' (@gregbunce on `2021/00/00`)
- [ ] rename the AGOL name for 'USCongressDistricts2012' from 'Utah US Congress Districts' to 'Utah US Congress Districts 2012 to 2022' (@gregbunce on `2021/00/00`)

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## Where is the data source

_Choose one._

- [x] Internal SGID

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] Add data to the Internal SGID (name, completed: `2021/00/00`)
- [ ] Configure forklift for Farm from AGOL (name, completed: `2021/00/00`)
- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)
- [ ] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2021/00/00`)
- [ ] Complete a `SGID.META.AGOLItems` record (@gregbunce, completed: `2021/00/00`)
- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [ ] Open SGID via cloudb (@steveoh on `2021/00/00`)
- [ ] ArcGIS Online via forklift (@stdavis on `2021/00/00`)
- [ ] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/00/00`)
- [ ] [Open Data](https://opendata.gis.utah.gov) (name on `2021/00/00`)
- [ ] [gis.utah.gov](https://gis.utah.gov/data) data pages (name on `2021/00/00`)
- [ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [ ] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
This seems like an unnecessary breaking change.

**Comment by gregbunce** [comment]
the other option is to only remane the public-facing data via the meta agol items table.  this would still be a potential breaking change for open-sgid users if they've mapped a layer but wouldn't be breaking for open data/agol users (they would only be affected by seeing a new name). 

i think it has more benefits than harm. - clarity.  

but, yes... we should continue to discuss and hash out.  this is good

**Comment by gregbunce** [comment]
/remind us to make decision on this on 12/1/2021

**Comment by stdavis** [comment]
I'm in favor of the change. I like the new naming scheme and I feel like it's worth the pain to standardize the older table names. We should just take our time with notifications and such. 

Also, the tasks that are currently in this issue are for introducing new data. I think that the tasks from the "remove data from sgid" template should also be added since this is essentially deleting old tables and introducing new ones.

**Comment by eneemann** [comment]
I agree that the name changes would be much clearer for users.  'UtahSchoolBoardDistricts2012to2022' is much clearer than 'UtahSchoolBoardDistricts2015'.

For the other layers, is the shared year (like 2012) too confusing?  For example, with 'UtahSenateDistricts2002to2012' and 'UtahSenateDistricts2012to2022', were both boundaries valid during elections in 2012?  Or would it make more sense to start the later period with 2013?  ('UtahSenateDistricts2002to2012' and 'UtahSenateDistricts**2013**to2022'). Or end the earlier period with 2012?  ('UtahSenateDistricts2002to**2011**' and 'UtahSenateDistricts2012to2022').

**Comment by ZachBeck** [comment]
I'm ok with the change, hopefully the disruption is minimal. I think it makes sense to go with a naming convention like 2012to2022 since the boundaries are legally valid during that timeframe even though there is calendar overlap with other years.

**Comment by eneemann** [comment]
`I think it makes sense to go with a naming convention like 2012to2022 since the boundaries are legally valid during that timeframe even though there is calendar overlap with other years.`

Thanks, that's what I was looking for.  I think the proposed naming convention is good then.

**Comment by steveoh** [comment]
I think the hassle of renaming this outweighs the clarity benefits, especially for a dataset that will be considered static or shelved. I'm not a big fan of the `year to year` naming since it can be nebulous in terms of including the year or up to that year but it is the shortest which i like for the database table name. I think for AGOL/OpenData we could expand?

> Also, the tasks that are currently in this issue are for introducing new data. I think that the tasks from the "remove data from sgid" template should also be added since this is essentially deleting old tables and introducing new ones.

I think scotts idea is a good one, and since the majority are in agreement, we should create an intro and a deprecation issue to create overlap of the datasets to allow for the transition. 

The [web api](https://github.com/agrc/api.mapserv.utah.gov/blob/59e33d81a25840806b5045d9a8e978711f160f28/WebAPI.API/Models/TableMapping.cs#L311-L319) will need to be updated since those tables get a lot of requests.

![image](https://user-images.githubusercontent.com/325813/144090150-097aab49-0f14-420f-a9ce-a2e9aa88669e.png)

https://elections.utah.gov/map/district-maps will require updates. We will need to coordinate with the lt gov to make the required changes to [forklift](https://github.com/agrc/lt-gov-political-districts/blob/main/scripts/LtGovPallet.py), [mapserv](https://mapserv.utah.gov/arcgis/rest/services/LtGovPoliticalDistricts/Districts/MapServer), and whatever other items they have going on.

I'm assuming vista will also need to be involved in the disruption.

Maybe the disruption is moot since all of these dependencies will need to be updated to the newest boundary data anyway?

**Comment by gregbunce** [comment]
i'll mention it up again as an alterative - we could leave the table names in Internal and only re-name the public-facing data (via the meta agol table). 

we'd still have to deal with the open sgid table rename, but agol would be stable, right? 

would that be less disruptive?

**Comment by mheagin** [comment]
Not sure about the Vista app, right now when I check it I only see the precincts/VistaBallotAreas shown. I will check with Mark M and find out for sure. I will ask about the district-maps updates too.

**Comment by mheagin** [comment]
Not sure if @ZachBeck makes those or not. or if anyone has talked to him about it>

**Comment by steveoh** [comment]
> @mheagin , i'm sure steve or scott can verify where those layers are coming from. for the district maps, it looks like mapserv ![image](https://user-images.githubusercontent.com/16906316/144098329-6cda493e-2e80-4e3e-b7a7-31d6947c2bc5.png)

I linked to the services in my last comment but here are the more direct links. 

- https://github.com/agrc/lt-gov-political-districts - the embedded app on that page
- https://mapserv.utah.gov/arcgis/rest/services/LtGovPoliticalDistricts/Districts/MapServer - the service it uses
- https://github.com/agrc/lt-gov-political-districts/blob/main/scripts/LtGovPallet.py - the forklift pallet to manage the service

**Comment by gregbunce** [comment]
reading through the thread it sounds like there's enough support to rename the existing layers - not only match the new layers but also clarify the effective dates in the title.

steve's comments are solid and they should be considered and worked out before we move forward.  

i don't believe there is a huge rush on this rename.  i'd rather go slow and do it right. 

so, for me, **the question remains**, do we rename the layers in Internal and watch everything bubble up (and break things) from there or do we keep the names existing names in the Internal and only rename the public-facing stuff (via the metatable's public name filed)?

**Comment by steveoh** [comment]
> so, for me, **the question remains**, do we rename the layers in Internal...

This goes against our policy and shouldn't be a question.

**Comment by gregbunce** [comment]
i'll rephrase and say remove the current layers and re-add them with new names. aka; deprecate and add.

I'm leaning toward renaming the public-facing stuff and leaving the names in Internal.

**Comment by steveoh** [comment]
> remove the current layers and re-add them with new names. aka; deprecate and add.

A rename is a delete and an add. It should be treated as an add and deprecate. We should allow the two datasets to live side by side for the two weeks that we call out in our removal policy.

If this decision isn't black and white we should update our policies to make it so.

**Comment by gregbunce** [comment]
to recap... our policy does not allow us to rename a layer by changing its name in the metastable (via the AGOL_PUBLISHED_NAME field).  The policy suggests that to rename a layer we must add a new layer (with the desired name) and then to deprecate the existing layer.

This is based on the fact that the open sgid contains DB tables and these names should batch the layer names in agol - and changing a table name in open sgid is clearly a breaking change.  However, a name change in agol is not a breaking change, as the URL, etc. stays the same.  

would that be the underlying logic used for name changes in our policies?

**Comment by steveoh** [comment]
I think that sums it up well

**Comment by gregbunce** [comment]
good point on the open data url (using the agol name).  that one slipped my memory.

**Comment by steveoh** [comment]
## conductor results for tasks - 167

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **10** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
/remind me on 11/15/2022 to revisit this issue and make separate porter issues

**Comment by gregbunce** [comment]
we can move forward with 2002 data now as this is not being in the interim for re-predicting purposes. 
deprecate these layers and change the name as move them to 'shelved'

**Comment by steveoh** [comment]
Is the plan to close this issue and spread it into more specific issues?

**Comment by gregbunce** [comment]
Yeah, that makes the most sense.

**Comment by gregbunce** [comment]
I'm closing this issue.  I will be creating a separate issue to rename each of these 4 layers in Jan 2023 when we move these layers to AGOL as 'shelved'.  We chose Jan 2023 b/c they are in use until then (these layers are being used through the November 2022 elections and also through January 2023 as the newly elected officials will then populate the new districts (aka: the 2022_to_2032 districts)).

**Comment by gregbunce** [comment]
I'm closing this issue. I will be creating a separate issue that will rename each of these 4 layers in Jan 2023 when we move these layers to AGOL as 'shelved'. We chose Jan 2023 b/c they are in use until then (these layers are being used through the November 2022 elections and also through January 2023 as the newly elected officials will then populate the new districts (aka: the 2022_to_2032 districts)).

**Comment by mheagin** [comment]
Just want to remind everyone, according to Mark and the elections office, that 2012 data should remain available to the public until we have new elections.  It does reflect what the current elected officials represent. 
Not sure how people hit that data for the "find your legislature" and such app's and we don't want to leave anyone high and dry.

**Comment by gregbunce** [comment]
i have a calendar reminder in by google calendar and the agrc employee calendar to pick this up in Jan 2023.  Also, to keep us on track, here are the notes on [what needs to be done in Jan 2023](https://docs.google.com/document/d/17eqBXA3Rw5g8gtAcZ6muNlszYKDtVSTj8OyG02ieDn4/edit).
