### ISSUE TITLE
Add Housing Unit Inventory from WFRC zipfile

### ISSUE THREAD

**Issue by brigsz** [agrc/porter#171]
# Summary

- **Proposed Readable Name**: Utah Housing Unit Inventory 
- **Proposed Internal Dataset Name**: HousingUnitInventory
- **Proposed External Dataset Name**: housing_unit_inventory 
- **Proposed Data Category**: Planning
- **Data Description**: [file showing affordable housing](https://docs.google.com/document/d/17ptBqtzl7pVQECQwYE1VZWE_zt_QmKtQQoKxyDPFZg0/edit)
- **Source Agency/Entity**: WFRC but it is a compliation of county LIR and parcels
- **Contact**: jdadams@utah.gov analytics@wfrc.org
- **Update Frequency**: annually

This data came from WFRC, they did the work on some Wasatch front counties.  Now Jake of UGRC is to do other counties

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@jacobdadams   on `2022/04/19`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@brigsz  on `2022/01/25`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (No domains detected @nathankota on `2022/02/02`)

## Where is the data source

_Choose one._

- [ ] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))
- [x] Google Drive file ([link](https://drive.google.com/drive/folders/1DquF64ezC3GUk6EFs5Db1p2tkepTPBO7?usp=sharing))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@ZachBeck , completed: `2022/04/21`)
- ~[ ] Configure forklift for Farm from AGOL (name, completed: `2021/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@jacobdadams , completed: `2021/05/17`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@nathankota, completed: `2022/05/16`)
- [x] Complete a `SGID.META.AGOLItems` record (@jacobdadams , completed: `2022/05/03`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2021/05/16`)
- [x] ArcGIS Online via forklift (@stdavis on `2021/05/16`)
	- https://utah.maps.arcgis.com/home/item.html?id=bbdc62867c2340949f530a71666223ab
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/05/14`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@steveoh on `2021/05/16`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2021/05/23`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/05/23`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **6** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **7** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by brigsz** [comment]
Good Morning All,  What is a reasonable time frame to wrap this up?  I know the next two weeks are a bit busy, just wanted to check in.

**Comment by gregbunce** [comment]
I would say the end of next week is reasonable.  the next step is to get it loaded into the Internal DB and wire up the Meta table.

**Comment by brigsz** [comment]
Be careful @gregbunce you have a bunch of stuff flying through the air.  Just wanted to check in

**Comment by gregbunce** [comment]
lso, @nathankota is chatting with me now about this porter issue and has offered to assist and also spread the joy. thanks, kota!

**Comment by jacobdadams** [comment]
@gregbunce, after talking with Nate I'm gonna use my wide, knobby shoulders to butt in and take over a bunch of your tasks to get this out 😆 It'll also help me with my understanding of their code as I work on it for the non-WFRC counties.

**Comment by steveoh** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **5** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **1** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by jacobdadams** [comment]
Talked with Josh this morning about schema and getting data from MAG. A new dataset should be coming in a week or so.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **5** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **1** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by jacobdadams** [comment]
Josh told me MAG is still trying to get their data out, so we're just going to upload what we've got. @gregbunce, @ZachBeck, or @MichaelAGRC, does one of you want to take on the task of adding the table to the internal SGID SDE so that we get all the permissions, etc set right?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @jacobdadams has completed **1** out of **4** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **1** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @jacobdadams has completed **1** out of **4** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for planning.HousingUnitInventory

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find planning.HousingUnitInventory in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for planning.HousingUnitInventory

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| stewardship | :no_entry: Did not find planning.HousingUnitInventory in the worksheet |

**Comment by nathankota** [comment]
@jacobdadams I'm confused that conductor says it's in open data, but I cannot find an AGOL item for it to complete the stewardship doc (?)

**Comment by jacobdadams** [comment]
Yeah, that is interesting. The forklift process to get it uploaded got hung up by the database migration and we're still working through that. It isn't in AGOL yet.

**Comment by stdavis** [comment]
I deleted this data from hashing in forklift so that it would get a fresh push tomorrow night.

**Comment by steveoh** [comment]
Is anyone planning to do the stewardship entry?

**Comment by steveoh** [comment]
Did my checks today, i don't see any references in gis.utah.gov or the sgid index.

**Comment by jacobdadams** [comment]
Yeah, these are forthcoming (got pushed back by UGIC).

**Comment by nathankota** [comment]
[Change log/data stewardship sheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/) updated

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **2** out of **2** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **4** out of **6** tasks | :no_entry: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for planning.HousingUnitInventory

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
I reran the sgid index action and it didn't make any changes. Did you add the website url to the stewardship sheet @jacobdadams?

**Comment by jacobdadams** [comment]
Ah, forgot that. I just added it in 👍

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 171

| check | status |
| - | :-: |
| jacobdadams has completed **4** out of **4** tasks | :+1: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| nathankota has completed **2** out of **2** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for planning.HousingUnitInventory

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
