### ISSUE TITLE
Remove DEQMAP_RBCAOFF from SGID

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#177]
# Summary

- **Internal Dataset Name**: SGID.ENVIRONMENT.DEQMAP_RBCAOFF
- **External Dataset Name**: opensgid.environment.deqmap_rbcaoff
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=e57f4a025d9447dbb0392932089db155

_A short summary of the situation._
DEQ has determined that this table is no longer utilized or necessary, and has not been getting updated, and has requested removal from SGID.

## Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_
It is either unused or, if it is being used, it is no longer correct data. They could get in contact with Rick Saathoff at DEQ/DERR if there are further questions.

This item will not be shelved. ~The replaced data is still accessible via our shelved policy in AGOL (a link to the shelved item).~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Prepend "(Mature Support)" to the end of the item title. (@nathankota , completed: `2022/03/03`)
- [x] Remove all tags other than "Deprecated". (@nathankota , completed: `2022/03/03`)
- [x] Add note to ArcGIS Online description and default popup noting when layer will be deleted and any replacement layer (@nathankota , completed: `2022/03/03`)
- [x] Unshare item from Open Data (@nathankota , completed: `2022/03/03`)
- ~[ ] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (name, completed: `2021/00/00`)~ THERE IS NO STEWARDSHIP TABLE RECORD
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@steveoh, completed: `2022/03/03`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@jacobdadams , completed: `2022/03/03`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@nathankota, completed: `2022/03/18`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@eneemann, completed: `2022/03/18`)
  - ~Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]~
- [x] Remove ArcGIS Online item: (@nathankota , completed: `2022/03/21`)
  - Manually delete the AGOL item
  -  ~-OR-~
  - ~Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manually~ ~changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - ~-OR-~
  - ~Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the~ ~`AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~ 
  - ~Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).~ 
- ~[ ] Remove Farm from AGOL connection (name, completed: `2021/00/00`)~
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2021/00/00`)~
- ~[ ] Add this porter url to the `Deprecated` field of the [Stewardship] (https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2021/00/00`)~ THERE IS NO STEWARDSHIP TABLE RECORD
- [x] Remove row from `SGID.META.AGOLItems` table (@nathankota, completed: `2022/03/18`)
- ~[ ] Delete Google Drive data (name, completed: `2022/00/00`)~ NO G-DRIVE DATA EXISTS
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis , completed: `2022/03/21`)
- [x] Remove data from forklift hashing and receiving (@stdavis , completed: `2022/03/21`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis , completed: `2022/03/21`)

~### Shelve/Static~

~_Choose one based on situation._~

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2021/00/00`)~
- ~[ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2021/00/00`)~
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2021/00/00`)~

~_Add record to table._~

- ~[ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2022/03/21`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/03/03`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2022/03/04`)

## Are there service dependencies

- Does an application depend on this data? No
- [x] Are clients querying this data with the WebAPI? (@steveoh on `2022/03/03`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@nathankota )
- [x] Dev Team (@steveoh)
- ~[ ] Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.DEQMAP_RBCAOFF

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find ENVIRONMENT.DEQMAP_RBCAOFF in the worksheet |

**Comment by stdavis** [comment]
I believe that all tasks have been completed. Just waiting for the 👍 from porter...

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 177

| check | status |
| - | :-: |
| nathankota has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **6** out of **6** tasks | :+1: |
| jacobdadams has completed **2** out of **2** tasks | :+1: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.DEQMAP_RBCAOFF

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find ENVIRONMENT.DEQMAP_RBCAOFF in the worksheet |
