### ISSUE TITLE
Add FacilityPST from DEQ

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#181]
# Summary

- **Proposed Readable Name**: Utah Petroleum Storage Tank Facilities
- **Proposed Internal Dataset Name**: FacilityPST
- **Proposed External Dataset Name**: petroleum_storage_tank_facilities 
- **Proposed Data Category**: Environment
- **Data Description**: Under- and above-ground petroleum storage tanks.
- **Source Agency/Entity**: DEQ/DERR
- **Contact**: Richard Saathoff
- **Update Frequency**: Nightly via deq enviro forklift pallet

This is a [replacement for FacilityUST](https://github.com/agrc/porter/issues/182) that includes a few new fields and adds above-ground tank data. This dataset also has two new related tables that need to be added: [`TankPST`](https://github.com/agrc/porter/issues/183) and [`CompliancePST`](https://github.com/agrc/porter/issues/185).

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@stdavis on `2022/04/01`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@stdavis on `2022/04/01`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@stdavis on `2022/04/01`)
	- This dataset does not use any domains.

## Where is the data source

_Choose one._

- [ ] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))
- [x] Farm from DEQ Database via enviro pallet

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (??, completed: `2022`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson, completed: `2022/04/14`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@rkelson, completed: `2022/04/14`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2022/04/01`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/04/04`)
- [x] [ArcGIS Online](https://utah.maps.arcgis.com/home/item.html?id=4d31fef4543f449ebe04a84909a11023) via forklift (@stdavis on `2022/04/04`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/04/04`)
- [x] [Open Data](https://opendata.gis.utah.gov/datasets/utah::utah-petroleum-storage-tank-facilities/explore) (@stdavis on `2022/04/04`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2022/04/18`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/04/18`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
scott, are you comfortable doing the data pages and the stewardship sheet for these replacement layers or would you like me to handle that?

**Comment by stdavis** [comment]
@gregbunce I would love some help if you are offering.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 181

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **7** tasks | :no_entry: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by stdavis** [comment]
We are waiting on the client to approve the ETL of these datasets in the enviro app project before we move forward with adding them.

**Comment by stdavis** [comment]
The client has approved the data and we are good to add it to SGID. I copied the metadata from FacilityUST with minor modifications. It may need some work to bring it up to date with our [metadata standards](https://gis.utah.gov/about/policy/metadata/).

Here's the data:
[FacilityPST.gdb.zip](https://github.com/agrc/porter/files/8352143/FacilityPST.gdb.zip)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 181

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **7** tasks | :no_entry: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.petroleum_storage_tank_facilities

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find Environment.petroleum_storage_tank_facilities in the worksheet |

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/161314091-a40894cd-3d67-455f-a051-a38934921c0f.png)

**Comment by stdavis** [comment]
@ZachBeck This dataset is already in SGID internal. I'm not sure how it got there. Maybe you added it or maybe forklift did? Either way, it's looking good. Would you mind just verifying that the appropriate permissions are granted to it?

**Comment by ZachBeck** [comment]
@stdavis I didn't add it but it looks good, it's shared out to the internal user.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 181

| check | status |
| - | :-: |
| @stdavis has completed **4** out of **7** tasks | :no_entry: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.FacilityPST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship | :no_entry: Did not find Environment.FacilityPST in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 181

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **7** tasks | :no_entry: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.FacilityPST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship | :no_entry: Did not find Environment.FacilityPST in the worksheet |

**Comment by rkelson** [comment]
I've made updates to the data page and stewardship sheet

**Comment by steveoh** [comment]
Thanks rick. We will let conductor run monday and can close this then when we have the 👍🏼

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 181

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **7** tasks | :no_entry: |
| rkelson has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.FacilityPST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
