### ISSUE TITLE
Remove DEQMAP_TANKUST from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#184]
# Summary

- **Internal Dataset Name**: Environment.DEQMAP_TANKUST
- **External Dataset Name**: deqmap_tankust
- **ArcGIS Online Url**: https://www.arcgis.com/home/item.html?id=2e1fd516848a4b2f9d961ea40756691d

This dataset is being [superseded by TankPST](https://github.com/agrc/porter/issues/183) which adds above-ground tank data.

# No actions should be taken on this until #183 has been completed

## Migration Guide

This dataset has been replaced by [TankPST](https://github.com/agrc/porter/issues/183) which is named `petroleum_storage_tanks` in the Open SGID and "Utah Petroleum Storage Tanks" in the SGID Open Data.
The replaced data is still accessible via our shelved policy in AGOL (TODO).

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Prepend "(Mature Support)" to the end of the item title (@stdavis, completed: `2022/05/16`)
- [x] Remove all tags other than "Deprecated" (@stdavis, completed: `2022/05/16`)
- [x] Add note to ArcGIS Online description and default popup noting when layer will be deleted and any replacement layer (@stdavis, completed: `2022/05/16`)
- [x] Unshare item from Open Data (@stdavis, completed: `2022/05/16`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@stdavis, completed: `2022/05/16`)
	- there wasn't an entry for this table
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@stdavis, completed: `2022/05/16`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@stdavis, completed: `2022/05/16`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@stdavis, completed: `2022/05/31`)

### Hard Delete (scheduled for 2022/05/31)

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@ZachBeck, completed: `2022/05/17`)
  - Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]
- [x] Remove ArcGIS Online item: (name, completed: `2022/05/31`)
  ~- Manually delete the AGOL item~
  -  -OR-
  ~- Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - -OR-
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.
  - Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).
~- [ ] Remove Farm from AGOL connection (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@stdavis, completed: `2022/05/31`)
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@stdavis, completed: `2022/05/31`) - not there
- [x] Update `SGID.META.AGOLItems` table (@stdavis, completed: `2022/05/31`)
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
~  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
~  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
~- [ ] Delete Google Drive data (name, completed: `2022/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2022/05/31`) - it was already gone
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2022/05/31`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2022/05/31`)

### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2022/00/00`)~
- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2022/00/00`)
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2022/00/00`)~

_Add record to table._

- [x] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (@stdavis, completed: `2022/05/31`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@stdavis on `2022/06/06`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/05/16`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2022/05/18`)

## Are there service dependencies

- Does an application depend on this data?
- Are clients querying this data with the WebAPI?

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 184

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **15** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.DEQMAP_TANKUST

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship | :no_entry: Did not find Environment.DEQMAP_TANKUST in the worksheet |

**Comment by jacobdadams** [comment]
Auditor has successfully run against the data in the metatable. However, it moved it back to the Environment folder and re-shared it with the environment group because it is not yet in the AGOLItems_shelved table. Once the row is transferred there, it should move the folder and the group to shelved.

**Comment by stdavis** [comment]
/remind me to move forward with hard delete on 5/31/2022

**Comment by agrc-conductor** [comment]
## conductor results for Environment.DEQMAP_TANKUST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find Environment.DEQMAP_TANKUST in the worksheet |
