### ISSUE TITLE
Add CompliancePST from DEQ/DERR

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#185]
# Summary

- **Proposed Readable Name**: Utah Petroleum Storage Tanks Compliance 
- **Proposed Internal Dataset Name**: CompliancePST
- **Proposed External Dataset Name**: petroleum_storage_tanks_compliance 
- **Proposed Data Category**: Environment
- **Data Description**: A table related to FactilityPST that shows compliance data.
- **Source Agency/Entity**: DEQ/DERR
- **Contact**: Rick Saathoff
- **Update Frequency**: Nightly via DEQ Enviro pallet

This is a [replacement for DEQMAP_COMPLIANCE_UST](https://github.com/agrc/porter/issues/186) that adds above-ground tank data. This table is related to FacilityUST.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@stdavis on `2022/04/04`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@stdavis on `2022/04/05`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@stdavis on `2022/04/01`)
	- This dataset does not have any domains.

## Where is the data source

_Choose one._

- [ ] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))
- [x] Farm from DEQ Database via enviro pallet

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@ZachBeck, completed: `2022/04/01`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
~- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson, completed: `2022/00/00`)~
~- [ ] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@rkelson, completed: `2022/00/00`)~
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2022/04/04`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@stdavis on `2022/04/11`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/04/11`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/04/06`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@stdavis on `2022/04/11`)
- ~[ ] [gis.utah.gov](https://gis.utah.gov/data) data pages (@stdavis on `2022/00/00`)~
- ~[ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/00/00`)~

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
scott, are you comfortable doing the data pages and the stewardship sheet for these replacement layers or would you like me to handle that?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 185

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **7** tasks | :no_entry: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.CompliancePST

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find Environment.CompliancePST in the worksheet |

**Comment by stdavis** [comment]
The client has approved the data and we are good to add it to SGID. I'm still waiting on metadata. I asked Rick Saathoff to help me with it.

Here's the data:
[CompliancePST.gdb.zip](https://github.com/agrc/porter/files/8352123/CompliancePST.gdb.zip)

**Comment by stdavis** [comment]
> scott, are you comfortable doing the data pages and the stewardship sheet for these replacement layers or would you like me to handle that?

@gregbunce Same answer as the other issue. I'd love the help if you have the bandwidth

**Comment by stdavis** [comment]
@ZachBeck or @MichaelAGRC Would you mind loading this data (.zip is in a previous comment) into internal and granting it the appropriate permissions? I can add the metadata later.

**Comment by ZachBeck** [comment]
@stdavis this is loaded now.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 185

| check | status |
| - | :-: |
| @stdavis has completed **1** out of **7** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.CompliancePST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find Environment.CompliancePST in the worksheet |

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/161588607-2a45447c-8255-489e-8118-3bdabf84acf5.png)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 185

| check | status |
| - | :-: |
| @stdavis has completed **4** out of **7** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for Environment.CompliancePST

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship | :no_entry: Did not find Environment.CompliancePST in the worksheet |

**Comment by rkelson** [comment]
this is a table that does not need data page or stewardship changes

**Comment by steveoh** [comment]
Great. Scott, will you close this if it is complete.
