### ISSUE TITLE
Remove DEQMAP_CERCLABRRESTRICT from SGID

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#191]
# Summary

- **Internal Dataset Name**: SGID.ENVIRONMENT.DEQMAP_CERCLABRRESTRICT
- **External Dataset Name**: opensgid.environment.deqmap_cerclabrrestrict
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=a1f9e9046e7342f484365bceda9b9515

_A short summary of the situation._
We have confirmed with DEQ DERR and IT staff that the Enviro "Interactive Map" does not utilize data from this table but, rather, from views directly from a DEQ database; therefore, there is lacking justification to host the table in the SGID any longer. DEQ staff agree.
## Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_

Data in this table are available directly from enviro.utah.gov by filtering for the parent data set and exploring the resulting table(s) of related data. 

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Prepend "(Mature Support)" to the end of the item title (@nathankota , completed: `2022/03/28`)
- [x] Remove all tags other than "Deprecated" (@nathankota , completed: `2022/03/28`)
- [x] Add note to ArcGIS Online description and default popup noting when layer will be deleted and any replacement layer (@nathankota , completed: `2022/03/28`)
- [x] Unshare item from Open Data (@nathankota , completed: `2022/03/28`)
- ~[ ] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (name, completed: `2022/00/00`)~ NO STEWARDSHIP TABLE RECORD
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@nathankota , completed: `2022/03/28`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@nathankota , completed: `2022/03/28`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@stdavis, completed: `2022/04/01`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@ZachBeck, completed: `2022/04/04`)
  - ~Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]~
- [x] Remove ArcGIS Online item: (@nathankota , completed: `2022/04/11`)
  - Manually delete the AGOL item
  -  ~-OR-~
  - ~Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - ~-OR-~
  - ~Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  - ~Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).~
- ~[ ] Remove Farm from AGOL connection (name, completed: `2022/00/00`)~
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2022/00/00`)~
- ~[ ] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (name, completed: `2022/00/00`)~ NO STEWARDSHIP TABLE RECORD

- ~[ ] Update `SGID.META.AGOLItems` table (name, completed: `2022/00/00`)~
  - ~cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  - ~set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  - ~set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
- ~[ ] Delete Google Drive data (name, completed: `2022/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis , completed: `2022/04/01`)
- [x] Remove data from forklift hashing and receiving (@stdavis , completed: `2022/04/01`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis , completed: `2022/04/01`)

### ~Shelve/Static~

~_Choose one based on situation._~

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2022/00/00`)~
- ~[ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2022/00/00`)~
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2022/00/00`)~

~_Add record to table._~

- ~[ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2022/04/11`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/04/11`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2022/03/29`)

## Are there service dependencies

- Does an application depend on this data? No
- [x] Are clients querying this data with the WebAPI? (@steveoh on `2022/03/28`) 

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@nathankota)
- [x] Dev Team (@nathankota )
- ~[ ] Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 191

| check | status |
| - | :-: |
| @nathankota has completed **8** out of **9** tasks | :no_entry: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.DEQMAP_CERCLABRRESTRICT

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find ENVIRONMENT.DEQMAP_CERCLABRRESTRICT in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 191

| check | status |
| - | :-: |
| @nathankota has completed **8** out of **9** tasks | :no_entry: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.DEQMAP_CERCLABRRESTRICT

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find ENVIRONMENT.DEQMAP_CERCLABRRESTRICT in the worksheet |
