### ISSUE TITLE
Add TaxEntities2021 SGID.ECONOMY.TaxEntities2021

### ISSUE THREAD

**Issue by mheagin** [agrc/porter#194]
# Summary

- **Proposed Readable Name**: Utah Tax Entities 2021 
- **Proposed Internal Dataset Name**: TaxEntities2021
- **Proposed External Dataset Name**: Utah Tax Entities 2021 
- **Proposed Data Category**: Economy
- **Data Description**: Polygons depicting the Utah tax entities for 2021
- **Source Agency/Entity**: Utah State Tax Commission
- **Contact**: Utah State Tax Commission 
- **Update Frequency**: Yearly

This is the latest Tax Entities, which include all incorporated bodies that have the power to levy a local property tax such as school districts, counties, cities, special service districts, redevelopment districts, etc.
## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [ ] Sweeper checks have run and passed (@gregbunce on `2022/00/00`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@mheagin on `2022/03/31`)
- [ ] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on `2022/00/00`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- ~[ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@mheagin , completed: `2022/03/31`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@stdavis, completed: `2022/04/01`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@mheagin , completed: `2022/03/31`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2022/04/01`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/04/04`)
- [x] [ArcGIS Online](https://utah.maps.arcgis.com/home/item.html?id=228ac715bbb446e4a4ecfb6dea3c52b1) via forklift (@stdavis on `2022/04/04`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/04/04`)
- [x] [Open Data](https://opendata.gis.utah.gov/datasets/utah-tax-entities-2021/explore) (name on `2022/04/04`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2022/04/06`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/04/06`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 194

| check | status |
| - | :-: |
| mheagin has completed **3** out of **3** tasks | :+1: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
@mheagin is there a problem if `ent_rate` is 0 in all the records i looked at?

**Comment by steveoh** [comment]
The stewardship spreadsheet is missing the open data url in the endpoint column and the website has not been updated with the new year and open data links.

**Comment by gregbunce** [comment]
thanks, mike, for the explanation.  the 2021 date in the title is a little confusing but i get what you're saying.  as long as we explain that (what you said) on the datapage and/or in the metadata that should help folks work out those details.

**Comment by stdavis** [comment]
@nathankota Do I need to update locate to point to this new data?

**Comment by nathankota** [comment]
@stdavis  > Do I need to update locate to point to this new data?

From the [2020 Tax Entity data](https://opendata.gis.utah.gov/datasets/utah-tax-entities-2020/explore) I can't tell what locate might be using. I don't see tax entities as a map layer, and it doesn't seem to include any of the data in the summary report. I do see Tax Increment Areas, which seem to be different. Or maybe they're a subset of the Tax Entities? Let me know what I'm missing.

**Comment by stdavis** [comment]
The Tax Increment Areas layer on the map and in the [summary report](https://github.com/agrc/locate/blob/22b0c15adcba91a88ecec30efecdf22505ad8f81/lib/app/templates/ReportTemplate.html#L58-L82) is the tax entity data [joined with some static county contacts](https://github.com/agrc/locate/blob/22b0c15adcba91a88ecec30efecdf22505ad8f81/scripts/locate_pallet.py#L130-L150).

**Comment by nathankota** [comment]
Thank you for the reminder. Yes, this should be updated in Locate. 

> The Tax Increment Areas layer on the map and in the [summary report](https://github.com/agrc/locate/blob/22b0c15adcba91a88ecec30efecdf22505ad8f81/lib/app/templates/ReportTemplate.html#L58-L82) is the tax entity data [joined with some static county contacts](https://github.com/agrc/locate/blob/22b0c15adcba91a88ecec30efecdf22505ad8f81/scripts/locate_pallet.py#L130-L150).

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2021

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
