### ISSUE TITLE
Add TaxAreas2021 SGID.ECONOMY.TaxAreas2021

### ISSUE THREAD

**Issue by mheagin** [agrc/porter#195]
# Summary

- **Proposed Readable Name**: Utah Tax Areas2021 
- **Proposed Internal Dataset Name**: TaxAreas2021
- **Proposed External Dataset Name**: Utah Tax Areas 2021 
- **Proposed Data Category**: ECONOMY
- **Data Description**: Centrally assessed property tax analysis areas
- **Source Agency/Entity**: Utah State Tax Commission
- **Contact**: Utah State Tax Commission
- **Update Frequency**: Yearly

This dataset represents Taxing Districts/Areas in the State of Utah as maintained by the Utah State Tax Commission (USTC). Each taxing district polygon represents a unique combination of overlapping taxing entities. The property tax within a taxing district should be the same for all residential properties.
## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@gregbunce on `2022/04/01`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@mheagin  on `2022/03/31`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on `2022/04/11`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- ~[ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@mheagin , completed: `2022/03/31`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@mheagin, completed: `2022/04/04`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@mheagin , completed: `2022/03/31`)
- [x] Complete a `SGID.META.AGOLItems` record (@stdavis, completed: `2022/04/01`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/04/05`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/04/04`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/04/04`)
- [x] [Open Data](https://opendata.gis.utah.gov/datasets/utah-tax-areas-2021/explore) (@stdavis on `2022/04/04`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2022/04/06`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/04/06`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxAreas2021

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
The stewardship spreadsheet is missing the open data url in the endpoint column and the website has not been updated with the new year and open data links.

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxAreas2021

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
