### ISSUE TITLE
Add SGID.POLITICAL.DistrictCombinationAreas2022 currently in SDE to AGOL

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#199]
# Summary

- **Proposed Readable Name**: Utah District Combination Areas 2022 
- **Proposed Internal Dataset Name**: SGID.POLITICAL.DistrictCombinationAreas2022
- **Proposed External Dataset Name**: Utah_District_Combination_Areas_2022 
- **Proposed Data Category**: POLITICAL
- **Data Description**: Data set reflects the unique political district areas.
- **Source Agency/Entity**: UGRC and The Lieutenant Governor's Office
- **Contact**: Mike Heagin mheagin@utah.gov
- **Update Frequency**: Static

_Introduce your data, where it comes from, why it is being added etc._
Data currently resides in SDE and needs to be made available to AGOL and OpenData.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID - already is
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@eneemann on `nightly`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@rkelson on `2022/04/26`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@rkelson `2022/04/26`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- ~[x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@mheagin, completed: `2022/0?/??`)~
- ~[ ] Configure forklift for Farm from AGOL (, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson, completed: `2022/04/26`) This data, similar to the 2012 data, is not on https://gis.utah.gov/data/political/2022-2032-house-senate-congressional-districts/
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@rkelson, completed: `2022/05/02`)
- [x] Complete a `SGID.META.AGOLItems` record (@rkelson, completed: `2022/05/02`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/05/16`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/05/23`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/05/04`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@rkelson on `2022/00/00`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson `2022/05/04`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/05/16`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by rkelson** [comment]
It would be super awesome if at the least we could get this layer propagating to AGOL by next week so development can begin.

**Comment by steveoh** [comment]
@jacobdadams and @stdavis do we need to add an item to the meta table to let the pallet push it out, then create the shelved record so auditor moves it to the right location?

**Comment by stdavis** [comment]
> * Complete a `SGID.META.AGOLItems` record

Is the key to getting it propagating to AGOL.

**Comment by jacobdadams** [comment]
phew, I'm glad I was telling the truth in the data team meeting 😅 

Are we shelving the previous combined districts layer, or will they both live in internal(sde)/open sgid for a while?

**Comment by rkelson** [comment]
@jacobdadams let's plan to keep both for now considering we are storing some of the other historical district layers

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **4** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find POLITICAL.DistrictCombinationAreas2022 in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
@rkelson This is waiting on you and the stewardship spreadsheet.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
@rkelson still waiting on you here.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 199

| check | status |
| - | :-: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Data Source | :no_entry: |
| - Website URL | :no_entry: |
| - Description | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.DistrictCombinationAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
