### ISSUE TITLE
Add GSL Water Level 2016

### ISSUE THREAD

**Issue by eneemann** [agrc/porter#202]
# Summary

- **Proposed Readable Name**: Utah Great Salt Lake Water Level 2016
- **Proposed Internal Dataset Name**: GSLWaterLevel2016
- **Proposed External Dataset Name**: great_salt_lake_water_level_2016
- **Proposed Data Category**: Water
- **Data Description**: A polygon representation of the Great Salt Lake and shoreline as captured during the 2016 LiDAR collection project.
- **Source Agency/Entity**: UGRC
- **Contact**: UGRC
- **Update Frequency**: Not planned

This is a new offering that depicts the extent and shoreline of the Great Salt Lake during the time of the 2016 LiDAR collection project. It was created from breaklines that were included in the LiDAR project deliverables in order to show a more recent view of the Great Salt Lake's extent within the context of the recent decades-long drought. The lake level in 2016 was right around the historical low point, which was only since broken in 2021.  Therefore, the 2016 lake level and shoreline are very similar to the current lake level and shoreline (early 2022), providing a decent proxy for recent lake conditions.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (name  on `2022/05/03`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (name on `2022/05/05`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (name on `2022/00/00`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- ~[ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@eneemann , completed: `2022/00/00`)
- ~[ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson, completed: `2022/05/05`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@eneemann, completed: `2022/00/00`)
- [x] Complete a `SGID.META.AGOLItems` record (@eneemann, completed: `2022/00/00`)
- ~[] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/05/05`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/05/05`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/05/05`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@eneemann on `2022/05/05`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson on `2022/05/05`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/05/16`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by eneemann** [comment]
I just added the website URL to the stewardship doc

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 202

| check | status |
| - | :-: |
| eneemann has completed **4** out of **4** tasks | :+1: |
| rkelson has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by steveoh** [comment]
🎉
