### ISSUE TITLE
Deprecate DAQ Compliance App

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#203]
The original sponsor of the app left DAQ a few years ago. Since then DAQ has developed a Survey123 app and some other AGOL capabilities to replace their need for the compliance application.

- **Application Name**: DAQ Compliance
- **Application Url**: complianceapp.utah.gov (complianceapp.dev.utah.gov)

_A short summary of the situation._
(see summary above)

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2022/00/00`)~
- ~[ ] Remove forklift pallet (@steveoh , completed: `2022/00/00`)~
- ~[ ] Remove application-specific Databases (-, completed: `2022/00/00`)~
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (@nathankota, completed: `2022/05/05`) - only a notes doc was found and deleted

### Is there a website?

- [x] Remove DNS entry (@nathankota , completed: `2022/05/10`)
- [x] Archive source code repository (@steveoh , completed: `2022/05/05`)
- ~[ ] Remove app-specific quad word from Discover system (-, completed: `2022/00/00`)~

_Choose one._

- [x] Remove from the web server (@steveoh, completed: `2022/05/05`)
- ~[ ] Replace app with a static page with information (name, completed: `2022/00/00`)~
- ~[ ] Redirect somewhere else (name, completed: `2022/00/00`)~

### Is there a map service?

- ~[ ] Stop (-, completed: `2022/00/00`)~
- ~[ ] Delete (-, completed: `2022/00/00`)~
- ~[ ] Unregister Data Store in ArcGIS Server (-, completed: `2022/00/00`)~

### Is there a forklift pallet?

- ~[ ] Remove repo (-, completed: `2022/00/00`)~
- ~[ ] Remove stale data from forklift hashing and receiving (-, completed: `2022/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (-, completed: `2022/00/00`)~

### Are there service dependencies?

- ~[ ] Validate that the web api does not query it (-, completed: `2022/00/00`)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (-, completed: `2022/00/00`)~

## Notification

- ~[ ] Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- ~[ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- ~[ ] Cadastre Team (@rkelson)~

**Comment by steveoh** [comment]
I'm done.

**Comment by nathankota** [comment]
[INC1648775](https://utah.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=74ddb1e687970d5002637489cebb35ed%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) for the DNS records.

**Comment by nathankota** [comment]
messaged Lexie to remove _agrc_deqedocs_ro_ user from ITDB222SP

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 203

| check | status |
| - | :-: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| steveoh has completed **3** out of **3** tasks | :+1: |
