### ISSUE TITLE
Add EMS Response Areas

### ISSUE THREAD

**Issue by eneemann** [agrc/porter#208]
# Summary
_Note: the name of this data has not yet been finalized._

- **Proposed Readable Name**: Utah EMS Response Areas
- **Proposed Internal Dataset Name**: EMSResponseAreas
- **Proposed External Dataset Name**: EMS_Response_Areas
- **Proposed Data Category**: SOCIETY (to match other NG911-centric datasets)
- **Data Description**: This polygon data was created to represent Emergency Medical Service (EMS) response areas in Utah for the Next-Generation 911 system (NG911).  It depicts the primary EMS response agency for a given location in Utah and was compiled from a variety of data sources.  The response areas represent a variety of service levels (paramedic, advanced EMT, with or without transport capability, etc.), but generally include 911 scene response. 
- **Source Agency/Entity**: UGRC
- **Contact**: Erik Neemann
- **Update Frequency**: As needed

_This dataset contains a polygon representation of Emergency Medical Service (EMS) response areas in Utah, intended to depict the primary response agency for a given area.  The primary use of the data will be for the NG911 system.  It will be added to the [Public Safety data page](https://gis.utah.gov/data/society/public-safety/)._

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@eneemann on `2022/06/23`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@eneemann on `2022/06/22`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@eneemann on `2022/06/22`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- ~[ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@ZachBeck, completed: `2022/06/24`)
- ~[ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@eneemann, completed: `2022/06/27`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@eneemann, completed: `2022/06/24`)
- [x] Complete a `SGID.META.AGOLItems` record (@eneemann, completed: `2022/06/24`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@eneemann on `2022/06/27`)
- [x] ArcGIS Online via forklift (@eneemann on `2022/06/27`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/06/27`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@eneemann  on `2022/06/27`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@eneemann  on `2022/06/27`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@eneemann  on `2022/06/27`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for society.EMSResponseAreas

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |
