### ISSUE TITLE
Add Fire Response Areas

### ISSUE THREAD

**Issue by eneemann** [agrc/porter#209]
# Summary
_Note: the name of this data has not yet been finalized._

- **Proposed Readable Name**: Utah Fire Response Areas 
- **Proposed Internal Dataset Name**: FireResponseAreas
- **Proposed External Dataset Name**: Fire_Response_Areas
- **Proposed Data Category**: SOCIETY (to match other NG911-centric datasets)
- **Data Description**: This polygon data was created to represent fire response areas in Utah for the Next-Generation 911 system (NG911).  It depicts the primary fire response agency for a given location in Utah and was compiled from a variety of data sources.  The response areas represent career and volunteer fire departments at a variety of levels including local, municipal, county, state, and federal agencies, as well as a few private or industrial organizations.
- **Source Agency/Entity**: UGRC
- **Contact**: Erik Neemann
- **Update Frequency**: As needed

_This dataset contains a polygon representation of fire response areas in Utah, intended to depict the primary response agency for a given location._

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@eneemann on `2022/06/23`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@eneemann on `2022/06/22`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@eneemann on `2022/06/22`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- ~[ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@ZachBeck, completed: `2022/06/24`)
- ~[ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@eneemann, completed: `2022/06/27`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@eneemann, completed: `2022/06/24`)
- [x] Complete a `SGID.META.AGOLItems` record (@eneemann, completed: `2022/06/24`)
- ~[ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@eneemann on `2022/06/27`)
- [x] ArcGIS Online via forklift (@eneemann on `2022/06/27`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/06/27`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@eneemann on `2022/06/27`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@eneemann on `2022/06/27`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/06/27`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 209

| check | status |
| - | :-: |
| @eneemann has completed **5** out of **6** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
