### ISSUE TITLE
Add New Application Template

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#212]
We have a template for [deprecating an app](https://github.com/agrc/porter/blob/main/.github/ISSUE_TEMPLATE/3-deprecate-application.md) but not for introducing one. Is there any consensus on creating one? It would help us remember things like #210. Maybe there are other steps that we should be verifying when we create new apps?

**Comment by steveoh** [comment]
I bet @nathankota and @brigsz could come up with a checklist.

- Maintenance contract
- Archer diagram
- Etc

**Comment by nathankota** [comment]
I will give a shot at adding to the list Steve started. For Porter, the list might fit well into the current layout where the issue creator (with help from whomever is needed) checks the box of the things that are needed, then signs/dates them when they are complete? Unless we need two sections: one for the required items, another for when they are completed? 

- [ ] SOW or similar agreement (maybe not this, b/c it will have been in place well before adding to APM)
- [ ] Maintenance contract
- [ ] Archer diagram
- [ ] Service Now task
- [ ] GitHub repo (add link)
- [ ] Primary client contact (? maybe not in Porter)
- [ ] ... (what else?)
