### ISSUE TITLE
Add H3 hexes for the state

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#214]
# Summary

- **Proposed Readable Name**: Utah H3 Hexes Level 5/6/7/8/9
- **Proposed Internal Dataset Name**: h3_hexes_z5/6/7/8/9
- **Proposed External Dataset Name**: h3_hexes_z5/6/7/8/9 
- **Proposed Data Category**: Index
- **Data Description**: The H3 hexes covering the State of Utah at zoom levels 5-9
- **Source Agency/Entity**: UGRC
- **Contact**: Jacob Adams
- **Update Frequency**: Static

These are five datasets, one for each H3 hex zoom levels 5-9. They were created using the method described in my [blog post](https://gis.utah.gov/using-h3-hexes/). I had to buffer the state boundary to make sure I got all the hexes that cover the state (the `h3.polyfill` method just searches if the centroid of a hex is within a polygon), so there are some hexes that are outside the state boundary.

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@jacobdadams  on `2022/12/13`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@jacobdadams on `2022/11/18`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@jacobdadams on `2022/11/18`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@jacobdadams, completed: `2022/11/09`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@jacobdadams, completed: `2022/12/19`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@jacobdadams, completed: `2022/12/12`)
- [x] Complete a `SGID.META.AGOLItems` record (@jacobdadams, completed: `2022/12/13`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/12/19`)
- [x] ArcGIS Online via forklift (@jacobdadams on `2022/12/15`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/12/15`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@jacobdadams on `2022/12/19`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@jacobdadams on `2022/12/19`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/12/19`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
~- [ ] Cadastre Team (@rkelson)~

**Comment by gregbunce** [comment]
i agree. I think it's super useful for comparative analysis and having these spatial pieces (the geom) readily available will be a huge time saver and also make the system easier to work with.  i think if it's in the sgid, other folks will take advantage of it as well. 

i would say if an official source decides to serve it in the future then we point to that layer, but in the meantime, we serve it for ease of use.

that's my opinion. 
others?

**Comment by jacobdadams** [comment]
Yeah, what Greg said. It provides a standardized grid that other agencies can use in their analyses. I see it as a functional/foundational layer.

**Comment by steveoh** [comment]
We'll need to update the proposed names. `/` in a table name is not a great idea. If we follow the political boundary convention it would be something like `h3_hexes_5_to_9`.

**Comment by jacobdadams** [comment]
There are five different layers- 5, 6, 7, 8, and 9.

**Comment by stdavis** [comment]
It seems like a good fit for the SGID to me as well. Just because it allows for a common standard for analysis across the state.

**Comment by jacobdadams** [comment]
For sweeper, should I do that before I load into SGID internal or wait until its in there and let the main sweeper check get it?

**Comment by eneemann** [comment]
You could probably let sweeper get it after loading to internal.

**Comment by jacobdadams** [comment]
Ok, here's an interesting licensing thought. The H3 system itself is licensed under Apache 2.0 (an open-source, preserve-copyright license). However, the polygons are generated by the H3 system but are not necessarily part of the system or the code (you don't download the polygons, you generate them).

Does this mean the polygons are still under the Apache 2.0 license? Or can we put them under our CC license?

And if it's under Apache, is there anything special we need to do to tell sweeper?

**Comment by steveoh** [comment]
Does that imply we shouldn't use h3 in the table name?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 214

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **7** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by steveoh** [comment]
@eneemann or someone, will you create a draft pr referencing this issue as a part of the introduction steps please.

**Comment by jacobdadams** [comment]
I've got a branch read for sweeper; @steveoh or @eneemann, can you give me write access to the repo so I can push?

**Comment by steveoh** [comment]
> I've got a branch ready for sweeper; @steveoh or @eneemann, can you give me write access to the repo so I can push?

It looks like you are already a contributor. What's the error you get?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 214

| check | status |
| - | :-: |
| @jacobdadams has completed **3** out of **9** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 214

| check | status |
| - | :-: |
| @jacobdadams has completed **3** out of **10** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for indices.h3_hexes_z5

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find indices.h3_hexes_z5 in the worksheet |

**Comment by jacobdadams** [comment]
Ok, sweeper has been updated with the h3 license info, along with some dependency updating. @eneemann, what do we need to do to get that updated on the main sweeper instance?

**Comment by steveoh** [comment]
I'll update the package in production

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 214

| check | status |
| - | :-: |
| @jacobdadams has completed **8** out of **11** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |

**Comment by jacobdadams** [comment]
Ok, I think I've got all my stuff done. I'm marking Open Data as verified because they work if you link directly to them in open data. They don't show up if you search, but that's the broader Index Group issue and not specifically these layers.
