### ISSUE TITLE
Remove and shelve outdated Utah US Congress Districts from Open SGID (remain in AGOL as shelved)

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#217]
# Summary

- **Internal Dataset Name**: USCongressDistricts2002
- **Internal Dataset Name**: USCongressDistricts2012

---

- **External Dataset Name**: [Utah US Congress Districts 2002](https://opendata.gis.utah.gov/maps/utah-us-congress-districts-2002)
- **External Dataset Name**: [Utah US Congress Districts](https://opendata.gis.utah.gov/maps/utah-us-congress-districts)

---

- **ArcGIS Online Url**: [Utah US Congress Districts 2002](https://utah.maps.arcgis.com/home/item.html?id=62580d50881f48489f2813358cad791d)
- **ArcGIS Online Url**: [Utah US Congress Districts](https://utah.maps.arcgis.com/home/item.html?id=f86be475250b474d965e42971f50c0d3)

---

_A short summary of the situation._
These two Congress Districts are no longer active.  As of Jan 2023, we are now using the latest US Congresseation districts and these need to be removed from Open Data but made available in AGOL under the 'shelved' tag.  Also, we should rename the item names in AGOL to be more descriptive and to better match our current naming convention for this layer.  The remaining should be as follows:

- Utah US Congress Districts 2002 to 2012
- Utah US Congress Districts 2012 to 2022

## Migration Guide

This dataset has been replaced by [Utah US Congress Districts 2022 to 2032](https://opendata.gis.utah.gov/maps/utah-us-congress-districts-2022-to-2032). 

At this point, we should be migrating applications and users away from this outdated layer and onto the latest data.

Let's do a soft delete before we do a hard delete (aka: remove from Open Data) because of the many systems and users that were/are potentially using this data.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Remove "Authoritative" tag from AGOL (@gregbunce, completed: `2023/01/31`)
- [x] Add "Shelved" tag to AGOL item (@gregbunce, completed: `2023/01/31`)
- [x] Update the ArcGIS Online description, informing users how this layer was used in the past (@gregbunce, completed: `2023/01/31`)
- [x] Unshare item from Open Data (@gregbunce, completed: `2023/01/31`)
- [x] Rename the AGOL layer if needed (@gregbunce, completed: `2023/01/31`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row with the agol item URL now that is shelved and note that it has been shelved in the description column (@gregbunce, completed: `2023/01/31`)
- [x] Change `Authoritative` field to null in `SGID.META.AGOLItems`. Allow to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2023/01/31`)
    - [x] remove itemid in meta table (@gregbunce, completed: `2023/01/31`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@gregbunce, completed: `2023/02/10`)

### Shelve/Static

_Choose one based on situation._

- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (@gregbunce, completed: `2023/01/31`)

_Add record to table._

- [x] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (@gregbunce, completed: `2023/01/31`)

### Hard Delete (to happen after 2/15/2023)

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@gregbunce, completed: `2023/02/15`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2023/02/06`)
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2023/02/27`)
- [x] Remove data from forklift hashing and receiving (@steveoh, completed: `2023/02/27`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2023/02/27`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Verified that data has been removed from Open SGID (@gregbunce on `2023/02/15`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2023/02/27`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2023/02/27`)

## Are there service dependencies

- Does an application depend on this data? Yes
- [x] Figure out what to do with http://elections.utah.gov/map/district-maps (#223 @nathankota on `2023/02/16`)

- Are clients querying this data with the WebAPI?
At this point, the answer should be no.  But, we need to verify that.

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 217

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **14** tasks | :no_entry: |
| @gregbunceon has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
/remind me to finish and close out this issue on 2/15/2023

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 217

| check | status |
| - | :-: |
| gregbunce has completed **15** out of **15** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
My validation tasks look good.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 217

| check | status |
| - | :-: |
| gregbunce has completed **15** out of **15** tasks | :+1: |
| steveoh has completed **6** out of **6** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.USCongressDistricts2002

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by steveoh** [comment]
Shouldn't there be a stewardship deprecation link and checkbox in this issue?

@gregbunce should we wait for @nathankota's thing before closing this?

**Comment by gregbunce** [comment]
yeah, i wasn't sure about that.  I am fuzzy on whether we 'shelved' and 'depreciated' them or just shelved them.  what do you think?

**Comment by gregbunce** [comment]
I think we can close it, unless i need to add deprecation links to the spreadsheet.  

at this point, the data has only one endpoint and it's stable.

**Comment by steveoh** [comment]
If there is no deprecation link I think it shows up in the SGID index? I think we decided to remove shelved but not static from the index?

**Comment by gregbunce** [comment]
good point.  yeah, the policy states, "Shelved datasets are not included in the SGID Open Data site."  

I'll add the links.  thanks for clarifying.

**Comment by gregbunce** [comment]
i'd say we can close this.  any objections?

**Comment by stdavis** [comment]
I think that we should leave at least one issue open with the http://elections.utah.gov/map/district-maps task.

**Comment by steveoh** [comment]
That would be #223 then right?
