### ISSUE TITLE
Remove cadastre.plss_point_agrc from SGID

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#218]
# Summary

- **Internal Dataset Name**: cadastre.PLSSPoint_AGRC
- **External Dataset Name**: cadastre.plss_point_agrc
- **ArcGIS Online Url**: https://opendata.gis.utah.gov/datasets/utah-plss-point-agrc and https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services/PLSSPoint_AGRC/FeatureServer/0

The plss_point_agrc dataset is a derivative of the plss points GCDB and was only used by the plss.utah.gov v2 app. The v3 app uses a different service and I don't believe we need this data set any longer.

## Migration Guide

Anyone currently using the plss_point_agrc dataset should migrate to the plss_point_gcdb dataset.

This dataset has been replaced by an arcgis online hosted feature service to serve the plss web app and will not be shared in the SGID.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title (@jacobdadams, completed: `2023/02/27`)
- [x] Remove all tags other than "Deprecated" (@jacobdadams, completed: `2022/00/00`)
- [x] Add note to ArcGIS Online description noting when layer will be deleted and any replacement layer (@jacobdadams, completed: `2023/02/27`)
- [x] Unshare item from Open Data (@jacobdadams, completed: `2023/02/27`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@steveoh, completed: `2023/01/30`)
- [x] Mark ArcGIS Online item as deprecated in preparation for future deletion (@jacobdadams, completed: `2023/03/01`)
  - [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@jacobdadams, completed: `2023/02/27`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@jacobdadams , completed: `2023/03/01`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@mheagin, completed: `2023/03/27`)
  - Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]
- [x] Remove ArcGIS Online item: (@gregbunce, completed: `2023/04/17`)
  - Manually delete the AGOL item
  -  -OR-
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.
  - Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).
- ~[ ] Remove Farm from AGOL connection (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh, completed: `2023/03/27`)
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@steveoh, completed: `2023/03/27`)
- [x] Update `SGID.META.AGOLItems` table (@steveoh, completed: `2022/00/00`)
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
- [x] Delete Google Drive data (@nathankota, completed: `2023/04/17` confirmed with @mheagin that there is no data to delete from G drive, although he may have a copy somewhere for posterity)
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2023/03/27`)
- [x] Remove data from forklift hashing and receiving (@steveoh, completed: `2023/03/27`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2023/03/27`)

### Shelve/Static

_Choose one based on situation._

- ~[ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2022/00/00`)~
- ~[ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2022/00/00`)~
- ~[ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2022/00/00`)~

_Add record to table._

- ~[ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2023/04/10`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2023/01/31`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2023/03/28`)

## Are there service dependencies

- Does an application depend on this data? Not anymore
- Are clients querying this data with the WebAPI? BigQuery shows no web api search usage

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
@jacobdadams and @gregbunce can I get a little help here please?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **0** out of **6** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| @jacobdadams has completed **6** out of **7** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by gregbunce** [comment]
let me know if you need assistance (@jacobdadams)

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by gregbunce** [comment]
@jacobdadams are you okay if i assign you the hard delete items?

**Comment by steveoh** [comment]
Since this is an application only layer, we should be safe to proceed with the hard delete.

**Comment by agrc-conductor** [comment]
## conductor results for cadastre.PLSSPoint_AGRC

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
> let me know if you need assistance (@jacobdadams)

> @jacobdadams are you okay if i assign you the hard delete items? i could assist as well. just let me know.

@gregbunce moving forward, let's shoot first and ask for forgiveness after. Otherwise we stall out.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| jacobdadams has completed **8** out of **8** tasks | :+1: |
| @steveoh has completed **10** out of **11** tasks | :no_entry: |
| mheagin has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 218

| check | status |
| - | :-: |
| jacobdadams has completed **8** out of **8** tasks | :+1: |
| steveoh has completed **11** out of **11** tasks | :+1: |
| mheagin has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
the agol item and service definttion file has been removed from arcgis online and has been backed up on the [google drive](https://drive.google.com/drive/u/1/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
