### ISSUE TITLE
Remove and shelve outdated Utah School Board District data from Open SGID (remain in AGOL as shelved)

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#219]
# Summary

- **Internal Dataset Name**: SGID.POLITICAL.UtahSchoolBoardDistricts2015
- **External Dataset Name**: [Utah School Board Districts 2015](https://opendata.gis.utah.gov/maps/utah-school-board-districts-2015)
- **ArcGIS Online Url**: [Utah School Board Districts 2015](https://utah.maps.arcgis.com/home/item.html?id=855c45da6d2e4386b06cfa27229f9685)

_A short summary of the situation._

This school board data/district is no longer active. As of Jan 2023, we are now using the latest districts and this one need to be removed from Open Data but made available in AGOL under the 'shelved' tag. Also, we should rename the item names in AGOL to be more descriptive and to better match our current naming convention for this layer. The remaining should be as follows:

- Utah School Board Districts 2012 to 2022

Also, see this [somewhat related porter issue](https://github.com/agrc/porter/issues/166) in which we are deprecating the School Board District named 2012.

## Migration Guide

This dataset has been replaced by [Utah School Board Districts 2022 to 2032](https://opendata.gis.utah.gov/maps/utah-school-board-districts-2022-to-2032).

At this point, we should be migrating applications and users away from this outdated layer and onto the latest data.

Let's do a soft delete before we do a hard delete (aka: remove from Open Data) because of the many systems and users that were/are potentially using this data.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Remove "Authoritative" tag from AGOL (@gregbunce, completed: `2023/01/27`)
- [x] Add "Shelved" tag to AGOL item (@gregbunce, completed: `2023/01/27`)
- [x] Update the ArcGIS Online description, informing users how this layer was used in the past (@gregbunce, completed: `2023/01/27`)
- [x] Unshare item from Open Data (@gregbunce, completed: `2023/01/27`)
- [x] Rename the AGOL layer if needed (@gregbunce, completed: `2023/01/27`)
- [x] Udate the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row with the agol item URL now that is shelved and note that it has been shelved in the description column (@gregbunce, completed: `2023/01/27`)
  - [x] Change `Authoritative` field to null in `SGID.META.AGOLItems`. Allow to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2023/01/27`)
    - [x] After one successful run of Auditor, remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@gregbunce, completed: `2023/02/10`)

### Shelve/Static

_Choose one based on situation._

- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (@gregbunce, completed: `2023/01/27`)

_Add record to table._

- [x] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (@gregbunce, completed: `2023/01/27`)

### Hard Delete (to happen after 2/15/2023)

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@gregbunce, completed: `2023/02/15`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2023/02/06`)
- [x] Remove row from `SGID.META.ChangeDetection` (@steveoh, completed: `2023/02/27`)
- [x] Remove data from forklift hashing and receiving (@steveoh, completed: `2023/02/27`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2023/02/27`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Verified that the data has been removed from Open SGID (@gregbunce on `2023/02/15`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2023/02/27`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2023/02/27`)

## Are there service dependencies

- Does an application depend on this data? Yes
- [x] Figure out what to do with http://elections.utah.gov/map/district-maps (#223 @nathankota on `2023/03/07`)

- Are clients querying this data with the WebAPI?
At this point, the answer should be no.  But, we need to verify that.

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
/remind me to finish shelving on 2/10/2023

**Comment by gregbunce** [comment]
@jacobdadams if you get a min, please look over my actions above (in the `soft delete` and `shelve/static` sections) to make sure I'm jiving with your processes.  i don't want to blow anything up (but, it could be fun!).

**Comment by jacobdadams** [comment]
Everything looks good, but the Auditor logs are telling me I missed a step with the soft delete- it doesn't like having the item id in both tables. @gregbunce, are you ok if I remove the itemid from the main meta table?

**Comment by gregbunce** [comment]
thanks for making sure all the wires are connected under the hood.  sure, you can remove the itemid from the meta table.  thanks.  this layer was my dry run (aka template) on how to proceed with the other political district layers so, should I remove the itemid when moving ahead with the other layers  (us cong; state senate; state house)?  The workflow is pretty much identical to this one.

**Comment by jacobdadams** [comment]
Great, I've got the itemid removed from the meta table and I'll do a manual run of auditor once I get the conda environment set up.

And yeah, I think this works great moving forward. Let's just make sure we remove the itemid from the meta table once we put it in the shelved table.

**Comment by gregbunce** [comment]
Great, that works.  also, i added you to the task of removing the row from the meta table.  I'm not sure the timing you'd like on that, so i figured i'll assign that one to you.  feel free to remove it whenever you see it necessary (my workflow does not require that row there).

**Comment by jacobdadams** [comment]
We may want to double check with @steveoh on that- I feel like that table gets used for the clouddb stuff that loads items to the Open SGID.

**Comment by steveoh** [comment]
I believe as soon as you remove that row from the meta table that the table will be removed from the OpenSGID. I don't see any issues with this as from the description that appears to be what we want to do. Since we are putting this on the shelf, we only need to make sure the agol item isn't removed and everything else should be removed.

**Comment by gregbunce** [comment]
bumping the removal date in Internal db to 2/15/2022

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 219

| check | status |
| - | :-: |
| @gregbunce has completed **10** out of **14** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 219

| check | status |
| - | :-: |
| gregbunce has completed **14** out of **14** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 219

| check | status |
| - | :-: |
| gregbunce has completed **14** out of **14** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
My validation tasks look good.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 219

| check | status |
| - | :-: |
| gregbunce has completed **14** out of **14** tasks | :+1: |
| steveoh has completed **6** out of **6** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for POLITICAL.UtahSchoolBoardDistricts2015

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: There are multiple items with this name on rows 517, 517. Please remove the duplicates. |
