### ISSUE TITLE
Remove SGID.WATER.RiparianAreas from SGID

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#232]
# Summary

- **Internal Dataset Name**: SGID.WATER.RiparianAreas
- **External Dataset Name**: opensgid.water.riparian_areas
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=74a6478eae424c17b96d1677ee1a4654

_The State Wetlands Coordinator has requested we remove the layer from the SGID as updates are pushed out by USFWS irregularly and they would like us to point people straight to the authoritative steward's resources._

## Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_

There are services and downloads available from the federal steward USFWS that will always be the most current:
https://www.fws.gov/node/264847
https://www.fws.gov/program/national-wetlands-inventory/web-mapping-services
https://fwspublicservices.wim.usgs.gov/wetlandsmapservice/rest/

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@rkelson, completed: `2023/03/23`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@rkelson, completed: `2023/03/23`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@rkelson, completed: `2023/03/27`)
- ~[x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@rkelson, completed: `2023/03/27`)~
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@rkelson, completed: `2023/03/27`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@rkelson, completed: `2023/03/28`)
    - [x] Unshare the item from its SGID group, which will remove it from Open Data (@jacobdadams, completed: `2023/03/28`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@rkelson, completed: `2023/04/18`)
  - Deprecated database layers can be backup up on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers]
- [x] Remove ArcGIS Online item: (@jacobdadams, completed: `2023/04/25`)
  - ~Manually delete the AGOL item~
  - -OR-
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  - ~Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  - Deprecated AGOL items can be backup on Google Drive > AGRC Share > Team Projects > SGID > [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS).
- ~[ ] Remove Farm from AGOL connection (@, completed: `2023/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson, completed: `2023/03/23`)
- ~[x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@rkelson, completed: `2023/03/27`)~
- [x] Update `SGID.META.AGOLItems` table (@rkelson, completed: `2023/03/28`)
  - ~cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  - ~set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
- ~[ ] Delete Google Drive data (name, completed: `2023/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2023/04/24`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2023/04/24`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2023/04/24`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2023/04/03`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2023/04/03`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2023/04/25`)

## Are there service dependencies

- [x] Are clients querying this data with the WebAPI?
- [x] Notify Josh Nielson (josh.nielson at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@eneemann on `2023/00/00`)
- [ ] Does any other application depend on this data?

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 232

| check | status |
| - | :-: |
| @rkelson has completed **3** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 232

| check | status |
| - | :-: |
| @rkelson has completed **7** out of **10** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for WATER.RiparianAreas

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 232

| check | status |
| - | :-: |
| rkelson has completed **9** out of **9** tasks | :+1: |
| @jacobdadams has completed **1** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| eneemann has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for WATER.RiparianAreas

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :no_entry: |
