### ISSUE TITLE
Issue with Porter-Removing data from SGID

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#233]
### Describe the problem you are having
In the `Removing data from the SGID` issue, Hard Delete section, the folder path for the Google Drive backups of the data being removed should be changed to :
AGRC Projects > SGID > deprecated layers > internal_db_sgid_layers
We could also add a link to the folder:
https://drive.google.com/drive/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq

#### Should a new checkbox be added
I would suggest this be an additional checkbox

**Comment by steveoh** [comment]
Sounds good to me. Toss it in a pull request!

**Comment by rkelson** [comment]
this is complete
