### ISSUE TITLE
Deprecate Roadkill Desktop Application

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#235]
# Summary

- **Application Name**: Roadkill Desktop
- **Application Urls**
  - Staging: http://test.mapserv.utah.gov/wvc/mobile
  - Production: https://mapserv.utah.gov/wvc/desktop

_A short summary of the situation._

DWR has decided to deprecate this application in favor of their AGOL stuff.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

~- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2023/00/00`)~
- [x] Remove application-specific Databases (@MichaelAGRC, completed: `2023/04/12`)
	- `roadkill.agrc.utah.gov` (DNS record removal via INC1812136)
	- Not sure if there is a test version still around??
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (@nathankota, completed: `2023/04/11` NOTE: keeping due to ongoing mobile app project and maintenance)
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (@nathankota, completed: `2023/04/11` NOTE: updated the existing [Roadkill record](https://utah.service-now.com/nav_to.do?uri=%2Fcmdb_ci_business_app.do%3Fsys_id%3D66544a431be115d049656358b04bcb24%26sysparm_view%3Dbusiness_applications%26sysparm_record_target%3Dcmdb_ci_business_app%26sysparm_record_row%3D39%26sysparm_record_rows%3D65%26sysparm_record_list%3DORDERBYzztextsearchyy) for the mobile app)

### Is there a website?

~- [ ] Remove DNS entry (name, completed: `2023/00/00`)~
- [x] Archive source code repository (@stdavis, completed: `2023/04/11`)
	- https://github.com/agrc/roadkill-web
- [x] Remove app-specific quad word from Discover system (@stdavis, completed: `2023/04/11`)
	- `alfred-plaster-crystal-dexter` is being used for other apps as well ([mapserv.utah.gov](http://mapserv.utah.gov/), [raster.utah.gov](http://raster.utah.gov/), [parcels.utah.gov](http://parcels.utah.gov/), [plss.utah.gov](http://plss.utah.gov/), [plss.dev.utah.gov](http://plss.dev.utah.gov/), [ut-dts-agrc-plss-prod.web.app](http://ut-dts-agrc-plss-prod.web.app/))
	- ~`crystal-connect-remote-episode`~

_Choose one._

- [x] Remove from the web server (@stdavis, completed: `2023/04/11`)
~- [ ] Replace app with a static page with information (name, completed: `2023/00/00`)~
- [x] Redirect to their [experience builder app](https://experience.arcgis.com/experience/9c34ea0968e940ac8b3fdb2d61a19280/page/Home/?views=View-16%2CTrack-Route%2CRoute-tracking%2CInstall) (@stdavis, completed: `2023/04/11`)

### Is there a map service?

~- [ ] Stop (@stdavis, completed: `2023/00/00`)~
- [x] Delete (@stdavis, completed: `2023/04/11`)
- [x] Unregister Data Store in ArcGIS Server (@stdavis, completed: `2023/04/11`)

### Is there a forklift pallet?

- [x] Remove repo (@stdavis, completed: `2023/04/11`)
  - don't forget to remove the pallet from the current packing slip in receiving!
- [x] Remove stale data from forklift hashing and receiving (@stdavis, completed: `2023/04/11`)
	- there was none
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2023/04/11`)
	- there was none

### Are there service dependencies?

~- [ ] Validate that the web api does not query it (name, completed: `2023/00/00`)~
~- [ ] Validate that AGRC or applications widgets do not reference it (name, completed: `2023/00/00`)~

## Notification

~- [ ] Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

~- [ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
~- [ ] Cadastre Team (@rkelson)~

**Comment by stdavis** [comment]
@MichaelAGRC We just got back confirmation from the client. We are good to blow away this database when you get a minute.

**Comment by steveoh** [comment]
If `roadkill.agrc.utah.gov` isn't being used anywhere we should release it and @nathankota can update the books.

**Comment by stdavis** [comment]
It's not being used. I assumed that would be part of the DB delete. @nathankota Can you release it?

**Comment by steveoh** [comment]
> It's not being used. I assumed that would be part of the DB delete. @nathankota Can you release it?

I don't think the db folks are aware of the networking info.

**Comment by nathankota** [comment]
> > It's not being used. I assumed that would be part of the DB delete. @nathankota Can you release it?
> 
> I don't think the db folks are aware of the networking info.

As in, [this info](https://trello.com/c/1dBtUrpq)?

**Comment by nathankota** [comment]
dns record removal via INC1812136

**Comment by MichaelAGRC** [comment]
Dbase has been informed and both DEV and PROD databases are offline.

**Comment by steveoh** [comment]
> Dbase has been informed and both DEV and PROD databases are offline.

Will you edit the issue to add the date completed michael?

This looks done though. 🏁 🐎🐎🐎

**Comment by stdavis** [comment]
It looks like I missed the cloud project for this.
- [ ] delete cloud projects: `ut-dts-agrc-roadkill-web-dev` & `ut-dts-agrc-roadkill-web-prod`
- [ ] clean up terraform project
