### ISSUE TITLE
Add Tax Areas 2022 from Utah Tax Commission

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#239]
# Summary

- **Proposed Readable Name**: Utah Tax Areas 2022 
- **Proposed Internal Dataset Name**: TaxAreas2022
- **Proposed External Dataset Name**: tax_areas_2022 
- **Proposed Data Category**: Economy
- **Data Description**: Centrally assessed property tax analysis areas.
- **Source Agency/Entity**: Utah Tax Commission
- **Contact**: Nick Kenczka
- **Update Frequency**: Yearly

Yearly tax area update from the Utah Tax Commission

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@ZachBeck on `2022/06/06`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@ZachBeck on `2022/06/06`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@ZachBeck on `2022/06/06`)

## Where is the data source

_Choose one._

- [x] Internal SGID
~- [ ] Farm from AGOL ([agol item url](??))~

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@ZachBeck, completed: `2022/06/06`)
~- [ ] Configure forklift for Farm from AGOL (name, completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck , completed: `2022/06/12`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2022/06/12`)
- [x] Complete a `SGID.META.AGOLItems` record (@ZachBeck, completed: `2022/06/08`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (~@steveoh~ @stdavis on `2022/06/19`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/06/19`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2023/06/09`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@ZachBeck on `2022/06/12`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck on `2022/06/12`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (~@steveoh~ @stdavis on `2022/06/19`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

~- [ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
~- [ ] Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 239

| check | status |
| - | :-: |
| @ZachBeck has completed **4** out of **9** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Economy.TaxAreas2022

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |

**Comment by stdavis** [comment]
@ZachBeck I believe that I finished up the last few tasks for this today. Want to take one more look and close it out?
