### ISSUE TITLE
Duplicate AGOL UTA layers

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#24]
# Summary

The following layer have been marked deprecated for some time.

- [UTA Bus Routes Wasatch Front](http://utah.maps.arcgis.com/home/item.html?id=dff015071aca4653af7838479caca356) (dff015071aca4653af7838479caca356) and 
- [UTA Bus Stops Wasatch Front](http://utah.maps.arcgis.com/home/item.html?id=b3b210a4fe864ad7afb34e74ba554cbd) (b3b210a4fe864ad7afb34e74ba554cbd)

Two replacement layers were uploaded near the end of 2019 and are the layers referenced in the SGID.META.AGOLItems table. These older layers are still getting some use, but should be removed.

## Suggested Action

- ~[ ] Move items to shelved folder/group for x months (1? 3? 6?)~
- [x] Update description with upcoming deletion date (@ZachBeck) 
- [x] Delete completely 

# Triage

- [x] Data Team Triage (data team )
- [x] Dev Team Triage (@steveoh)
- ~[ ] Cadastre Team Triage~

# Remove data from the following areas

- [x] ArcGIS Online (@ZachBeck )
- ~[ ] Internal SGID (assigned to)~
- ~[ ] SGID10 (assigned to)~
- ~[ ] Open SGID (assigned to)~
- ~[ ] Google Drive (assigned to)~
~- [ ] Open data (assigned to)~
~- Mapserv (assigned to)~

# Copy data to the following areas

- ~[ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
- ~[ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
- ~[ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- ~[ ] gis.utah.gov data pages (assigned to)~
- ~[ ] Stewardship doc and sgid-index (assigned to)~
- ~[ ] `SGID.META.AGOLItems` (assigned to)~
- ~[ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
- ~[ ] `SGID.META.ChangeDetection` (assigned to)~

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
or
- ~[ ] Replace app with a static page with information (assigned to)~
or
- ~[ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~

# Is there a forklift pallet?

- ~[ ] Remove repo (assigned to)~
- ~[ ] Remove stale data from forklift hashing and receiving (assigned to)~

# Are there service dependencies?

- ~[ ] Validate that the web api does not query it (assigned to)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

- [ ] Blog post (assigned to)
- [ ] Twitter (@steveoh)
  - [x] Intent
  - [ ] Completed

**Comment by steveoh** [comment]
dev team did a first pass at this and removed a bunch of checks. Since the data is only in arcgis online and open data a lot do not apply. I verified that all of the automated areas are using the proper item id.

**Comment by steveoh** [comment]
I like the 1 month timeline with a description in the item page.

**Comment by steveoh** [comment]
What is the status of this?

**Comment by ZachBeck** [comment]
UTA Bus Stops Wasatch Front and UTA Bus Routes Wasatch Front have both been deprecated and in my opinion can be deleted. UTA updates this data every 6 months, I don't think it's worth shelving.

**Comment by nathankota** [comment]
- Data Team triage complete, and issue edited to reflect decision to delete

- Description updated in AGOL items for deletion on 7/16

- Calendar reminder created to complete deletion on 7/16

**Comment by steveoh** [comment]
Should we keep this open until 7/16?

**Comment by steveoh** [comment]
/remind me to close this issue on July 16

**Comment by ZachBeck** [comment]
Deleted from AGOL
