### ISSUE TITLE
Deprecate ERAP app/skid

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#253]
# Summary

- **Application Name**: ERAP
- **Application Urls**: https://experience.arcgis.com/experience/285c8572fddd41a7b2221e731bf23ace
  - Staging: ut-dts-agrc-erap-dev
  - Production: ut-dts-agrc-erap-prod

The ERAP/Rent Relief program has ended and DWS does not need this map online anymore.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2023/00/00`)~
- ~[ ] Remove application-specific Databases (name, completed: `2023/00/00`)~
- ~[ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2023/00/00`)~
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (@nathankota , completed: `2023/07/10`)

### Is there a website?

- ~[ ] Remove DNS entry (name, completed: `2023/00/00`)~
- [x] Archive source code repository (@jacobdadams , completed: `2023/07/12`)
- ~[ ] Remove app-specific quad word from Discover system (name, completed: `2023/00/00`)~
- [x] Remove cloud project (@steveoh, completed: `2023/07/12`)
- [x] Remove terraform infrastructure (@jacobdadams , completed: `2023/07/12`)

_Choose one._

- ~[ ] Remove from the web server (name, completed: `2023/00/00`)~
- ~[ ] Replace app with a static page with information (name, completed: `2023/00/00`)~
- ~[ ] Redirect somewhere else (name, completed: `2023/00/00`)~
- [x] Deprecate and unshare web app and map (@jacobdadams , completed: `2023/07/12`)

### Is there a map service?

- ~[ ] Stop (name, completed: `2023/00/00`)~
- ~[ ] Delete (name, completed: `2023/00/00`)~
- ~[ ] Unregister Data Store in ArcGIS Server (name, completed: `2023/00/00`)~
- [x] Unshare and deprecate feature layer in AGOL (@jacobdadams, completed: `2023/07/12`)

### SFTP

- [x] Contact DWS to stop automated csv dump to our SFTP (emailed Jennifer Edwards and Mike Murdock from DWS about who on their team can help, since Rick Kowalczik's email is no longer active, and he helped set it up, @jacobdadams or @nathankota , completed: `2023/07/10`)
- [x] Contact DTS to remove `dws-erap` share (share and user removed via INC1856498, @nathankota, completed: `2023/07/11`)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- ~[ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- ~[ ] Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 253

| check | status |
| - | :-: |
| @nathankota has completed **0** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **5** tasks | :no_entry: |
| steveoh has completed **1** out of **1** tasks | :+1: |

**Comment by jacobdadams** [comment]
Looks like everything's done now, closing this issue.
