### ISSUE TITLE
Add SGID.CADASTRE.Parcels_Piute_LIR

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#259]
# Summary

- **Proposed Readable Name**: Utah Piute County Parcels LIR 
- **Internal Dataset Name**: SGID.CADASTRE.Parcels_Piute_LIR
- **Proposed External Dataset Name**: piute_county_parcels_lir
- **Proposed Data Category**: CADASTRE
- **Data Description**: county LIR parcel data
- **Source Agency/Entity**: County & St. Auditor
- **Contact**: rkelson@utah.gov
- **Update Frequency**: Annual

_Introduce your data, where it comes from, why it is being added etc._
This is simply an additional LIR parcel dataset

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [x] Sweeper checks have run and passed (@stdavis  on `2023/09/22`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@rkelson on `2023/09/21`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@rkelson on `2023/09/21`)

## Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@rkelson , completed: `2023/09/21`)
~- [ ] Configure forklift for Farm from AGOL (@stdavis , completed: `2022/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson , completed: `2022/00/00` https://github.com/agrc/gis.utah.gov/pull/2370)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@rkelson , completed: `2023/09/25`)
- [x] Complete a `SGID.META.AGOLItems` record (@rkelson , completed: `2022/09/27`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2022/00/00`)~
- [x] Define a record set with archives It is 30660 (@brigsz, completed: `2023/10/12`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2023/10/02`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/10/10`)
	- https://utah.maps.arcgis.com/home/item.html?id=d75188a6edcc4af2a128001c89522b32
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2023/10/04`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@rkelson  on `2023/10/04`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson on `2023/10/04`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/10/12`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
Sweeper results:
![image](https://github.com/agrc/porter/assets/1326248/2a657806-798d-4247-9ed2-ca8936f3e649)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 259

| check | status |
| - | :-: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **6** out of **9** tasks | :no_entry: |
| @brigsz has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for CADASTRE.Parcels_Piute_LIR

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 259

| check | status |
| - | :-: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| rkelson has completed **9** out of **9** tasks | :+1: |
| @brigsz has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
These descriptions are identical but they are two different services. I approved it but maybe we could differentiate the two datasets and expand what LIR is?

<img width="1286" alt="image" src="https://github.com/agrc/porter/assets/325813/affdb11e-1223-4d9f-8313-25d0f3e5725b">

**Comment by brigsz** [comment]
I have requested a chat with Archives to create a record series for LIR as I did not see it in the list

**Comment by brigsz** [comment]
okay, an update, I have filled out the form to create the record series.  When it is approved and implemented I will respond here.

**Comment by brigsz** [comment]
okay, did last part, the series number is 30660 that is for all LIR records

**Comment by brigsz** [comment]
Thats all folks
