### ISSUE TITLE
Remove StateCampuses map service from mapserv.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#273]
# Summary

- **Name**: https://mapserv.utah.gov/arcgis/rest/services/StateCampuses/Blank/MapServer

_A short summary of the situation._

We don't know what this service is used for and don't believe that it is relevant. Perhaps @steveoh could give a bit more background/memories.

I checked the server log stats on both machines and there was no traffic for this service over the past 7 days.

## Action items

1. _Assign a person who should complete the task._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Shut Off Service (@stdavis, completed: `2023/10/23`)
- [x] Delete Service (two weeks after shut off) (@steveoh, completed: `2023/11/06`)
- [x] Remove source data (@steveoh, completed: `2023/11/06`)
	- "there's probably a static statecampus.gdb in forklift and then those are probably in the map data folder on the servers."

## Notification

// skipping as it was for a custom app
- ~[ ] Twitter~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
/remind me to delete this service in two weeks

**Comment by steveoh** [comment]
That service was an empty map, with a dynamic workspace registered to it, that allowed  layers to be dynamically added to it from a geodatabase when the client turned them on. I want to say there were 50+ layers in the workspace. I wonder if @brigsz has a data sharing agreement or what if anything could be done with that data. Should it be kept or deleted?

**Comment by brigsz** [comment]
gsutherland@utah.gov (George) took over for mikesmith@utah.gov  That is where it totally went silent.  I do not have any agreements.  I am going to reach out to George and tell him we are deleting the data and see if he screams

**Comment by brigsz** [comment]
I have reviewed some of the correspondence on this one.  @steveoh Can you shut it down today and delete the data on 11/6/2023?  George who took over the project for DFCM pleaded insanity and said he was not involved back a few years ago.  Not sure how something just gets totally forgotten about like that.

**Comment by steveoh** [comment]
That is the plan @brigsz

**Comment by stdavis** [comment]
Do I need to add a step for some sort of data deletion?

**Comment by steveoh** [comment]
yeah there's probably a static statecampus.gdb in forklift and then those are probably in the map data folder on the servers.

**Comment by steveoh** [comment]
closing as complete
