### ISSUE TITLE
Deprecate Mapserv (app2) Machine

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#276]
# Summary

- **Name**:

We think that this machine may no longer be needed given the fact that many of the services have been migrated to AGOL or deprecated. We plan to shut it down and see how it goes.

## Action items

1. _Assign a person who should complete the task._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Shut down ArcGIS Server (@stdavis, completed: `2023/10/25`)
- [x] Remove server from forklift config (@stdavis, completed: `2023/10/25`)
	- Don't forget to refresh the data on this server if we turn it back on.
- [x] Shut down machine (@stdavis, completed: `2023/11/08`) 
- [x] Request removal of app2 from the gis app pool in NSX load balancer (@steveoh, completed: `2023/11/07`)
   - INC1916738 
- [x] Stop paying maintenance and do not renew the associated ArcGIS Server Standard License (@nathankota , completed: `2023/11/07`, reminder set for May 1, 2024 to not renew the maintenance on one standard license)
- [x] Submit ticket for decommission of machine (@nathankota, completed: `2023/11/27`)
	- Wait a week or so after the machine has been shut down to complete this task.
	- [RITM0258986](https://utah.service-now.com/sc_req_item.do?sys_id=f11c22c597327d50f0323aa3f153af15&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog)
- [x] undo data.mapserv.utah.gov stuff since it's no longer needed
	- [x] update DNS in print proxy (@steveoh, completed: `2023/11/08`)
		- https://github.com/agrc/serverless-print-proxy/pull/155
	- [x] Release data.mapserv.utah.gov DNS (@nathankota, completed: `2023/11/13`, via [REQ0182457](https://utah.service-now.com/sc_request.do?sys_id=1875c6e4976a7510f0323aa3f153af1f&sysparm_record_target=sc_request&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog))
	- [x] Remove data.mapserv.utah.gov load balancer and VIP (@steveoh, completed: `2023/11/09`) INC1917808

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
/remind me to shut down this machine in two weeks

**Comment by steveoh** [comment]
/remind @nathankota to initiate the decommission of the machine in 13 days

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 276

| check | status |
| - | :-: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| @nathankota has completed **2** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by nathankota** [comment]
Server decommission request submitted. Task checked and dated above.

**Comment by steveoh** [comment]
greg hasn't reviewed and all the tasks are complete.
