### ISSUE TITLE
Deprecate UGRC's Fire Business System Integration

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#278]
# Summary

- **Application Name**: Fire Business System Integration
- **Application Urls**
  - Staging: N/A
  - Production: https://github.com/agrc/fire-business

The primary uses of the (A)UGRC-built tools/integrations for the DNR/FFSL Fire Business System are no longer required, as their functionality has been replaced by FFSL contractors responsible for supporting the system (Gold Systems and/or Timmons Group).

## Action items

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@steveoh, completed: `2023/11/06`)
- [x] Remove application-specific Databases( @steveoh, completed: `2023/11/06`)
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (@nathankota , completed: `2023/11/06`)
  - Deleted FFSL folder containing AT and Prod database connection information 
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (@nathankota , completed: `2023/11/06`)
- [x] Remove Google Analytics property (@steveoh, completed: `2023/11/06`)

### Is there a website?

- Remove DNS entry (name, completed: `2023/00/00`)
- [x] Archive source code repository (@steveoh, completed: `2023/11/06`)
- [x] Remove app-specific quad word from Discover system (@steveoh, completed: `2023/11/06`)
- [x] Remove cloud project (@steveoh, completed: `2023/11/06`)
- [x] Remove terraform infrastructure (@steveoh, completed: `2023/11/06`)

_Choose one._

- ~Remove from the web server (name, completed: `2023/00/00`)~
- ~Replace app with a static page with information (name, completed: `2023/00/00`)~
- ~Redirect somewhere else (name, completed: `2023/00/00`)~

### Is there a map service?

- ~[ ] Stop (name, completed: `2023/00/00`)~
- ~[ ] Delete (name, completed: `2023/00/00`)~
- ~[ ] Unregister Data Store in ArcGIS Server (name, completed: `2023/00/00`)~

ffsl arcgis server was shut down a while ago

### Is there a forklift pallet?

- [x] Remove repo (@steveoh, completed: `2023/11/06`)
  - don't forget to remove the pallet from the current packing slip in receiving!
- [x] Remove stale data from forklift hashing and receiving (@steveoh, completed: `2023/11/06`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@steveoh, completed: `2023/11/06`)

### Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh, completed: `2023/11/06`)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh, completed: `2023/11/06`)

## Notification

- ~Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- ~Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- ~Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 278

| check | status |
| - | :-: |
| @nathankota has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |

**Comment by steveoh** [comment]
closing as complete

**Comment by nathankota** [comment]
came across another record for this in ServiceNow Business Applications and deleted it today

![image](https://github.com/agrc/porter/assets/15659642/6a9a235d-22c8-4f4e-ad83-b61acfc08775)

**Comment by steveoh** [comment]
Strange. How?

**Comment by nathankota** [comment]
it may be related to https://github.com/agrc/planning-queue/issues/331
