### ISSUE TITLE
Remove Utah WRI Focus Areas from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#280]
# Summary

- **Internal Dataset Name**: n/a
- **External Dataset Name**: Utah WRI Focus Areas
- **ArcGIS Online Url**: https://opendata.gis.utah.gov/datasets/utahDNR::utah-wri-focus-areas/about

DWR is no longer using this layer. We are removing it from WRI and need to have it removed from our OpenData portal. It does not exist in Internal, OpenSGID, or the SGID Index.

## Migration Guide

WRI project ranking will no longer include focus areas. There is no replacement for this layer. The data are still available from DWR via https://www.arcgis.com/home/item.html?id=661d37c39929419fbb8e529c1725d19d but we are unsure about the future of the service.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Unshare the item from its SGID group, which will remove it from Open Data (@MichaelAGRC, completed: `2023/11/29`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Ask DNR to unshare the item with our org (@nathankota, completed: `2023/12/18`, Alison and Tyler S. are on standby for this)
- [x] Does any other application depend on this data? (@nathankota I checked with WRI and DWR GIS and they're not aware of any other apps using the SGID data set, and neither am I)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by nathankota** [comment]
/remind @nathankota to have DWR unshare Focus Areas with the SGID Bioscience group in their AGOL.

**Comment by nathankota** [comment]
/remind me to have DWR unshare Focus Areas with the SGID Bioscience group in their AGOL.

**Comment by nathankota** [comment]
/remind me to have DWR unshare Focus Areas with the SGID Bioscience group in their AGOL on December 13, 2023 (third time's a charm)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 280

| check | status |
| - | :-: |
| MichaelAGRC has completed **1** out of **1** tasks | :+1: |
| @nathankota has completed **1** out of **2** tasks | :no_entry: |
| steveoh has completed **2** out of **2** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by nathankota** [comment]
all tasks completed
