### ISSUE TITLE
Deprecate SBI Locate app

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#283]
# Summary

- **Application Name**: SBI Locate
- **Application Urls**
  - Staging: sbi.dev.utah.gov
  - Production: sbilocate.ugrc.utah.gov

_A short summary of the situation._
SBI Locate was using the to-be-retired Esri JS 3x API. An [LE Locate Experience Builder application](https://experience.arcgis.com/experience/c1b5822d55694628a5577bc218c7bee2/) has been built as a replacement and has been provided to the DHHS team that utilizes the app.
 

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (no pages found, but worth a second look) (@steveoh, completed: `2023/12/13`)
- [x] Remove application-specific Databases (@steveoh, completed: `2023/12/13`)
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) No folder found (@nathankota , completed: `2023/12/13`)
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) - Changed record to "DHHS Law Enforcement Viewer" (@nathankota , completed: `2023/12/13`)
- [x] Remove Google Analytics property (@steveoh, completed: `2023/12/13`)

### Is there a website?

- [x] [RITM0260789](https://utah.service-now.com/sc_req_item.do?sys_id=aebe99da9783b954f0323aa3f153afcf&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog) Remove DNS entry - NetworkOps says there is only a record for sbi.dev.utah.gov (@nathankota, completed: `2023/12/13`)
  - [x] Remove from [DNS sheet](https://docs.google.com/spreadsheets/d/1CRY3p9Uc_vysWsEmyLFM9HTFisw_ICkGBnnuenQP4aM/edit#gid=1903062282) once RITM is complete (@nathankota, completed: `2023/12/18`)
- [x] Archive source code repository (@steveoh, completed: `2023/12/13`)
- [x] Remove app-specific quad word from Discover system (@steveoh, completed: `2023/12/13`)
- [x] Remove app-specific api key from UGRC API (@steveoh, completed: `2023/12/13`)
- [x] Remove cloud project (@steveoh, completed: `2023/12/13`)
  - ut-dts-agrc-sbi-dev
  - ut-dts-agrc-sbi-prod
- [x] Remove terraform infrastructure (@steveoh, completed: `2023/12/13`)

_Choose one._

- ~[ ] Remove from the web server (@steveoh, completed: `2023/00/00`)~
- ~Replace app with a static page with information (name, completed: `2023/00/00`)~
- Attempted, but not possible ~Redirect somewhere else (name, completed: `2023/00/00`)~

### Is there a map service or AGOL item?

- ~[ ] Stop (@steveoh , completed: `2023/00/00`)~
- [x] Delete (c3c3b5c993324c3fb69bb3837a7b784d) (@steveoh, completed: `2023/12/13`)
- ~[ ] Unregister Data Store in ArcGIS Server (@steveoh , completed: `2023/00/00`)~

### Is there a forklift pallet?

- ~[ ] Remove repo (name , completed: `2023/00/00`)~
  - don't forget to remove the pallet from the current packing slip in receiving!
- ~[ ] Remove stale data from forklift hashing and receiving (name, completed: `2023/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2023/00/00`)~

### Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh, completed: `2023/00/00`)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh, completed: `2023/00/00`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [ ] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by steveoh** [comment]
i'm done with all i can do. close this up when you're ready

**Comment by nathankota** [comment]
all tasks completed
