### ISSUE TITLE
Remove SGID.TRANSPORTATION.UDOTTenthMileRefPoints from SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#285]
# Summary

- **Internal Dataset Name**: SGID.TRANSPORTATION.UDOTTenthMileRefPoints
- **External Dataset Name**: Utah UDOT Tenth Mile Ref Points
- **ArcGIS Online Url**: https://www.arcgis.com/home/item.html?id=2b9972e0879248c2978da1c91d77ab4f

_A short summary of the situation._
This layer has been deprecated by UDOT and has been replaced by the following service: [Mile Point Linear Measure (LM)](https://www.arcgis.com/home/item.html?id=768b285ed14e40e5853f45963f2d137a#). UGRC's [Transportation page](https://gis.utah.gov/data/transportation/roads-system/#MilepostPoints) points users to this new service (in the Related Resources section)

## Migration Guide
Users should be using UDOT's [Mile Point Linear Measure (LM)](https://www.arcgis.com/home/item.html?id=768b285ed14e40e5853f45963f2d137a#) as a replacement.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@DenisePeterson, completed: `2024/01/03`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@DenisePeterson, completed: `2024/01/03`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@DenisePeterson, completed: `2024/01/03`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@gregbunce, completed: `2023/12/22`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2023/12/22`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@DenisePeterson, completed: `2024/01/03`)
    - [x] Unshare the item from its SGID group, which will remove it from Open Data (@DenisePeterson, completed: `2024/01/03`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@DenisePeterson, completed: `2024/01/18`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@DenisePeterson, completed: `2024/01/18`).
- [x] Remove ArcGIS Online item: (@DenisePeterson, completed: `2024/01/18`)
  - Manually delete the AGOL item
  - -OR-
  ~- Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - -OR-
  ~- Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  ~- Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).~
~- [ ] Remove Farm from AGOL connection (name, completed: `2023/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2023/12/21`)
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@gregbunce, completed: `2023/12/22`)
- [x] Update `SGID.META.AGOLItems` table (@DenisePeterson, completed: `2024/01/18`)
  ~- cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  ~- set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  ~- set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
~- [ ] Delete Google Drive data (name, completed: `2023/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2023/00/00`)
	- This was already done.
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/01/25`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/01/25`)

### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2023/00/00`)~
~- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2023/00/00`)~
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2023/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2023/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2024/01/22`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/02/05`)
- [x] Auditor sets appropriate `Deprecated` information (@jacobdadams on `2023/12/23`)

## Are there service dependencies

- [ ] Are clients querying this data with the WebAPI?
- [x] Notify Don Jackson (at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2023/12/22`)
- [ ] Does any other application depend on this data?

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| @DenisePeterson has completed **0** out of **9** tasks | :no_entry: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| @DenisePeterson has completed **0** out of **9** tasks | :no_entry: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| @steveoh has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| @DenisePeterson has completed **5** out of **9** tasks | :no_entry: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| @DenisePeterson has completed **5** out of **9** tasks | :no_entry: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| DenisePeterson has completed **9** out of **9** tasks | :+1: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.UDOTTenthMileRefPoints

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| DenisePeterson has completed **9** out of **9** tasks | :+1: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.UDOTTenthMileRefPoints

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| DenisePeterson has completed **9** out of **9** tasks | :+1: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **3** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 285

| check | status |
| - | :-: |
| DenisePeterson has completed **9** out of **9** tasks | :+1: |
| gregbunce has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.UDOTTenthMileRefPoints

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |
