### ISSUE TITLE
Remove Mike Heagin from UGRC accounts (after Dec 29, 2023)

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#287]
# Remove Mike from UGRC accounts

- **Name**: Mike Heagin

Mike is retiring on December 29, 2023 so we'll need to remove him from all the appropriate places and locations. 

## Action items

1. _Assign a person who should complete the task._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

I used our [stackoverflow team list ](https://stackoverflowteams.com/c/ugrc/questions/11)to get us going

- [x] Bitwarden account (@steveoh, completed: `2024/01/02`)
- [x] Google Analytics user (@steveoh, completed: `2024/01/02`)
- [x] Remove Mike's name from https://turngps.utah.gov @seanfernandez , completed: '2024/00/00')
- [x] github.com organization (@steveoh, completed: `2024/01/02`)
- [x] Facebook settings (@steveoh, completed: `2024/01/02`)
- [x] Twitter account settings (@steveoh, completed: `2024/01/02`)
- [x] ArcGIS Online user (@MichaelAGRC, completed: `2024/01/02`)
- [x] Discover Server user (@jacobdadams or @rkelson, completed: `2022/00/00`)~
- [x] License Manager user (@MichaelAGRC, completed: `2024/01/02`)
- [x] Admin app accounts (permission proxy) (@stdavis, completed: `2024/01/08`)
- [x] [Trello](https://trello.com/w/utahgeospatialresourcecenter/members) (@nathankota, completed: `2024/01/02`)
- [x] Drive shares (@brigsz, completed: `2024/01/22`)
- [x] Slack (@steveoh, completed: `2024/01/02`)
- [x] A deletion, maybe, more learning to figure it out
- [x] Google team drive (@brigsz, completed: `2024/01/16`)
- [x] Agrcgroup google group (@brigsz, completed: `2024/01/16`)
- [x] Pluralsight [form](https://goo.gl/forms/0yKGpeWgm1ZxW0jp2) (@steveoh, completed: `2024/01/08`)
- [x] UMD Access to databases (@MichaelAGRC, completed: `2024/01/02`)
- [x] Zabbix monitoring groups (@steveoh, completed: `2024/01/08`)
- [x] GCP projects/service accounts (@steveoh, completed: `2024/01/02`)
- [x] Service Now Group removal (via [INC1940690](https://utah.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=04d8dc7c976bf1d0f0323aa3f153afab%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) @nathankota, completed: `2024/01/02`)
- [x] GIS website data.yml (@gregbunce, completed: `2024/01/02`)
- [x] Website contact page (@steveoh, completed: `2024/01/02`)
- [x] Forklift emails (@stdavis, completed: `2024/01/08`)
- [x] Citrix access (@gregbunce, completed: `2024/01/02`)
- [x] UGRC API keys (@steveoh, completed: `2024/01/02`)
- [x] Sendgrid API keys (@steveoh, completed: `2024/01/02`)
- [x] Stackoverflow teams account (@steveoh, completed: `2024/01/02`)
- [x] Update stewardship sheet and reassign Mike's data assignments (@gregbunce, completed: `2024/01/05`)
- [x] Change recipient of ugrc@utah.gov emails from Mike to Michael (@nathankota, completed: `2024/01/17`, via [RITM0263298](https://utah.service-now.com/now/nav/ui/classic/params/target/sc_req_item.do%3Fsys_id%3D76e2b1a997fbf190f0323aa3f153af7e%26sysparm_stack%3Dsc_req_item_list.do%3Fsysparm_query%3Dactive%3Dtrue)

1. _Assign yourself or someone to check the item._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by mheagin** [comment]
Offical last day in 29th Dec. so please don't disconnect anything I will need to finish my career before then.  Thanks

**Comment by gregbunce** [comment]
Please review the assignments and update names as appropriate.  
I kind of broke the rules and started assigning folks just to get the ball rolling.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 287

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **8** tasks | :no_entry: |
| @MichaelAGRC has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **2** tasks | :no_entry: |
| @nathankota has completed **0** out of **2** tasks | :no_entry: |
| @brigsz has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **1** out of **3** tasks | :no_entry: |

**Comment by steveoh** [comment]
@gregbunce and @seanfernandez should we remove these assignments or update them with another contact for the gis website?

<img width="240" alt="image" src="https://github.com/agrc/porter/assets/325813/8ea0562d-66ca-4a08-ae82-abb53ca73342">

**Comment by jacobdadams** [comment]
Doesn't look like he had a unique Discover user, crossed out that line.

**Comment by gregbunce** [comment]
> @gregbunce and @seanfernandez should we remove these assignments or update them with another contact for the gis website?
> 
> 
> 
> <img width="240" alt="image" src="https://github.com/agrc/porter/assets/325813/8ea0562d-66ca-4a08-ae82-abb53ca73342">
> 
> 

Yup, that would be Denise. I can take care of it.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 287

| check | status |
| - | :-: |
| @steveoh has completed **12** out of **14** tasks | :no_entry: |
| MichaelAGRC has completed **3** out of **3** tasks | :+1: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| nathankota has completed **2** out of **2** tasks | :+1: |
| @brigsz has completed **0** out of **3** tasks | :no_entry: |
| gregbunce has completed **4** out of **4** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 287

| check | status |
| - | :-: |
| steveoh has completed **14** out of **14** tasks | :+1: |
| MichaelAGRC has completed **3** out of **3** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| nathankota has completed **2** out of **2** tasks | :+1: |
| @brigsz has completed **0** out of **3** tasks | :no_entry: |
| gregbunce has completed **4** out of **4** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 287

| check | status |
| - | :-: |
| steveoh has completed **14** out of **14** tasks | :+1: |
| @seanfernandez has completed **0** out of **1** tasks | :no_entry: |
| MichaelAGRC has completed **3** out of **3** tasks | :+1: |
| rkelson has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| nathankota has completed **2** out of **2** tasks | :+1: |
| @brigsz has completed **2** out of **3** tasks | :no_entry: |
| gregbunce has completed **4** out of **4** tasks | :+1: |

**Comment by brigsz** [comment]
I far as I can tell, all boxes have been checked and all tasks completed correctly
