### ISSUE TITLE
Deprecate Geocoding Toolbox

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#289]
# Summary

- **Application Name**: Geocoding Toolbox
- **Application Url**: https://github.com/agrc/geocoding-toolbox

There are now two much better alternatives to this project. For those who are comfortable working in ArcGIS Pro, [Masquerade](https://github.com/agrc/masquerade) is an Esri-compatible locator service that can be used with the out-of-the-box geocoding geoprocessing tools. Non-Esri users can use the [UGRC API Client](https://github.com/agrc/api-client).

Recently, the API client has overtaken this project in total requests per month. (Masquerade requests were wired up to this chart starting today)
![image](https://github.com/agrc/porter/assets/1326248/d81cc417-7fc4-4b7c-b09d-c203deb413f2)

Currently, there are 13 active toolbox geocoders:
![image](https://github.com/agrc/porter/assets/1326248/3dbf0d4e-928f-4e58-8937-08bf5d9e7759)

My proposal is that we immediately add a note to the Geocoding Toolbox repository to notify folks that it has been deprecated. Nothing should break for existing users. Then we write a blog post outlining the newer options and send this to emails linked to the API keys that have recently used the project letting them know of the newer options.

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Blog post outlining newer options (@stdavis, completed: `2024/01/16`)
		https://github.com/agrc/gis.utah.gov/pull/2445
- [x] Send email to emails linked to API keys that recently used this project (@steveoh, completed `2024/03/28`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@stdavis, completed: `2024/01/16`)
		https://github.com/agrc/gis.utah.gov/pull/2445
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (@stdavis, completed: `2024/01/25`)
	- No project folder found.
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) - No entry found (@nathankota, completed: `2024/01/16`)
- ~[ ] Remove Google Analytics property (name, completed: `2023/00/00`)~
- [x] Remove Vimeo video (@stdavis, completed: `2024/01/31`)

### Is there a website?

- [x] Archive source code repository (@stdavis, completed: `2024/01/25`)

## Notification

- ~[ ] Twitter (@steveoh)~

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
@jacobdadams I added you to the "team drive folder" task b/c you created the content there.  Let me know if I can assist.
https://drive.google.com/drive/u/1/folders/1nSusmM75zZNX2V1z3kz-sypnNnFtfht3

**Comment by nathankota** [comment]
I lost my filter for the list of UGRC-specific Business Applications, but after searching for a bit the only entry I see for "geocoding" is the following, which I assume we want to keep, correct @stdavis ? I don't see another Business Application entry specific to the geocoding toolbox.
![image](https://github.com/agrc/porter/assets/15659642/d64868e8-aed4-4e60-8be7-286ed2d084b6)

**Comment by stdavis** [comment]
> which I assume we want to keep, correct

Yes, we should keep it. That looks like the web API to me? Maybe @steveoh would know better.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by stdavis** [comment]
@steveoh Here's some possible text for an email to the API key email addresses:

>You are receiving this message because an API key for api.mapserv.utah.gov registered to this email address has been used recently with our [Geocoding Toolbox](https://github.com/agrc/geocoding-toolbox). This is to inform you that this project has been deprecated and we now have a better solution for geocoding Utah addresses within Esri products called [Masquerade](https://github.com/agrc/masquerade). Please see [our blog post](https://gis.utah.gov/the-gecoding-toolbox-is-being-deprecated/) for more details.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by steveoh** [comment]
We need to remove the Vimeo link how to video.

**Comment by stdavis** [comment]
> We need to remove the Vimeo link how to video.

I couldn't bring myself to delete @jacobdadams's work so I set it to private.

**Comment by jacobdadams** [comment]
It's ok @stdavis, [I will survive](https://www.youtube.com/watch?v=6dYWe1c3OyU)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 289

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
