### ISSUE TITLE
Remove TRANSPORTATION.Roads_FreewayExits from Internal SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#290]
# Summary

- **Internal Dataset Name**: TRANSPORTATION.Roads_FreewayExits
- **External Dataset Name**: Utah Roads Freeway Exits
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=ead23cdea2184a45a92007261675457e

_A short summary of the situation._

We are no longer getting updates from UDOT for this Internal SGID layer.  It has been replaced by a [UDOT-managed web service](https://opendata.gis.utah.gov/datasets/uplan::freeway-exit-locations-1/explore).  The [gis.utah.gov transportation data page](https://gis.utah.gov/data/transportation/roads-system/#FreewayExitPoints) points users to the latest and greatest UDOT data, which is also searchable/findable in the UGRC Open SGID (Hub) site.  

At this point, we just need to clean up Internal SGID by removing/deprecating this outdated layer.

## Migration Guide

All users should be pointing to [UDOT's newest web service](https://opendata.gis.utah.gov/datasets/uplan::freeway-exit-locations-1/explore) for this layer. 

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@DenisePeterson, completed: `2024/01/25`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@DenisePeterson, completed: `2024/01/25`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@DenisePeterson, completed: `2024/01/25`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@DenisePeterson, completed: `2024/01/25`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@DenisePeterson, completed: `2024/01/25`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@DenisePeterson, completed: `2024/01/26`)
    - [x] Unshare the item from its SGID group, which will remove it from Open Data (@DenisePeterson, completed: `2024/01/26`)

### Hard Delete

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@DenisePeterson, completed: `2024/02/08`)
 ~- [ ] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (name, completed: `2023/00/00`).~
- [x] Remove ArcGIS Online item: (@DenisePeterson, completed: `2024/02/08`)
  - Manually delete the AGOL item
  - -OR-
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manaually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  ~- Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (@stdavis, completed: `2023/00/00`)~ (not applicable)
~- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2023/00/00`)~
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@DenisePeterson, completed: `2024/02/08`)
- [x] Update `SGID.META.AGOLItems` table (@DenisePeterson, completed: `2024/02/08`)
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
~- [ ] Delete Google Drive data (name, completed: `2023/00/00`)~
~- [ ] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/00/00`)~ (was not present)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/02/20`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/02/20`)

### Shelve/Static

_Choose one based on situation._

- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2023/00/00`)
- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2023/00/00`)
- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2023/00/00`)

_Add record to table._

- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (name, completed: `2023/00/00`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2024/02/20`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/02/20`)
- [x] Auditor sets appropriate `Deprecated` information (@jacobdadams on `2024/01/26`)

## Are there service dependencies

- [x] Are clients querying this data with the WebAPI?
- [x] Check if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/02/27`)
- [ ] Does any other application depend on this data?

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 290

| check | status |
| - | :-: |
| @DenisePeterson has completed **7** out of **11** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.Roads_FreewayExits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by ZachBeck** [comment]
@gregbunce this layer is in the base maps. Will there be a replacement layer in Internal?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 290

| check | status |
| - | :-: |
| @DenisePeterson has completed **7** out of **11** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.Roads_FreewayExits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by ZachBeck** [comment]
@gregbunce what is your plan for the base maps if you delete this feature class from Internal?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 290

| check | status |
| - | :-: |
| DenisePeterson has completed **11** out of **11** tasks | :+1: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.Roads_FreewayExits

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by gregbunce** [comment]
@ZachBeck do you want the new data to be imported into the internal or are you okay to pull it from the udot service?

**Comment by ZachBeck** [comment]
Internal please.

**Comment by gregbunce** [comment]
@stdavis how would you like us to proceed with wiring up udot's freeway exit web service to internal sgid?  a new porter issue, or is that overkill?

**Comment by gregbunce** [comment]
or is the Honeycomb fgdb updater able to work with udot's web service (aka: maybe we don't need to bring it into Internal)?

**Comment by ZachBeck** [comment]
Honeycomb will pick it up once I add it to the Pro project.

**Comment by stdavis** [comment]
If the only reason we want it in internal is for the base maps, we can come up with a different way to put it in the base maps. I'll work with Zach to get it added to the honeycomb forklift stuff and just get it directly from the service.

**Comment by agrc-conductor** [comment]
## conductor results for TRANSPORTATION.Roads_FreewayExits

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 290

| check | status |
| - | :-: |
| DenisePeterson has completed **11** out of **11** tasks | :+1: |
| stdavis has completed **2** out of **2** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by gregbunce** [comment]
I'm in the process of verifying this data is not linked to any 911 dispatch center or Motorola maps. I have a feeling it is.

**Comment by steveoh** [comment]
> I'm in the process of verifying this data is not linked to any 911 dispatch center or Motorola maps. I have a feeling it is.

All the other tasks have been completed already so it's pretty much gone. What is the plan?

**Comment by gregbunce** [comment]
Okay, I already fixed those.  Let's close this out.

**Comment by gregbunce** [comment]
thanks everyone.
