### ISSUE TITLE
Remove ENVIRONMENT.LakeMonitorSites from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#300]
# Summary

- **Internal Dataset Name**: `SGID.ENVIRONMENT.LakeMonitorSites`
- **External Dataset Name**: `enviroment.lake_monitor_sites`
- **ArcGIS Online Url**: https://opendata.gis.utah.gov/datasets/utah::utah-lake-monitor-sites/about

This layer has become outdated and was replaced long ago by `SGID.ENVIRONMENT.DWQMonitoringLocations`. 

From Ryan Parker on 3/7/2024:
>I was able to chat with Mark Stanger about the [...] monitoring layers in the SGID. We were able to determine that both of these layers are outdated and can be removed. The updated [...] monitoring sites are available in the "Monitoring Locations" layer on the Interactive Map.

Related: #299, #301

## Migration Guide

This dataset has been replaced by `SGID.ENVIRONMENT.DWQMonitoringLocations` which is named `environment.dwq_monitorying_locations` in the Open SGID and [Utah DWQ Monitoring Locations](https://opendata.gis.utah.gov/datasets/utah::utah-dwq-monitoring-locations/about) in the SGID Open Data.
The replaced data is still accessible via our shelved policy in AGOL (a link to the shelved item).

### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@stdavis, completed: `2024/03/18`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@stdavis, completed: `2024/03/18`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@stdavis, completed: `2024/03/18`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) row as deprecated by pasting the related Porter issue URL in the Deprecated field (@stdavis, completed: `2024/03/18`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@stdavis, completed: `2024/03/18`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@jacobdadams, completed: `2024/04/23`)
    - [x] Unshare the item from its SGID group, which will remove it from Open Data (@jacobdadams, completed: `2024/04/23`)
- [x] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (@stdavis, completed: `2024/03/18`). - it's not used

### Hard Delete

**Target Date:** 2024/04/02

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@gregbunce, completed: `2024/04/22`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@gregbunce, completed: `2024/04/22`).
- [x] Remove ArcGIS Online item: (@gregbunce, completed: `2024/04/22`)
  - Manually delete the AGOL item
  - -OR-
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (name, completed: `2024/00/00`)~
~- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (name, completed: `2024/00/00`)~ We just aren't going to migrate these pages into the new website.
- [x] Add this porter url to the `Deprecated` field of the [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@stdavis, completed: `2024/04/02`)
- [x] Update `SGID.META.AGOLItems` table (@jacobdadams, completed: `2024/04/23`)
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
  ~- set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  ~- set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
~- [ ] Delete Google Drive data (@gregbunce, completed: `2024/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/04/29`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/04/29`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/04/29`)

### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2024/00/00`)~
- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (@gregbunce, completed: `2024/04/22`)
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2024/00/00`)~

_Add record to table._

- [x] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online  with `shelved` or `static` in the `CATEGORY` field (@gregbunce, completed: `2024/04/22`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@stdavis on `2024/04/29`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/04/29`)
- [x] Auditor sets appropriate `Deprecated` information (@jacobdadams on `2024/03/19`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/04/23`)

## Are there service dependencies

- [x] Are clients querying this data with the WebAPI?
- [x] Notify Don Jackson (don.jackson1 at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/03/11`)
- [x] Does any other application depend on this data? - Not that I can find on GitHub.

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **10** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
@stdavis, let me know if you need assistance assigning or working on some of the hard delete tasks.

**Comment by steveoh** [comment]
> @stdavis, let me know if you need assistance assigning or working on some of the hard delete tasks.

Would it be better if someone from the data team handled those parts since they are familiar with the process?

**Comment by stdavis** [comment]
I put my name next to stuff that I felt comfortable doing. I was hoping that the team leads would assign the other items as appropriate.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **10** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @gregbunce has completed **1** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @gregbunce has completed **1** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @gregbunce has completed **1** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @gregbunce has completed **1** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **1** out of **5** tasks | :no_entry: |
| @gregbunce has completed **2** out of **8** tasks | :no_entry: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| jacobdadams has completed **5** out of **5** tasks | :+1: |
| gregbunce has completed **7** out of **7** tasks | :+1: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 300

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| jacobdadams has completed **5** out of **5** tasks | :+1: |
| gregbunce has completed **7** out of **7** tasks | :+1: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ENVIRONMENT.LakeMonitorSites

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |
