### ISSUE TITLE
Remove PLANNING.UtahPLI_Areas_Proposal_Jan16 from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#304]
## Summary

- **Internal Dataset Name**: `SGID.PLANNING.UtahPLI_Areas_Proposal_Jan16`
- **External Dataset Name**: `Utah PLI Areas Proposal Jan16`
- **ArcGIS Online Url**: <https://www.arcgis.com/home/item.html?id=4d2327d21f2f4f729e99473b64ff1794/>

In a recent review of the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148), these apparently duplicate datasets were discovered. `PublicLandsInitiativeHR5780Areas_BLM2016` seemed to be the more complete dataset so the decision was made to deprecate `UtahPLI_Areas_Proposal_Jan16`.

### Migration Guide

This dataset has been replaced by (`SGID.PLANNING.PublicLandsInitiativeHR5780Areas_BLM2016`) which is named (`planning.public_lands_initiative_hr5780_areas_blm_2016`) in the Open SGID and (`Utah Public Lands Initiative HR5780 Areas BLM 2016`) in the SGID on ArcGIS.

The replaced data is still accessible via our shelved policy in AGOL (a link to the shelved item).

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

#### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@stdavis, completed: `2024/04/02`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@stdavis, completed: `2024/00/00`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@stdavis, completed: `2024/04/02`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) row as deprecated by pasting the related Porter issue URL in the "porterUrl" field and setting the value of the "ugrcStatus" field as "deprecated" (@stdavis, completed: `2024/04/02`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@stdavis, completed: `2024/04/02`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@jacobdadams, completed: `2024/04/05`)
    - [x] Unshare the item from its SGID group, which will remove it from the SGID on ArcGIS (@jacobdadams, completed: `2024/04/05`)
- [x] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (@stdavis, completed: `2024/03/28`).

#### Hard Delete

**Target Date:** 2024/04/16

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@gregbunce, completed: `2024/04/29`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@gregbunce, completed: `2024/04/29`).
- [x] Remove ArcGIS Online item: (@jacobdadams, completed: `2024/06/17`)
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (@gregbunce, completed: `2024/00/00`)~
	- does not exist
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@stdavis, completed: `2024/05/06`)
	- could not find any

~- [ ] Update `SGID.META.AGOLItems` table (@stdavis, completed: `2024/00/00`)~
  ~- cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  ~- set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  ~- set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
~- [ ] Delete Google Drive data (@gregbunce, completed: `2024/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/05/13`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/05/13`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/05/13`)

#### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2024/00/00`)~
- [x] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (@jacobdadams, completed: `2024/06/17`)
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2024/00/00`)~

_Add record to table._

- [x] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online with `shelved` or `static` in the `CATEGORY` field (@jacobdadams, completed: `2024/00/00`)

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@stdavis on `2024/05/20`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/05/30`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/04/05`)

### Are there service dependencies

- [x] Are clients querying this data with the WebAPI?
~- [ ] Notify Don Jackson (don.jackson1 at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/00/00`)~
- [x] Does any other application depend on this data?
	- Not that I could find in a search on GitHub.

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **1** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by gregbunce** [comment]
> The replaced data is still accessible via our shelved policy in AGOL (a link to the shelved item).

@stdavis are you requesting we 'shelf' the layer that we are removing?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **4** tasks | :no_entry: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **6** out of **12** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | Exception was thrown! |
| meta table | Exception was thrown! |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| @stdavis has completed **10** out of **11** tasks | :no_entry: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| stdavis has completed **11** out of **11** tasks | :+1: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| stdavis has completed **11** out of **11** tasks | :+1: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| steveoh has completed **3** out of **3** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 304

| check | status |
| - | :-: |
| stdavis has completed **11** out of **11** tasks | :+1: |
| @jacobdadams has completed **3** out of **6** tasks | :no_entry: |
| gregbunce has completed **3** out of **3** tasks | :+1: |
| steveoh has completed **3** out of **3** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by stdavis** [comment]
@jacobdadams I'd love to get this issue closed out this week if you have some time to work on it. Thanks!

**Comment by agrc-conductor** [comment]
## conductor results for PLANNING.UtahPLI_Areas_Proposal_Jan16

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by stdavis** [comment]
Paging Mr @jacobdadams ...

**Comment by jacobdadams** [comment]
Ok, sorry. Layer has been shelved. We could wait for one more auditor run to verify auditor sees it as shelved, but we should be good.
