### ISSUE TITLE
Add historical monuments and marker data to the SGID

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#31]
# Summary

- **Proposed Dataset Name**: MonumentsAndMarkers
- **Proposed ISO Category**: History
- **Data Description**: Point feature class of historical monuments and markers
- **Source Agency/Entity**: State History
- **Contact**: Skylar Schulzke sschulzke@utah.gov 
- **Update Frequency**: as needed

# Triage

- [x] Data Team Triage Complete (@ZachBeck  )
- [ ] Dev Team Triage Complete (@steveoh )
~- [ ] Cadastre Team Triage Complete~

# We are introducing data

The data was or will be added on `2020/06/22` to the following areas

- [x] Internal SGID
~- [ ] SGID10~
~- [ ] ArcGIS Online~

# The data should propagate automatically to

- [x] ArcGIS Online
~- [ ] Internal SGID~
- [x] SGID10
- [x] Open SGID
- [x] Open data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] Stewardship doc and sgid-index
- [x] `SGID.META.AGOLItems`

# We have verified the data is live 

- [x] ArcGIS Online (@stdavis  `2020/06/24`)
- [x] Internal SGID (@ZachBeck  `2020/06/22`)
- [x] SGID10 (@steveoh on `2020/06/24`)
- [x] Open SGID (@steveoh on `2020/06/24`)
- [x] Open data (@jacobdadams on `2020/06/24`)
- [x] gis.utah.gov data pages (@ZachBeck on ``)
- [x] Stewardship doc and sgid-index (@ZachBeck on `2020/06/22`)
- [x] `SGID.META.AGOLItems` (@ZachBeck on `2020/06/22`)
- [x] `SGID.META.ChangeDetection` (@steveoh on `2020/06/24`)

# Notification

~- [ ] Blog post (@assigned)~
- [x] Twitter (@steveoh)

**Comment by steveoh** [comment]
@ZachBeck do you not want this data in SGID10 or are you ok if swapper puts it there?

**Comment by steveoh** [comment]
Also for my own curiosity, what is in this dataset. I think the plss terms are messing with me.

**Comment by ZachBeck** [comment]
I didn't see any reason for it to go there but I'm fine if it does.

**Comment by stdavis** [comment]
Swapper [doesn't have any ability to make exceptions](https://github.com/agrc/warehouse/blob/master/sgid/SwapperPallet.py#L29) currently. So if there are no worries about it, I would say just let it flow to SGID10, AGOL, & Open SGID.

**Comment by steveoh** [comment]
I remember deciding as a group to try to keep all of the sgid's the same so I agree with scott.

**Comment by ZachBeck** [comment]
Sweeper found/deleted 77 duplicates in the data. Let me know when the data makes it's way to agol and I can finish the META.AGOLItems table and the url in stewardship index

**Comment by stdavis** [comment]
It should be pushed to AGOL tomorrow evening.

**Comment by stdavis** [comment]
/remind me to check the data on June 24

**Comment by steveoh** [comment]
@ZachBeck I think you forgot to add the geometry type to the agol meta table.

**Comment by ZachBeck** [comment]
It's in there now.

**Comment by stdavis** [comment]
FYI - https://utah.maps.arcgis.com/home/item.html?id=63de4118823e4e3eba943ca43caefc72

**Comment by steveoh** [comment]
We might need to add another checkbox to verify that @jacobdadams script runs and updates the agol items summary, description, etc. Thoughts?

**Comment by stdavis** [comment]
> We might need to add another checkbox to verify that @jacobdadams script runs and updates the agol items summary, description, etc. Thoughts?

That's probably a good idea. I wondered if I should include that in the AGOLPallet but then decided that I didn't want to duplicate efforts.

**Comment by steveoh** [comment]
@ZachBeck this one is waiting on you I believe for the gis page before we can close it.

**Comment by steveoh** [comment]
This issue is missing the conductor metadata to enable auto-nagging.
        Please add `<!-- conductor = {...} -->` to the original issue with the details of the addition or deprecation.

        Refer to the wiki for the conductor property options.

**Comment by ZachBeck** [comment]
I'm hoping to take care of it tomorrow

**Comment by stdavis** [comment]
Ping @ZachBeck

**Comment by ZachBeck** [comment]
Pong, and done
