### ISSUE TITLE
Deprecate Templater Application

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#315]
## Summary

- **Application Name**: Templater
- **Application Urls**
  - Staging: n/a
  - Production: [agrc.github.io/templater](http://agrc.github.io/templater)

This app is no longer relevant since we upgraded the website to astro. It will eventually be replaced by [issue templates and github actions](https://github.com/agrc/gis.utah.gov/issues/2531).

#### Target delete date `2024/04/12`

- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (@stdavis, completed: `2024/04/12`)
	- https://github.com/agrc/gis.utah.gov/pull/2726

~- [ ] Remove application-specific Databases (name, completed: `2024/00/00`)~
~- [ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2024/00/00`)~
~- [ ] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (name, completed: `2024/00/00`)~
~- [ ] Remove Google Analytics property (name, completed: `2024/00/00`)~

#### Is there a website?

- [x] Remove DNS entry (@stdavis, completed: `2024/04/12`)
	- unpublished GH Pages site
- [x] Archive source code repository (@stdavis, completed: `2024/04/12`)
~- [ ] Remove app-specific quad word from Discover system (name, completed: `2024/00/00`)~
~- [ ] Remove app-specific api key from UGRC API (name, completed: `2024/00/00`)~
~- [ ] Remove cloud project (name, completed: `2024/00/00`)~
~- [ ] Remove terraform infrastructure (name, completed: `2024/00/00`)~

_Choose one._

~- [ ] Remove from the web server (name, completed: `2024/00/00`)~
~- [ ] Replace app with a static page with information (name, completed: `2024/00/00`)~
- [x] Redirect somewhere else (@stdavis, completed: `2024/04/12`)
	- https://github.com/agrc/gis.utah.gov/pull/2726

#### Is there a map service or AGOL item?

~- [ ] Stop (name, completed: `2024/00/00`)~
~- [ ] Delete (name, completed: `2024/00/00`)~
~- [ ] Unregister Data Store in ArcGIS Server (name, completed: `2024/00/00`)~

#### Is there a forklift pallet?

~- [ ] Remove repo (name, completed: `2024/00/00`)~
  - don't forget to remove the pallet from the current packing slip in receiving!
~- [ ] Remove stale data from forklift hashing and receiving (name, completed: `2024/00/00`)~
~- [ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2024/00/00`)~

#### Are there service dependencies?

~- [ ] Validate that the web api does not query it (name, completed: `2024/00/00`)~
- [x] Validate that UGRC or applications do not reference it (@stdavis, completed: `2024/04/12`)

### Notification

~- [ ] Twitter (@steveoh)~

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by stdavis** [comment]
@steveoh Will you take another look at this issue and let me know if I missed something?

**Comment by steveoh** [comment]
It looks thorough to me. We may need to revisit a solution in the future for guest blogs but I'm happy with this decision for now.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 315

| check | status |
| - | :-: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| steveoh has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
Closing this as complete.
