### ISSUE TITLE
Add Utah Tax Entities 2024 from Utah State Tax Commission 

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/porter#321]
## Summary

- **Proposed Readable Name**: Utah Tax Entities 2024
- **Proposed Internal Dataset Name**: SGID.ECONOMY.TaxEntities2024
- **Proposed External Dataset Name**: opensgid.economy.tax_entities_2024
- **Proposed Data Category**: ECONOMY
- **Data Description**: Tax Entities in the State of Utah as maintained by the Utah State Tax Commission 
- **Source Agency/Entity**: Utah State Tax Commission 
- **Contact**: Nick Kenczka
- **Update Frequency**: Annually

This is updated Tax Entities data for 2024 and was provided by the Utah State Tax Commission. 

### The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

### The data is of high quality

- [x] Sweeper checks have run and passed (@ZachBeck on `2024/05/22`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@ZachBeck on `2024/05/22`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@ZachBeck  on `2024/05/22`)

### Where is the data source

_Choose one._

- [x] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@ZachBeck, completed: `2024/05/22`)
- [ ] ~Configure forklift for Farm from AGOL (name, completed: `2024/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@DenisePeterson, completed: `2024/06/03`)
- [x] Add a [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) record (@ZachBeck, completed: `2024/05/22`)
- [x] Complete a `SGID.META.AGOLItems` record (@ZachBeck, completed: `2024/05/22`)
  - `AGOL_ITEM_ID` will be populated by Forklift after it publishes the new AGOL item.
- [ ] ~Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2024/00/00`)~
- [x] Define a record set with archives (@brigsz, completed: `2024/06/13`)

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@stdavis on `2024/05/28`)
- [x] ArcGIS Online via forklift (@stdavis on `2024/05/28`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2024/05/24`)
- [x] [SGID on ArcGIS](https://opendata.gis.utah.gov) (@stdavis on `2024/05/28`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2024/06/10`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@stdavis on `2024/05/28`)

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 321

| check | status |
| - | :-: |
| @ZachBeck has completed **0** out of **6** tasks | :no_entry: |
| @DenisePeterson has completed **0** out of **1** tasks | :no_entry: |
| @brigsz has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2024

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find ECONOMY.TaxEntities2024 in the worksheet |

**Comment by ZachBeck** [comment]
Do we know if this dataset is for 2023 or 2024?

**Comment by DenisePeterson** [comment]
2024

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2024

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - justification | :no_entry: |
| - dataContactEmail | :no_entry: |
| - dataContactName | :no_entry: |
| - productPage | :no_entry: |
| - itemId | :no_entry: |
| - displayName | :+1: |
| - description | :+1: |
| - category | :+1: |
| - productType | :+1: |
| - ugrcSteward | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2024

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - justification | :no_entry: |
| - dataContactEmail | :no_entry: |
| - dataContactName | :no_entry: |
| - displayName | :+1: |
| - description | :+1: |
| - category | :+1: |
| - productType | :+1: |
| - ugrcSteward | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 321

| check | status |
| - | :-: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
| DenisePeterson has completed **1** out of **1** tasks | :+1: |
| @brigsz has completed **0** out of **1** tasks | :no_entry: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2024

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - displayName | :+1: |
| - description | :+1: |
| - justification | :+1: |
| - category | :+1: |
| - productType | :+1: |
| - ugrcSteward | :+1: |
| - dataContactEmail | :+1: |
| - dataContactName | :+1: |

**Comment by brigsz** [comment]
I am unsure if we are facing a terminology issue on this.  Right now there is a 
series # of 27040 and a retention schedule.  The Series has a title of
 SERIES: 27040
TITLE: Tax entities records
DATES: 1995-
ARRANGEMENT: Grouped by file type, thereunder chronological

I would imagine that since the series exists, then this record, just is assigned to that series.  Not sure we need to actually call out the record.  I will continue to look

**Comment by brigsz** [comment]
Okay, concerning Record Series etc.  When a layer is created for the SGID someone must check to see does it fit into a record series.  If not work it out, and sounds like we need to have a schedule or something that will trigger a submission to archives with the proper forms.

@steveoh I know this conversation is only taking place in this issue, but applies to many issues.  Do you want to change the template and then I will look at each layer and see if it fits into a record series or if we need to do something more?

**Comment by steveoh** [comment]
The issue template is per dataset so I'm not sure what we'd update it to. What is your suggestion? 

I think the check box is to make sure that the data fits into an existing series or you will create a new one for it to go in before checking the box.

**Comment by brigsz** [comment]
Yes, your second paragraph makes total sense.  It was just when it calls
out Record set, that seems like some official Archives term. Whereas the
"making sure the data fits into an existing series or you will create a new
one for it to go in before checking the box" sounds very actionable.  There
must be a line we can put that easily conveys that.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 321

| check | status |
| - | :-: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
| DenisePeterson has completed **1** out of **1** tasks | :+1: |
| brigsz has completed **1** out of **1** tasks | :+1: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **3** out of **3** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for ECONOMY.TaxEntities2024

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - displayName | :+1: |
| - description | :+1: |
| - justification | :+1: |
| - category | :+1: |
| - productType | :+1: |
| - ugrcSteward | :+1: |
| - dataContactEmail | :+1: |
| - dataContactName | :+1: |

**Comment by stdavis** [comment]
@DenisePeterson I think that this issue can be closed out, no?

**Comment by DenisePeterson** [comment]
@stdavis Thanks for the reminder. Yes! I'll close this out now.
