### ISSUE TITLE
Remove SOCIETY.StateFuelSites from Internal SGID Only and maintaining AGOL layer

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#325]
## Summary

- **SOCIETY.StateFuelSites**:
- **opensgid.society.state_fuel_sites**:
- **https://utah.maps.arcgis.com/home/item.html?id=8d9bc67285fb421fb15d55342148ac1e**:

_A short summary of the situation._

### Migration Guide

_A short summary of how users affected by this deprecation can modify their workflows and projects to continue to get similar or improved functionality_

It was determined that this layer does not have a lot of value living in the Internal database. However it must persist in AGOL for an application. This way requested updates from the steward can immediately be reflected in the map by editing the AGOL layer directly. 

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

#### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

~- [ ] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@rkelson, completed: `2024/00/00`)~
~- [ ] Remove all tags other than "Deprecated" in the SDE metadata (@rkelson, completed: `2024/00/00`)~
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@rkelson, completed: `2024/07/03`)
~- [ ] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) row as deprecated by pasting the related Porter issue URL in the "porterUrl" field and setting the value of the "ugrcStatus" field as "removed". Also update the "refreshCycle" field (@rkelson, completed: `2024/00/00`)~
~- [ ] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@rkelson, completed: `2024/00/00`)~
- [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@rkelson, completed: `2024/07/03`)
~- [ ] Unshare the item from its SGID group, which will remove it from the SGID on ArcGIS (@jacobdadams, completed: `2024/00/00`)~
- [x] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (@rkelson, completed: `2024/07/03`).

#### Hard Delete

**Target Date:** 2024/07/22

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@rkelson, completed: `2024/08/06`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@rkelson, completed: `2024/07/03`). Created Utah_State_Fuel_Sites_20240620.gdb in the folder above
~- [ ] Remove ArcGIS Online item: (name, completed: `2024/00/00`)~
~- [ ] Remove Farm from AGOL connection (@stdavis, completed: `2024/00/00`)~
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) fields: "arcGisOnline", "openSgid", "openSgidTableName" (@stdavis, completed: `2024/07/22`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@rkelson , completed: `2024/07/09`)
~- [ ] Update `SGID.META.AGOLItems` table (name, completed: `2024/00/00`)~
~- [ ] Delete Google Drive data (name, completed: `2024/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/07/22`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/07/22`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/07/22`)

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@stdavis on `2024/07/29`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/08/12`)
~- [ ] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/00/00`)~

### Are there service dependencies

- [x] Are clients querying this data with the WebAPI? (@steveoh on `2024/08/12`)
- [x] Notify Don Jackson (don.jackson1 at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/06/20`)
- [x] Does any other application depend on this data?

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by rkelson** [comment]
This is a bit different than the usual deprecation from Internal as the AGOL item needs to persist after the removal from internal. I am not exactly sure how to accomplish this correctly. Any guidance on the best path forward is appreciated.

**Comment by steveoh** [comment]
For these types of AGOL only layers, we need to implement a backup strategy in case of data loss.

**Comment by rkelson** [comment]
Is there a list of similar agol only layers?

**Comment by steveoh** [comment]
@gregbunce 🔔

**Comment by gregbunce** [comment]
this is where the stewardship sheet (sgid index tab) as a database would be handy to run a query. one quick thought.

- we could use the stewardship sheet to filter where StorageType in (AGOL, Cloud) and HostedBy = UGRC and ArcGISOnline = true and itemId is not null.  or something like that. you get the idea.

Ultimately, that info is in the stewardship sheet (sgid index tab). 

@rkelson, i suggest exploring that route. if there are holes, we can work together to alter the sheet so we accommodate these types of questions.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 325

| check | status |
| - | :-: |
| @rkelson has completed **0** out of **9** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **2** tasks | :no_entry: |
| @stdavis has completed **0** out of **5** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 325

| check | status |
| - | :-: |
| @rkelson has completed **5** out of **7** tasks | :no_entry: |
| @stdavis has completed **0** out of **5** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 325

| check | status |
| - | :-: |
| @rkelson has completed **6** out of **7** tasks | :no_entry: |
| @stdavis has completed **0** out of **5** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 325

| check | status |
| - | :-: |
| @rkelson has completed **6** out of **7** tasks | :no_entry: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 325

| check | status |
| - | :-: |
| rkelson has completed **7** out of **7** tasks | :+1: |
| stdavis has completed **5** out of **5** tasks | :+1: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for SOCIETY.StateFuelSites

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |
