### ISSUE TITLE
Deprecate Fleet Vehicle Filter

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#326]
## Summary

- **Application Name**: Fleet Vehicle Filter
- **Application Urls**
  - Staging: n/a
  - Production: https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=a9c121751583400caeff41e0209ae163

This is a WAB app that Fleet no longer needs, so we'll just completely deprecate it. Map will be unshared on `2024/07/01`, with the data left in AGOL for future reference. 

The data update is done manually so there are no automations to remove.

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Target delete date (@jacobdadams , set: `2024/06/21`)
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2024/00/00`)~
- ~[ ] Remove application-specific Databases (name, completed: `2024/00/00`)~
- ~[ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2024/00/00`)~
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (@nathankota , completed: `2024/06/28`)
- ~[ ] Remove Google Analytics property (name, completed: `2024/00/00`)~

#### Is there a website?

- ~[ ] Remove DNS entry (name, completed: `2024/00/00`)~
- ~[ ] Archive source code repository (name, completed: `2024/00/00`)~
- ~[ ] Remove app-specific quad word from Discover system (name, completed: `2024/00/00`)~
- ~[ ] Remove app-specific api key from UGRC API (name, completed: `2024/00/00`)~
- ~[ ] Remove cloud project (name, completed: `2024/00/00`)~
- ~[ ] Remove terraform infrastructure (name, completed: `2024/00/00`)~

_Choose one._

- ~[ ] Remove from the web server (name, completed: `2024/00/00`)~
- ~[ ] Replace app with a static page with information (name, completed: `2024/00/00`)~
- ~[ ] Redirect somewhere else (name, completed: `2024/00/00`)~

#### Is there a map service or AGOL item?

- [x] Mark app and feature services as deprecated (@jacobdadams , completed: `2024/06/21`)
- [x] Unshare app and feature services (@jacobdadams , completed `2024/07/01`)
- ~[ ] Delete (name, completed: `2024/00/00`)~
- ~[ ] Unregister Data Store in ArcGIS Server (name, completed: `2024/00/00`)~

#### Is there a forklift pallet?

- ~[ ] Remove repo (name, completed: `2024/00/00`)~
  - don't forget to remove the pallet from the current packing slip in receiving!
- ~[ ] Remove stale data from forklift hashing and receiving (name, completed: `2024/00/00`)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes` (name, completed: `2024/00/00`)~

#### Are there service dependencies?

- ~[ ] Validate that the web api does not query it (name, completed: `2024/00/00`)~
- ~[ ] Validate that UGRC or applications do not reference it (name, completed: `2024/00/00`)~

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- ~[ ] Data Team (@gregbunce)~
- [x] Dev Team (@steveoh)
- ~[ ] Cadastre Team (@rkelson)~

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 326

| check | status |
| - | :-: |
| @jacobdadams has completed **2** out of **3** tasks | :no_entry: |
| @nathankota has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 326

| check | status |
| - | :-: |
| @jacobdadams has completed **2** out of **3** tasks | :no_entry: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **2** out of **2** tasks | :+1: |
