### ISSUE TITLE
Create labels for extra context

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#33]
### Describe the problem you are having

I think labels could help give context to the state of an open issue.

For additions something like...

- intending to add
- added
- waiting for propagation
- waiting for validation
- validated

We could do something similar with removals. 

I wonder if you think this would be too much ceremony or if it would be helpful.

**Comment by nathankota** [comment]
I think it would be useful for deciphering the status of an issue at a glance, similar to [open sgid issues](https://github.com/agrc/open-sgid/issues).

**Comment by steveoh** [comment]
> I think it would be useful for deciphering the status of an issue at a glance, similar to [open sgid issues](https://github.com/agrc/open-sgid/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Can you think of some useful labels?

**Comment by stdavis** [comment]
I would worry about creating more process and required clicks. This almost seems like a good use-case for projects. However, that's a whole other can of worms. I would say that the labels might be nice for the GitHub-geeks to keep things organized, but I wouldn't make it any required part of the process.

**Comment by ZachBeck** [comment]
I agree with Scott, there's a lot of T's to dot and I's to cross already. I'd vote to run a few feature classes through the process and if it seems like things are falling through the cracks then reevaluate the process.

**Comment by nathankota** [comment]
> > I think it would be useful for deciphering the status of an issue at a glance, similar to [open sgid issues](https://github.com/agrc/open-sgid/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
> 
> Can you think of some useful labels?

I accept being outvoted at this point. If we revisit labels I will help to suggest some.
