### ISSUE TITLE
Deprecate Broadband Speedtest Dashboard

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#330]
## Summary

- **Application Name**: Broadband Speedtest Dashboard
- **Application Urls**
  - Production: https://utah.maps.arcgis.com/apps/dashboards/829a7d8f5adc4d5bb283d85bf4bc9dfe

This dashboard and associated skid were intended to track the progress of the state's speedtest campaign. However, changes to the NTIA grant process and the purchase of Ookla data seems to have rendered it moot and it never got past the dev stage.

Rebecca Dilg authorized archiving the dashboard and skid in an email dated 11 July 2024. We will deprecate and unshare the dashboard and data, archive the repo, and remove the skid from GCP. 

There is no grace period needed; it hasn't seen much use at all.

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Target delete date (@jacobdadams, set: `2024/07/11`)
- ~[ ] Update relevant [gis.utah.gov](https://gis.utah.gov/developer/application) application pages (name, completed: `2024/00/00`)~
- ~[ ] Remove application-specific Databases (name, completed: `2024/00/00`)~
- ~[ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (name, completed: `2024/00/00`)~
- [x] Remove from Application Portfolio Management ("Business Applications" in ServiceNow) (No UGRC Business Application record for this app @nathankota, completed: `2024/07/15`)
- ~[ ] Remove Google Analytics property (name, completed: `2024/00/00`)~

#### Is there a website?

- ~[ ] Remove DNS entry (name, completed: `2024/00/00`)~
- [x] Archive source code repository (@jacobdadams, completed: `2024/07/11`)
- ~[ ] Remove app-specific quad word from Discover system (name, completed: `2024/00/00`)~
- ~[ ] Remove app-specific api key from UGRC API (name, completed: `2024/00/00`)~
- [x] Remove cloud project (@steveoh, completed: `2024/07/15`)
- [x] Remove terraform infrastructure (@steveoh , completed: `2024/07/15`)

_Choose one._

- ~[ ] Remove from the web server (name, completed: `2024/00/00`)~
- ~[ ] Replace app with a static page with information (name, completed: `2024/00/00`)~
- ~[ ] Redirect somewhere else (name, completed: `2024/00/00`)~

#### Is there a map service or AGOL item?

- [x] Unshare map, feature service (@jacobdadams, completed: `2024/07/12`)
- ~[ ] Delete (name, completed: `2024/00/00`)~
- ~[ ] Unregister Data Store in ArcGIS Server (name, completed: `2024/00/00`)~

#### Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh, completed: `2024/07/15`)
- [x] Validate that UGRC or applications do not reference it (@steveoh, completed: `2024/07/15`)

### Notification

- ~[ ] Twitter (@steveoh)~
  - No real need, it was never really launched anyways.

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 330

| check | status |
| - | :-: |
| jacobdadams has completed **3** out of **3** tasks | :+1: |
| nathankota has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **0** out of **5** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
This looks ready to close 🏁 .
