### ISSUE TITLE
Remove UTA Light Rail Stations from SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#334]
## Summary

- **Internal Dataset Name**: Transportation.LightRailStations_UTA
- **External Dataset Name**: Utah UTA Light Rail Stations
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=bb8f7bc8871b4a7594bcc037631073e7

UTA now has its own ArcGIS [Enterprise Portal](https://maps.rideuta.com/server/rest/services) and is hosting this layer and sharing it with UGRC's SGID ([SGID on ArcGIS](https://opendata.gis.utah.gov/datasets/utah::trax-light-rail-stations/about)) via [Distributed Collaboration in UGRC's AGOL](https://utah.maps.arcgis.com/home/group.html?id=0d070836637a449ba10680c92f2cd737#overview). 

### Migration Guide

The goal is to direct our users to UTA's [web service](https://opendata.gis.utah.gov/datasets/utah::trax-light-rail-stations/about), via the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit?gid=1024261148#gid=1024261148) and the SGID on ArcGIS.

#### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@gregbunce, completed: `2024/07/30`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@gregbunce, completed: `2024/07/30`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@gregbunce, completed: `2024/07/30`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) row to point to UTA's hosted data (@gregbunce, completed: `2024/07/30`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@gregbunce, completed: `2024/07/30`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@gregbunce, completed: `2024/08/01`)
    - [x] Unshare the item from its SGID group, which will remove it from the SGID on ArcGIS (@gregbunce, completed: `2024/07/30`)
- [x] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (@ZachBeck, completed: `2024/08/12`).

#### Hard Delete

**Target Date:** 2024/08/15

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@ZachBeck, completed: `2024/08/15`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@ZachBeck, completed: `2024/08/15`).
- [x] Remove ArcGIS Online item: (@ZachBeck, completed: `2024/08/24`)
  - Manually delete the AGOL item
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (@stdavis, completed: `2024/00/00`)~
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) (@gregbunce, completed: `2024/08/15`)
- [x] Remove/delete the relevant gis.utah.gov data page (including downloadMetadata.ts) (@ZachBeck, completed: 2024/08/15)
- [x] Update `SGID.META.AGOLItems` table, remove row (@ZachBeck, completed: `2024/08/15`)
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/08/26`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/08/26`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/08/26`)

#### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2024/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online with `shelved` or `static` in the `CATEGORY` field (name, completed: `2024/00/00`)~

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh, on `2024/09/02`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/09/02`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/07/31`)

### Are there service dependencies

- [x] Are clients querying this data with the WebAPI?
- [x] Update NG911 client maps with latest data sources (@gregbunce on `2024/08/15`)
- [x] Does any other application depend on this data?
  - [x] Remove from locate pallet and repoint app at UTA service (@stdavis, completed: `2024/08/19`)

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **10** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| @gregbunce has completed **8** out of **10** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| @gregbunce has completed **8** out of **10** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **6** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by gregbunce** [comment]
note about this layer and the [sgid index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit?gid=1024261148#gid=1024261148): I used the existing row (record) for this layer in the sheet and updated the values with the newest information (name, urls, etc).

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| gregbunce has completed **10** out of **10** tasks | :+1: |
| @ZachBeck has completed **5** out of **6** tasks | :no_entry: |
| @stdavis has completed **1** out of **5** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| gregbunce has completed **10** out of **10** tasks | :+1: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| gregbunce has completed **10** out of **10** tasks | :+1: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 334

| check | status |
| - | :-: |
| gregbunce has completed **10** out of **10** tasks | :+1: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
| stdavis has completed **4** out of **4** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Transportation.LightRailStations_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |
