### ISSUE TITLE
Old AGOL Items: UtahAGRC

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#35]
I've found the following items in AGOL that are owned by the UtahAGRC user that look old, unused, and/or broken. After the list is completed, we will triage it to figure out who knows it best and can determine if they can be deprecated/deleted. If they are part of the SGID or some other major project, consider opening a new issue using the full deprecation checklist/process.

I don't mean to call anyone out for their old data. I just wanted to have a place to track these things as I found them as part of the HTTP/HTTPS update process.

Everyone will look through and **check items that should be saved**. Tag the item with your name (`@user`) if you take care of it. After you've looked through it all, make a comment at the bottom stating so. If you deleted it, strike through the item.

- [ ] ~DNR DOGM Oil and Gas Wells, Fields, Units (Map Image Layer): http://utah.maps.arcgis.com/home/item.html?id=54e5d363060040469cb666c66a9e95ef~ @jacobdadams
- [ ] Utah's State Geographic Information Database (AGRC) (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=c7bb9f62fa7a4724b87f6df184b465bb (Old open data site? Points to `https://sgid-utah.opendata.arcgis.com`—mark as deprecated?)
- [ ] ~sbi map old (Web Map): http://utah.maps.arcgis.com/home/item.html?id=bd7d75dddc3c4fd58825447faf88727c~ @jacobdadams
- [ ] ~Wind Turbines (Map Image Layer): http://utah.maps.arcgis.com/home/item.html?id=7ece6e2d2e8f49c797e5d875fdfacb21~ @jacobdadams
- [ ] ~Dynamic Great Salt Lake (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=0615f71ee3c149b4a355b56189b0e0b5~ @jacobdadams
- [ ] ~Geospatial Mapping Technology (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=b3a66a0a87e740739afa74f896dd3d0d~ @jacobdadams
- [ ] ~gis.utah.gov website (Stat eof Utah, AGRC) (Document Link): http://utah.maps.arcgis.com/home/item.html?id=814fdc17e0b94edaa268f33b6711416f~ @jacobdadams
- [ ] ~Utah School Board District with Representatives (Web Map): http://utah.maps.arcgis.com/home/item.html?id=9ff4b96cc6434415846f618d93604128~ @jacobdadams
- [ ] ~Non Emergency Services - Zip Code Areas (Web Map): http://utah.maps.arcgis.com/home/item.html?id=fe2e69abbe774f4596c347a8a995c437~ @jacobdadams
- [ ] ~atals.utah.gov (online general reference & place finding) (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=dce4236412f8429a9a11bb498e986006~ @jacobdadams
- [ ] ~Digital Representations of Tribal Boundaries (Web Map): http://utah.maps.arcgis.com/home/item.html?id=0b9d2c5fae344a0db0c0643494041849~ @jacobdadams
- [ ] ~Mobile Broadband Drive Test Roads (Web Map): http://utah.maps.arcgis.com/home/item.html?id=6cb7d9d7ac0f4b00a0d5cdc95bc20a81~ @jacobdadams
- [ ] ~UORG 2016 Infrastructure Trail Projects AGRC BASEMAP (Web Map): http://utah.maps.arcgis.com/home/item.html?id=3a572f815ee24c70a9d65bdb4f5f2306 (appears to be old basemap for the story map; only has 56 views compared to aprox 1000 for other 2016 web map)~ @jacobdadams
- [ ] ~Utah Tower Locations WGS84 Old (Web Map): (not shared publicly; search by name)~@rkelson Deleted
- [ ] ~Utah Tower Locations WGS84 Old2 (Web Map): (not shared publicly, search by name)~@rkelson Deleted
- [ ] ~Proposed UCA Tower Locations (Feature Layer): (not shared publicly, search by name)~@rkelson Deleted
- [ ] ~Existing UCA Tower Locations (Feature Layer): (not shared publicly, search by name)~@rkelson Deleted
- [ ] ~LandMobileRadio (Map Image Layer): (not shared publicly, search by name)~@jacobdadams
- [ ] ~GOED Broadband Planning Map (Web Map): (not shared publicly, search by name)~
- [ ] ~LTELMR (Web Map): http://utah.maps.arcgis.com/home/item.html?id=a5aa41a499fa495399bf93ffc06abad6~ @jacobdadams
- [ ] ~Utah Precincts Map (Web Map): http://utah.maps.arcgis.com/home/item.html?id=1d8c9a8c110e44dcbf5f9d4bdc77a217~ @jacobdadams
- [ ] ~Utah State Dispatch Center Boundaries (Web Map): (not shared publicly, search by name)~ @jacobdadams
- [ ] ~Zip Code Boundaries for Utah (Web Map): (not shared publicly, search by name)~ @jacobdadams
- [ ] ~Mobile BB 3 and 6 Models (Feature Layer): (not shared publicly, search by name)~ @jacobdadams
- [ ] ~Test Map View (Web Map): (not shared publicly, search by name)~ @jacobdadams
- [ ] ~Transition to FCC's Data Model: Broadband Coverage Difference by Technology Type-Copy (Web Map): http://utah.maps.arcgis.com/home/item.html?id=12dcf59e462e4f36acb33bf71b21af20~ @jacobdadams
- [ ] ~Utah's State Geographic Information Database (AGRC) - Copied (Hub Site Application): not shared publicly — copy of our hub site?)~
- [ ] ~UORG 2016 Infrastructure Trail Projects (Web Mapping Application): (not shared publicly, search by name — unshared copy of public app?)~ @jacobdadams

**Comment by steveoh** [comment]
I don't need any of these. 

✅ signing off

**Comment by steveoh** [comment]
/remind me to delete everything without a check on 7/21/2020

**Comment by stdavis** [comment]
I don't need any of these.

✅ signing off

**Comment by eneemann** [comment]
I don't need any of these.
✅ signing off

**Comment by gregbunce** [comment]
I don't need any of these.

✅ signing off

**Comment by nathankota** [comment]
nuke it all!

**Comment by steveoh** [comment]
i cleaned up the cloned site without issue. I believe that was the last item.
