### ISSUE TITLE
Remove Utah Metro Townships from SGID

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/porter#352]
## Summary

- **Internal Dataset Name**: Boundaries.MetroTownships
- **External Dataset Name**: Utah Metro Townships
- **ArcGIS Online Url**: https://utah.maps.arcgis.com/home/item.html?id=103c6dc6764747079919c20927f40a9f

Per legislation from HB35 signed into law by Gov. Cox in March, 2024, “... an incorporated township is automatically converted into a municipality.” As such, the Metro Township layer is no longer needed.

### Migration Guide

Users can now find relevant data in [Utah Municipal Boundaries](https://utah.maps.arcgis.com/apps/mapviewer/index.html?layers=543fa1f073714198a3dbf8a292bdf30c).

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

#### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@DenisePeterson , completed: `2024/09/17`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@DenisePeterson , completed: `2024/09/17`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@DenisePeterson , completed: `2024/09/17`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) row as deprecated by pasting the related Porter issue URL in the "porterUrl" field and setting the value of the "ugrcStatus" field as "removed". Also update the "refreshCycle" field (@DenisePeterson , completed: `2024/09/17`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@DenisePeterson , completed: `2024/09/17`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@DenisePeterson , completed: `2024/09/23`)
    - [x] Unshare the item from its SGID group, which will remove it from the SGID on ArcGIS (@DenisePeterson , completed: `2024/09/23`)
- [x] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (@ZachBeck , completed: `2024/09/17`).

#### Hard Delete

**Target Date:** 2024/10/01

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@ZachBeck , completed: `2024/10/21`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@DenisePeterson , completed: `2024/10/04`).
- [x] Remove ArcGIS Online item: @DenisePeterson , completed: `2024/10/04`)
  - Manually delete the AGOL item
  - -OR-
  ~- Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),~
  - -OR-
  ~- Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.~
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (@stdavis, completed: `2024/00/00`)~
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) fields: "arcGisOnline", "openSgid", "openSgidTableName" (@DenisePeterson , completed: `2024/10/05`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (including `downloadMetadata.ts`) (@DenisePeterson , completed: `2024/10/11`)
- [x] Update `SGID.META.AGOLItems` table (@DenisePeterson , completed: `2024/09/23`)
  ~- cut and paste row to `AGOLItems_shelved` table if shelving (see below)~
  ~- set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL~
  ~- set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online~
~- [x] Delete Google Drive data ( , completed: `2024/00/00`)~
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis , completed: `2024/10/07`)
- [x] Remove data from forklift hashing and receiving (@stdavis , completed: `2024/10/07`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis , completed: `2024/10/07`)

#### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2024/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online with `shelved` or `static` in the `CATEGORY` field (name, completed: `2024/00/00`)~

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@steveoh on `2024/10/15`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/10/15`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/09/19`)

### Are there service dependencies

- [x] Are clients querying this data with the WebAPI? [This dashboard](https://lookerstudio.google.com/reporting/fbfcf1d5-e9c2-4b8a-94ae-9529d5d0bbef/page/p_7k74ao7wjd) may be helpful.
- [x] Notify Don Jackson (don.jackson1 at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/09/16`)
- [ ] Does any other application depend on this data?

#### Website references

- [x] [census places metadata reference](https://github.com/agrc/metadata-asset-tracking-tool/blob/7cd6da837de455589fbf290b256dd4d42f146e07/metadata/demographic/census_places_2020.md?plain=1#L21) (@miriamseely, completed: `2024/10/08`)
- [x] Website [boundary description](https://github.com/agrc/gis.utah.gov/blob/f207e826c510a1b424417bc5cd82728ae22226bc/src/pages/_partials/BoundaryDescription.astro#L14) used in these [product pages](https://github.com/search?q=repo%3Aagrc%2Fgis.utah.gov%20BoundaryDescription&type=code) (@DenisePeterson, completed: `2024/10/11`)
- [x] [You might also like link](https://gis.utah.gov/products/sgid/boundaries/municipal/) on the municipal boundary page (@DenisePeterson, completed: `2024/10/11`)

#### Other SGID data references

- [x] [UGRCodes](https://gis.utah.gov/blog/2021-04-26-introducing-ugrcodes/) reference metro townships with a suffix that also needs to update (@DenisePeterson, completed: `2024/10/11`)

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 352

| check | status |
| - | :-: |
| @DenisePeterson has completed **0** out of **14** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for category.internaltablename

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find category.internaltablename in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 352

| check | status |
| - | :-: |
| @DenisePeterson has completed **5** out of **14** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.metrotownships

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 352

| check | status |
| - | :-: |
| @DenisePeterson has completed **7** out of **14** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
This data does not need to be shelved as it does not appear to have historical relevance. Archives should have a copy if someone wants to download it for some reason. Does this seem accurate @gregbunce?

**Comment by gregbunce** [comment]
Yup, I agree, they can get it from archives.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 352

| check | status |
| - | :-: |
| @DenisePeterson has completed **12** out of **16** tasks | :no_entry: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @miriamseely has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.metrotownships

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by miriamseely** [comment]
I've removed the Metro Townships mention from the Census Places dataset. Let me know if there's anything else I can do to help!

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.metrotownships

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.metrotownships

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 352

| check | status |
| - | :-: |
| DenisePeterson has completed **15** out of **15** tasks | :+1: |
| ZachBeck has completed **2** out of **2** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| miriamseely has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.metrotownships

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by steveoh** [comment]
This looks complete, @DenisePeterson if you're happy with it please close this out.
