### ISSUE TITLE
Introduce Utah Voting Districts 2022-2032

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/porter#354]
## Summary

- **Application Name**: Utah Voting Districts 2022-2032
- **Application Urls**
  - Staging:
  - Production: https://utah.maps.arcgis.com/apps/instant/sidebar/index.html?appid=533ba1d728ad40d4bc189216c329766d
  - Short URL: https://s.utah.gov/utah-voting-districts

_A short summary of the application._
A simple application showing voting districts in Utah. Layers include Congressional, House, Senate, and School Board of Education districts. 

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

~- [ ] SOW or similar agreement (name, completed: `2024/00/00`)~
~- [ ] Add to [gis.utah.gov]([https://gis.utah.gov/developer/application](https://gis.utah.gov/solutions/for-government/application-portfolio-highlights/)) (name, completed: `2024/00/00`)~
~- [ ] Create Archer security diagram (name, completed: `2024/00/00`)~
   ~- Diagram URL:~
~- [ ] Add to Application Portfolio Management ("Business Applications" in ServiceNow) (nam,e, completed: `2024/00/00`)~
 ~ - Id:~
~- [ ] Create maintenance contract (name, completed: `2024/00/00`)~
~- [ ] Service Now task (name, completed: `2024/00/00`)~
  ~- Name:~
~- [ ] GitHub repo (name, completed: `2024/00/00`)~
   ~- Repo URL:~
- [x] Primary client contact (@DenisePeterson , completed: `2024/08/12`)
  - Name: Hayden Loftus 

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 354

| check | status |
| - | :-: |
| DenisePeterson has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **2** out of **2** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
