### ISSUE TITLE
Introduce Utah Homeowners Assistance Fund - UHAF

### ISSUE THREAD

**Issue by DenisePeterson** [agrc/porter#355]
## Summary

- **Application Name**: Utah Homeowners Assistance Fund - UHAF
- **Application Urls**
  - Staging:
  - Production: https://utah.maps.arcgis.com/apps/dashboards/2af128402650481eb1c18b025cd752d6

_A short summary of the application._
The Utah Homeowners Assistance Fund (UHAF) program is a federally funded housing assistance program for homeowners in Utah impacted by the COVID-19 pandemic. This dashboard shows homeowner demographics by zip code.

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

~- [ ] SOW or similar agreement (name, completed: `2024/00/00`)~
~- [ ] Add to [gis.utah.gov]([https://gis.utah.gov/developer/application](https://gis.utah.gov/solutions/for-government/application-portfolio-highlights/)) (name, completed: `2024/00/00`)~
~- [ ] Create Archer security diagram (name, completed: `2024/00/00`)~
  ~- Diagram URL:~
~- [ ] Add to Application Portfolio Management ("Business Applications" in ServiceNow) (nam,e, completed: `2024/00/00`)~
  ~- Id:~
~- [ ] Create maintenance contract (name, completed: `2024/00/00`)~
~- [ ] Service Now task (name, completed: `2024/00/00`)~
  ~- Name:~
~- [ ] GitHub repo (name, completed: `2024/00/00`)~
  ~- Repo URL:~
- [x] Primary client contact (@DenisePeterson , completed: `2024/02/14`)
  - Name: Eleni Alatini

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 355

| check | status |
| - | :-: |
| DenisePeterson has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **2** out of **2** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
