### ISSUE TITLE
Remove DWQAssessmentUnits from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#356]
## Summary

- **Internal Dataset Name**: Environment.DWQAssessmentUnits
- **External Dataset Name**: Utah DWQ Assessment Units
- **ArcGIS Online Url**: https://www.arcgis.com/home/item.html?id=0f39afb3b29d4c0a8abf7c46ed2e0354

This is an out-of-date layer that was never cleaned up.

Comments from Mark Stanger on 10/1:
>[This layer] is very out-of-date. I recognize assessment units, or the lack thereof, as being several years old. For example, the Great Salt Lake was one assessment unit (AU) but years ago was split into four AUs: Gunnison Bay, Gilbert Bay, Bear River Bay and Farmington Bay. 
Another example are the AUs in the Price River area that have an upper elevation boundary of 7200 or 7500 feet, such as Lower Grassy Trail Creek (UT14060007-012). I cannot remember if those specific boundaries were ever finalized/approved. 
I'm still looking for the source data that matches Scott's reference, but I am certain it is no longer applicable.

### Migration Guide

This dataset has been replaced by [Utah Assessed Waters](https://www.arcgis.com/home/item.html?id=0540a8a627a44e9f91e0f614f49efab1).

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

#### Soft Delete

_The purpose of the soft delete is to ensure that all of our users and applications have gracefully migrated off of the dataset. Soft deletes will remain in effect for 14 days. During this time, we will have the ability to restore the dataset to its original SGID offering(s). After these 14 days, the item is then ready for a hard delete._

Note: If this dataset is being replaced, then wait until the new data is publicly available before completing these steps:

- [x] Append "(Mature Support)" to the end of the item title in the `SGID.META.AGOLItems` table (@stdavis, completed: `2024/10/07`)
- [x] Remove all tags other than "Deprecated" in the SDE metadata (@stdavis, completed: `2024/10/07`)
- [x] Add note to SDE description noting when layer will be deleted and any replacement layer (@stdavis, completed: `2024/10/07`)
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) row as deprecated by pasting the related Porter issue URL in the "porterUrl" field and setting the value of the "ugrcStatus" field as "removed". Also update the "refreshCycle" field (@stdavis, completed: `2024/10/07`)
- [x] Change `Authoritative` field to `d` in `SGID.META.AGOLItems` to automatically set the `Deprecated` AGOL flag. Allow the `d` to persist through one run of [Auditor](https://github.com/agrc/auditor) - currently, Auditor runs daily at 5:00am (@stdavis, completed: `2024/10/07`)
  - After at least one successful run of Auditor:
    - [x] Remove the row from the `SGID.META.AGOLItems` table. This will trigger the removal of this item in Open SGID (@stdavis, completed: `2024/10/21`)
    - [x] Unshare the item from its SGID group, which will remove it from the SGID on ArcGIS (@stdavis, completed: `2024/10/21`)
~- [ ] Check if this layer in the base maps. If so, work with Zach to develop a path forward before you proceed with a Hard Delete (name, completed: `2024/00/00`).~

#### Hard Delete

**Target Date:** 2024/10/21

_Hard deletes are final. It is recommended to complete the soft delete process before moving on to these steps. If you decide to skip the soft delete, note that you will need to incorporate some of those steps here._

- [x] Manually remove data from the Internal SGID (@ZachBeck, completed: `2024/12/16`)
  - [x] Deprecated database layers should be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [internal_db_sgid_layers](https://drive.google.com/drive/u/0/folders/10Fk8NI2UpEUnAbgvhjlN18pyvSFDWyIq) (@ZachBeck, completed: `2024/12/16`).
- [x] Remove ArcGIS Online item: (@ZachBeck, completed: `2024/12/16`)
  - Manually delete the AGOL item
  - -OR-
  - Unshare by changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to something other than an Item ID and manually changing the sharing settings (remove the item from all SGID groups, remove Public sharing),
  - -OR-
  - Shelve the data by copying the row from `SGID.META.AGOLItems` to the `AGOLItems_shelved` table in AGOL and changing the `AGOL_ITEM_ID` field in `SGID.META.AGOLItems` to `shelved` or some other note.
  - Deprecated AGOL items can be backed up on Google Drive > AGRC Projects > SGID > deprecated layers > [agol_sgid_layers](https://drive.google.com/drive/u/0/folders/1xwSxiDNIH-9Hhmn6I7NfKBhm4SbYonX5).
~- [ ] Remove Farm from AGOL connection (name, completed: `2024/00/00`)~
- [x] Update the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) fields: "arcGisOnline", "openSgid", "openSgidTableName"(@ZachBeck, completed: `2024/12/16`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (including `downloadMetadata.ts`) (@stdavis, completed: `2024/10/28`)
~- [ ] Update `SGID.META.AGOLItems` table (name, completed: `2024/00/00`)~
  - cut and paste row to `AGOLItems_shelved` table if shelving (see below)
  - set the `AGOL_ITEM_ID` field to `hosted by <agency>` for Farm from AGOL
  - set the `AGOL_ITEM_ID` field to `exclude from AGOL` to not publish to ArcGIS Online
- [x] Delete Google Drive data (@ZachBeck, completed: `2024/12/16`)
- [x] Remove row from `SGID.META.ChangeDetection` (@stdavis, completed: `2024/10/28`)
- [x] Remove data from forklift hashing and receiving (@stdavis, completed: `2024/10/28`)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (@stdavis, completed: `2024/10/28`)

#### Shelve/Static

_Choose one based on situation._

~- [ ] Upload to `UtahAGRC/AGRC_Shelved` folder in AGOL (New shelved item not already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Move existing AGOL item to `AGRC_Shelved` AGOL folder (shelving an item already in AGOL) (name, completed: `2024/00/00`)~
~- [ ] Upload to appropriate `UtahAGRC/{SGID Category}` folder in AGOL (for `static` datasets) (name, completed: `2024/00/00`)~

_Add record to table._

~- [ ] Add record to `AGOLItems_shelved` [table](https://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) in ArcGIS Online with `shelved` or `static` in the `CATEGORY` field (name, completed: `2024/00/00`)~

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Remove data from Open SGID (@stdavis on `2024/10/28`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2024/10/28`)
- [x] Auditor sets appropriate `shelved`/`static`/`Deprecated` information (@jacobdadams on `2024/10/08`)

### Are there service dependencies

- [x] Are clients querying this data with the WebAPI? [This dashboard](https://lookerstudio.google.com/reporting/fbfcf1d5-e9c2-4b8a-94ae-9529d5d0bbef/page/p_7k74ao7wjd) may be helpful.
- [x] Notify Don Jackson (don.jackson1 at motorolasolutions.com) if the data is in the Next-Generation 911 Motorola Aware Map? (@gregbunce on `2024/00/00`)
- [x] Does any other application depend on this data?
  - [x] The DEQ Tank risk took relies on this data https://github.com/agrc/DEQ-TankRisk/blob/main/src/tank_risk_tool.pyt#L694 (@steveoh on `2024/11/08`)

### Notification

- [x] Twitter (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@ZachBeck)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

I need some help with the shelved tasks. I'm not sure how those are supposed to be done.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| @stdavis has completed **0** out of **12** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| @stdavis has completed **5** out of **12** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| @stdavis has completed **5** out of **12** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| @stdavis has completed **7** out of **12** tasks | :no_entry: |
| @steveoh has completed **0** out of **3** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| steveoh has completed **3** out of **3** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by steveoh** [comment]
Richard Saathoff has brought to our attention that the deq tank risk tool relies on this data which is no longer available in the open sgid. He's going to run with the mature support data in agol for this months report.

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by ZachBeck** [comment]
@stdavis does this layer need to be shelved or removed entirely?

**Comment by stdavis** [comment]
> does this layer need to be shelved or removed entirely?

It's up to the data team. I don't have any preference. I don't know anything more about it other than what I've put in this issue.

**Comment by ZachBeck** [comment]
Ok, I'll remove it and keep it consistent with the other layers in this set of porter issues.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |

**Comment by stdavis** [comment]
@ZachBeck It looks like you mark the task to assign data team tasks as complete but there are a few that seem like data team tasks without names on them. Are you expecting those to be done by our team?

**Comment by ZachBeck** [comment]
No, just getting sloppy in my old age. I'll take care of them.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 356

| check | status |
| - | :-: |
| stdavis has completed **12** out of **12** tasks | :+1: |
| ZachBeck has completed **5** out of **5** tasks | :+1: |
| steveoh has completed **4** out of **4** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for environment.DWQAssessmentUnits

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship |  |
| - porter issue link | :+1: |
