### ISSUE TITLE
Old AGOL Items: Zach

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#36]
I've found the following items in AGOL that are owned by you that look old, unused, and/or broken. Please take a look at them and see if they can be deprecated/deleted. If they are part of the SGID or some other major project, consider opening a new issue using the full deprecation checklist/process.

I don't mean to call anyone out for their old data. I just wanted to have a place to track these things as I found them as part of the HTTP/HTTPS update process.

This will be a living issue while we track down http links. The list may be edited from time to time.

~[ ] Utah ILEC Telephone and DSL Exchange Boundaries and Territories (Web Map): http://utah.maps.arcgis.com/home/item.html?id=cea1805ebeac4072a270192d0285b12f~
~[ ] July 2015: BLM Comm Sites (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=8ec0737321f24e3c9e0b6f0c1731ce09 (and webmap: http://utah.maps.arcgis.com/home/item.html?id=4e4d355f50e94728b7c0b69470314674)~
~[ ] October 2016 Map of the Month: State Facilities (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=7723c9bb92e9442b8794a6bdad73d01f (and webmap: http://utah.maps.arcgis.com/home/item.html?id=7824facee8b2452a9d64ad3baac2a6ca)~
~[ ] Active DABC Licensees (Web Mapping Appliction): http://utah.maps.arcgis.com/home/item.html?id=aeff272ef1fe4e9892f9ffbd29715867~
~[ ] GOED Broadband Planning Web App (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=60ef82117a594d858332e2624eabff55~
~[ ] Interactive Residential Map (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=d250e652c876464eaa547d17e783bd92~
~ [ ] Business Fiber Service (Web Mapping Application): http://utah.maps.arcgis.com/home/item.html?id=50c5a1727d9a432fba003a80048d4486 (This and the previous item appear to be linked to broadband stuff, but only have a couple dozen views each)~
~[ ] Utah Ski Areas (Web Map): (not publicly shared, search by name)~
~[ ] UT Broadband Verification Map August Fall 2013 (Web Map): http://utah.maps.arcgis.com/home/item.html?id=6e926e19fc674b45a8b5edbdd2fcfa7b~
~[ ] UT Broadband Address Pnt Verification Map August Fall 2013-Copy (Web Map):~ ~http://utah.maps.arcgis.com/home/item.html?id=d702dcd19f034044b78069f0e7464d6a~
~[ ] sbi all test (Web Map): (not publicly shared, search by name)~
~[ ] Mission Bay Reserve (geotagged) (Web Map): (not publicly shared, search by name)~
~[ ] Hazard_Faults_Quaternary (Map Image layer): (not publicly shared, search by name)~
~[ ] SBI template (Web Mapping Application): (not publicly shared, search by name)~
~[ ] test (Web Mapping Application): (not publicly shared, search by name)~

**Comment by ZachBeck** [comment]
DABC app can be deleted. That was a creation to try and score some points with the DABC, which doesn't seemed to have worked.

**Comment by ZachBeck** [comment]
All my junk is gone now.
