### ISSUE TITLE
Add Great Salt Lake Sentinel Landscape boundary from Utah Dept of Veterans Affairs

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#366]
## Summary

- **Proposed Readable Name**: Utah GSL Sentinel Landscape Boundary 
- **Proposed Internal Dataset Name**: GSL_SentinelLandscapeBoundary
- **Proposed External Dataset Name**: gsl_sentinel_landscape_boundary 
- **Proposed Data Category**: BOUNDARIES
- **Data Description**: Great Salt Lake sentinel landscape boundary
- **Source Agency/Entity**: Utah Dept of Veterans Affairs GSL Sentinel Landscape
- **Contact**: Marisa Weinberg
- **Update Frequency**: Static

This dataset represents a federally established boundary that shows the area of the Great Salt Lake Sentinel Landscape. The boundary was created by the Great Salt Lake Sentinel Landscape Coordinator with input from multiple federal agencies, state and local governments, and non-governmental organizations.

https://sentinellandscapes.org/landscapes/great-salt-lake/

### The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

### The data is of high quality

- [x] Sweeper checks have run and passed (@ZachBeck  on `2024/11/20`)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@ZachBeck  on `2024/11/20`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@ZachBeck  on `2024/11/20`)

### Where is the data source

_Choose one._

- [x] Internal SGID
~- [ ] Farm from AGOL ([agol item url](??))~

### Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the [Internal SGID](https://stackoverflow.com/c/ugrc/questions/109) (@ZachBeck , completed: `2024/11/21`)
~- [ ] Configure forklift for Farm from AGOL (@stdavis , completed: `2024/00/00`)~
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck, completed: `2024/12/05`)
- [x] Add a [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) record (@ZachBeck , completed: `2024/11/21`)
- [x] Complete a `SGID.META.AGOLItems` record (@ZachBeck , completed: `2024/11/21`)
  - `AGOL_ITEM_ID` will be populated by Forklift after it publishes the new AGOL item.
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2024/00/00`)~
~- [ ] Data is assigned to a record series with archives (@leault, completed: `2024/00/00`)~

### :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2024/12/04`)
- [x] ArcGIS Online via forklift (@stdavis on `2024/12/02`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2024/11/23`)
- [x] [SGID on ArcGIS](https://opendata.gis.utah.gov) (@ZachBeck on `2024/12/02`)
- [x] [gis.utah.gov](https://gis.utah.gov/products/sgid/categories/) data pages (@ZachBeck  on `2024/12/09`)
- [x] [sgid-index](https://gis.utah.gov/products/sgid/sgid-index/) (@steveoh on `2024/12/16`)

### Notification

- [x] X (@steveoh)

### Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@ZachBeck)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 366

| check | status |
| - | :-: |
| @ZachBeck has completed **7** out of **8** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for category.internaltablename

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find category.internaltablename in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 366

| check | status |
| - | :-: |
| @ZachBeck has completed **7** out of **8** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.gsl_sentinel_landscape_boundary

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find boundaries.gsl_sentinel_landscape_boundary in the worksheet |

**Comment by steveoh** [comment]
@ZachBeck, Since the dataset is static, do we know the year it was collected or created and should that be used in the data name? e.g.  boundaries.gsl_sentinel_landscape_boundary_2024?

**Comment by ZachBeck** [comment]
I would vote to put the year it was created in the metadata and keep the year off the name.

**Comment by steveoh** [comment]
> ## Dates in Dataset Names
> We will include dates in the names of datasets in the census, political, or tax categories to identify datasets where the most current data may not reflect the current calendar year, such as the latest Census demographic data.
> 
> For all other categories, dates should only be used for datasets that are no longer effective/active or are soon-to-be effective/active. This implies that the most current and relevant data contains no date suffix. Historical or future data should contain a date suffix to help identification at a glance.
> 
> The best way to identify a dataset's vintage or time frame is to view the metadata on its [data page](https://gis.utah.gov/products/sgid/categories/).

I think our policy validates your vote.

**Comment by steveoh** [comment]
@ZachBeck in the future, please mark the SGID index sheet column row `indexStatus` as draft until the data page is published and all the fields are complete. Otherwise a partial/invalid record is displayed on the website.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 366

| check | status |
| - | :-: |
| @ZachBeck has completed **8** out of **9** tasks | :no_entry: |
| @steveoh has completed **3** out of **5** tasks | :no_entry: |
| stdavis has completed **1** out of **1** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for boundaries.GSL_SentinelLandscapeBoundary

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - displayName | :+1: |
| - description | :+1: |
| - justification | :+1: |
| - category | :+1: |
| - productType | :+1: |
| - ugrcSteward | :+1: |
| - dataContactName | :+1: |
| - dataContactEmail | :+1: |
