### ISSUE TITLE
Old AGOL Items: Steve

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#38]
I've found the following items in AGOL that are owned by you that look old, unused, and/or broken. Please take a look at them and see if they can be deprecated/deleted. If they are part of the SGID or some other major project, consider opening a new issue using the full deprecation checklist/process.

I don't mean to call anyone out for their old data. I just wanted to have a place to track these things as I found them as part of the HTTP/HTTPS update process.

This will be a living issue while we track down http links. The list may be edited from time to time.

- [ ] Service Proxy (Application): (not publicly shared, search by name)

**Comment by steveoh** [comment]
I deleted everything from my agol content. I should be good now.
