### ISSUE TITLE
add checkbox(ex) to verify that agol validator has run

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#39]
We might need to add another checkbox to verify that @jacobdadams script runs and updates the agol items summary, description, etc. Thoughts?

_Originally posted by @steveoh in https://github.com/agrc/porter/issues/31#issuecomment-648962084_

**Comment by jacobdadams** [comment]
I'm in favor of this. `agol-validator` will be run nightly with forklift, and verifying the data should be a simple visual check of the AGOL item page.

For reference, `agol-validator` currently checks and modifies the following:

- Tags (removes 'Utah' and any other tags in the item title, adds 'AGRC', 'SGID', and category tags, Proper Cases or CAPS tags)
- Checks title against meta table
- Checks folder and sharing groups against SGID group
- Enables downloads in all formats
- Enables delete protection
- Tries to update AGOL metadata from SDE metadata
- Adds static/shelved note to description if applicable
- Adds an AGRC-branded, category-specific thumbnail for SGID items
- Sets authoritative status against meta table.

@steveoh , does "help wanted" mean you're asking for input, or that you're asking for someone to do the PR? I'd be happy to do the PR if that's the case.

**Comment by steveoh** [comment]
I use the tag on issues that should be simple for someone to pick up and contribute successfully. The issues are typically ones where deep knowledge of the project isn't required for the contributor to be successful. 

I am not implying that I don't want to do the task but rather that I am open to other people doing it before I get to it.

**Comment by steveoh** [comment]
I should say if you want to pick it up @jacobdadams, assign yourself to the issue so we do not duplicate work.
