### ISSUE TITLE
Remove Trails from SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#41]
# Summary

We are deprecating this layer and replacing it with a new and improved version called "TrailsAndPathways". I will put in a separate issue to add that layer.

# Triage

- [x] Data Team Triage (@gregbunce )
- [x] Dev Team Triage (@stdavis)
- [ ] ~Cadastre Team Triage~

# Remove data from the following areas

- [x] ArcGIS Online (@jacobdadams)
- [x] Internal SGID (@gregbunce on 7/15/2020)
- [x] SGID10 (@gregbunce on 7/15/2020)
- [x] Open SGID (@steveoh)
~- [ ] Google Drive~ (I think I'll hold off on this for now. this source provides access to older versions of the data. might be worth holding on to all sgid google drive data for future analysis.  just thinking out loud).
- [x] Open data (@jacobdadams)
~- [ ] Mapserv (assigned to)~
- [x] Backseat Driver (@stdavis)

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL~ (new layer contains all features in this layer)
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder~ (new layer contains all features in this layer)
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets)~ (@jacobdadams)

# Update information in the following areas

- [x] gis.utah.gov data pages (@gregbunce )
- [x] Stewardship doc and sgid-index (@gregbunce )
- [x] `SGID.META.AGOLItems` (@gregbunce on 7/15/2020)
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL)~
- [x] `SGID.META.ChangeDetection` (@stdavis)

# Is there a website?

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
or
~- [ ] Replace app with a static page with information (assigned to)~
or
~- [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

~- [ ] Stop (assigned to)~
~- [ ] Delete (assigned to)~

# Is there a forklift pallet?

~- [ ] Remove repo (assigned to)~
- [x] Remove stale data from forklift hashing and receiving (@stdavis)

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh )
- [x] Validate that AGRC or applications widgets do not reference it (@stdavis)

# Notification

- [x] Blog post (@gregbunce )
- [x] Twitter (@steveoh)
  - [x] Intent
  - [x] Completed

**Comment by gregbunce** [comment]
I can handle a bunch of this, but I will need assistance removing this layer from automated processes such as swapper, and the process of updating it in AGOL and Open SGID.

**Comment by rkelson** [comment]
what does the Cadastre team need to do to triage?

**Comment by gregbunce** [comment]
maybe when something from PLSS or TURN is added or removed from AGRC data or services.  ?

**Comment by jacobdadams** [comment]
> what does the Cadastre team need to do to triage?

I think that's in the issue template just to make sure the cadastre folks have a chance to see the request and be part of the conversation if needed. I can imagine that for many items there won't be much to do from the cadastre viewpoint.

**Comment by rkelson** [comment]
I am not aware of anyway this trails change would affect the cadastre team. Just let me know what you would like the cadastre team to do; I took a look at the Porter readme but still do not completely understand the process and protocols. I gather the Triage check boxes are who it assigned to and no check in the Cadastre triage box denotes the cadastre team does not need to do anything? And if I were to check the box it would denote the cadastre team has some action items to address?

**Comment by jacobdadams** [comment]
I think the checkboxes in the triage section means that someone from that team has looked it over and noted any requirements and assigned any tasks relevant to that team. Thus, if cadastre (or any other team on any other item) doesn't see anything that needs to be done, they just simply check it off (and if they do see something, they assign one of the items to someone or makes a note of it in the comments field). That way we know that they've looked it over and won't be taken by surprise when something changes.

**Comment by rkelson** [comment]
sounds good

**Comment by rkelson** [comment]
I wonder if @eneemann uses this dataset in his 911 dispatch stuff. Otherwise I think there are not any issues from the cadastre corner.

**Comment by eneemann** [comment]
I don't use the Trails data for dispatch, so I think Cadastre is clear of any necessary actions for this one.  I went ahead and checked off the box to indicate our review has been completed.

**Comment by steveoh** [comment]
Yah I think the template or the instructions need to be more clear on when to check boxes. 

We may need a separation between what is done and what needs to be done like with the addition template. 

Greg checked boxes that were other folks responsibility but that is not super intuitive.

**Comment by gregbunce** [comment]
i'm going to let this sit until it's replacement layer [Utah Trails and Pathways](https://github.com/agrc/porter/issues/42) has propogted up to AGOL/OpenData and Open SGID.  also, i'm out next week - if anyone is feeling ambitious, have at it, otherwise I'll be on it the week of July 6th.

**Comment by steveoh** [comment]
/remind me to check on this 7/6/2020

**Comment by gregbunce** [comment]
Okay, i'm no longer blocking progress on this issue.  feel free to tag me when the last item has been resolved and I can close the issue (or you can just close the issue if it's easier).  thanks for all the assistance on this.

**Comment by jacobdadams** [comment]
Just to verify, @gregbunce , we're not shelving this. Correct?

**Comment by jacobdadams** [comment]
I wonder if, rather than delete the AGOL item, we mark it as deprecated, remove it from the SGID group (which pulls it out of Open Data), and then send another twitter message that it will be completely deleted in 7/14/30 days. That removes the confusion but gives people time to update their maps/apps.

**Comment by stdavis** [comment]
I completed the dev team triage and assigned a few tasks.

**Comment by stdavis** [comment]
I removed the data from change detection and forklift-related data. I also unassigned those who do not have tasks assigned to them.

**Comment by steveoh** [comment]
Thanks scott, I'm done. @jacobdadams when you're finished you can close this.

**Comment by gregbunce** [comment]
sorry, @jacobdadams i didn't get notified for your question above.  yup, correct - i don't this we need to shelve it.  but, i also like you're idea of leaving in AGOL for a month, but now exposed to Open Data in case anyone is using.  though, they'll eventually have to find the new layer.

**Comment by agrc-conductor** [comment]
## conductor results

internal sgid: :+1:
sgid10: :+1:
meta table: :+1:
open sgid: :+1:
open data: :+1:
arcgis online: :+1:
stewardship: Deprecation issue link: :+1:

**Comment by jacobdadams** [comment]
The AGOL item has been marked as deprecated and unshared with the Recreation group (thus pulling it out of open data). 

We'll change the sharing from Public to none on August 20th, which will effectively delete it but keep it around for a bit in case there is weeping, wailing, and gnashing of teeth.

**Comment by gregbunce** [comment]
great, thanks!  should we close this issue?

**Comment by jacobdadams** [comment]
I say we leave it open until the 20th. I'm trying to figure out how to use the reminder bot right now...

**Comment by agrc-conductor** [comment]
## conductor results

| check | status |
| -- | -- |
| internal sgid | :+1: |
| sgid10 | :+1: |
| meta table | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship | Deprecation issue link: :+1: |

**Comment by jacobdadams** [comment]
/remind me to unshare the old trails layer on 8/20/2020

**Comment by jacobdadams** [comment]
Ok, the old trails layer has been unshared. I've edited the description to note it was superseded by the Trails and Pathways layer. 

Are we ok to close this issue now? I figure we'll delete the entire AGOL item after we're sure we don't need to re-enable it for anyone.

**Comment by stdavis** [comment]
I think that I would leave this issue open until the item has actually been removed from AGOL. Then you can check the last checkbox and close it.

**Comment by agrc-conductor** [comment]
## conductor results

| check | status |
| - | :-: |
| internal sgid | :+1: |
| sgid10 | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by gregbunce** [comment]
/ remind @jacobdadams on August 28, 2020

**Comment by jacobdadams** [comment]
/remind me to nuke the layer on 8/28/2020.

**Comment by agrc-conductor** [comment]
## conductor results for Recreation.Trails

| check | status |
| - | :-: |
| internal sgid | :+1: |
| sgid10 | :+1: |
| meta table | :+1: |
| stewardship |  |
| - deprecation issue link | :+1: |

**Comment by steveoh** [comment]
@jacobdadams please close this issue when you have removed the layer.

**Comment by jacobdadams** [comment]
Roasty toasty nuked.
