### ISSUE TITLE
Add TrailsAndPathways to SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#42]
# Summary

- **Proposed Dataset Name**: TrailsAndPathways
- **Proposed ISO Category**: Recreation
- **Data Description**: Utah Trails and Pathways
- **Source Agency/Entity**: AGRC
- **Contact**: Greg Bunce
- **Update Frequency**: Monthly

# Triage

- [x] Data Team Triage Complete
- [ ] Dev Team Triage Complete (assigned to)
- [ ] Cadastre Team Triage Complete

# We are introducing data

The data was or will be added on `2020/06/25` to the following areas

- [x] Internal SGID
- ~[ ] SGID10~
- ~[ ] ArcGIS Online~

# The data is high quality

- [x] Sweeper checks have run and passed
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] ArcGIS Online
- [x] SGID10
- [x] Open SGID
- [x] Open data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] Stewardship doc and sgid-index
- [x] `SGID.META.AGOLItems`

# We have verified the data is live 

- [x] ArcGIS Online (@ZachBeck  on `7/2/2020`)
- [x] Internal SGID (@gregbunce on `6/25/2020`)
- [x] SGID10 (@gregbunce  on `6/26/2020`)
- [x] Open SGID (@steveoh on `6/28/2020`)
- [x] Open data (@jacobdadams on `7/1/2020`)
- [x] gis.utah.gov data pages (@gregbunce on `6/26/2020`)
- [x] Stewardship doc and sgid-index (@gregbunce on `6/25/2020`)
- [x] `SGID.META.AGOLItems` (@gregbunce on `6/25/2020`)
- [x] `SGID.META.ChangeDetection` (@steveoh on `6/28/2020`)
- [x] `agol_validator` checks (@jacobdadams on `7/1/2020`)

# Notification

- [x] Blog post (@gregbunce )
- [ ] Twitter (@steveoh)

**Comment by ZachBeck** [comment]
How set in stone is the name, how about TrailsAndPaths instead?

**Comment by gregbunce** [comment]
we could to that.  I was thinking it will read on the data page and AGOL/OpenData as "Utah Trails and Pathways"  or Utah Trails and Paths".  Do you want to see the feature class named "TrailsAndPaths"?

**Comment by ZachBeck** [comment]
I like TrailsAndPathways as the feature class name and Utah Trails and Pathways for AGOL/OpenData

**Comment by steveoh** [comment]
Nitpick: you're not adding data to all three places. You will only add it to the internal sgid. Our tools will propagate those out. I think you only internal sgid should be checked. 

That might be confusing but we added those three boxes incase you wanted to add something directly to those areas skipping some of the automation.

**Comment by gregbunce** [comment]
thanks for the nitpicking.  ok, that's great!  I didn't know if the propagation tools were for data already in place.  so, thanks for clarifying.  that makes my job much easier.

**Comment by steveoh** [comment]
Yes so this should be helpful for everyone.

Data in the internal sgid will be added to the sgid with swapper

If there is a record in the agol items table it will be added to

- the open sgid with cloudb
- arcgis online with forklift
- open data with the agol validator

Did I miss anything?

**Comment by nathankota** [comment]
very helpful...a possible addition to the readme?

> Yes so this should be helpful for everyone.
> 
> Data in the internal sgid will be added to the sgid10 with swapper
> 
> If there is a record in the agol items table it will be added to
> 
> * the open sgid with cloudb
> * arcgis online with forklift
> * open data with the agol validator
> 
> Did I miss anything?

**Comment by gregbunce** [comment]
thanks again.  yeah, my missing link was for newly added items - and how they propagate, so thanks!  when i added the item to the META table, should i leave the item id blank until it gets one assigned?

**Comment by steveoh** [comment]
> when i added the item to the META table, should i leave the item id blank until it gets one assigned?

yes

**Comment by gregbunce** [comment]
this layer hasn't propagated to AGOL/OpenData or Open SGID yet and I'm out of the office next week.  @ZachBeck any chance you could monitor that and check the verified boxes (above) for the remaining sources? (if yes = thank you!! & if no = you're mean).  Just kidding.

**Comment by gregbunce** [comment]
the related blog post is [pr 1433](https://github.com/agrc/gis.utah.gov/pull/1433)

**Comment by ZachBeck** [comment]
It looks like this has made it's way to the Recreation folder but hasn't been shared out to the Recreation group yet. Are there any plans to deprecate the old trails data?

**Comment by jacobdadams** [comment]
I'm waiting to get the Monday morning forklift email, then I'll run the
validator that will share it out to the proper groups.

**Comment by gregbunce** [comment]
Yeah, there's an issue in to deprecate it.

**Comment by steveoh** [comment]
**notice**: when you add the website url to the steward ship tab, it needs to contain all parts of the url. greg used the implied path `data/recreation/trails` when it needs to be `data/recreation/trails/index.html`

**Comment by gregbunce** [comment]
Thanks for the note!

**Comment by steveoh** [comment]
@jacobdadams was this item validated in agol and shared properly? We should be able to wrap up this today if that is the case.

**Comment by jacobdadams** [comment]
Sorry, I got pulled away with some Covid stuff. Yes, it was. I've verified it's shared to the proper groups and available in opendata.

I left the ArcGIS Online box unchecked because it doesn't have a summary, description, or terms of use. @ZachBeck, do we have that info for this dataset?

**Comment by ZachBeck** [comment]
It has metadata in sde. That doesn't come across when the feature layer is created? I can update it manually if you want.

**Comment by jacobdadams** [comment]
It should have... let me look into it. Do we know for certain the metadata
was in the SDE before forklift added it to AGOL? (even still,
agol_validator should have grabbed it too... I need to investigate)

**Comment by ZachBeck** [comment]
I'm pretty sure it was there on Monday.

**Comment by jacobdadams** [comment]
Ok, after tracking it down, I think the problem with the metadata is that the SDE metadata is far longer than the ArcGIS API supports uploading (167,418 chars actual, max 32,767 characters supported). It looks like the vast majority of this is in the "lineage" item, tracking all the Geoprocessing tasks that have happened back to 2017. 

@gregbunce, do you have any problems blowing away all this old metadata? This will allow any updates to the description, etc to propagate from the SDE to AGOL.

**Comment by steveoh** [comment]
> @gregbunce, do you have any problems blowing away all this old metadata? This will allow any updates to the description, etc to propagate from the SDE to AGOL.

This should be a scheduled event. this will continue to grow and be a reoccurring issue.

**Comment by gregbunce** [comment]
Yes, please blow it away.  Thanks!

**Comment by gregbunce** [comment]
thanks everyone for picking up my slack on this last week.  it looks good.  it like the only remaining item it getting the metadata from Internal DB to AGOL. right?  @jacobdadams is there anything i need to do?

**Comment by jacobdadams** [comment]
No, I just need to trim up the metadata. I'm already running the validator
for this week's run, but I can trim the metadata and transfer it to AGOL
tomorrow.

**Comment by gregbunce** [comment]
great, thanks again!  no rush.

**Comment by jacobdadams** [comment]
Ok, most of the metadata has come through. The use limitations may be a little rough, but the rest of it should be there (except for the GP history, which should have been blown away).

**Comment by gregbunce** [comment]
thanks, jake.  it looks good.  from my angle, i think we can close this issue.  @steveoh what's the process to close this?

**Comment by steveoh** [comment]
i think hit the button when you are confident

**Comment by gregbunce** [comment]
i see the 'Close issue' button.  but, i want to make sure we're all in agreeance.

**Comment by gregbunce** [comment]
i'm signing off on this one and closing it.
