### ISSUE TITLE
Deprecate Utah Water Chemistry

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#45]
# Summary

UGS has decided to deprecate the [Utah Water Chemistry Database](https://geology.utah.gov/apps/waterchem/). There is a forklift process to sling some data for the application, but I am not sure if there are any associated SGID data sets. The application lives on a UGS server and I will coordinate with them so they can time their deprecation strategy.

# Triage

- [ ] Data Team Triage (@ZachBeck)
- [x] Dev Team Triage (@stdavis )
- [ ] Cadastre Team Triage

# Remove data from the following areas

~- [ ] ArcGIS Online (assigned to)~
~- [ ] Internal SGID (assigned to)~
~- [ ] SGID10 (assigned to)~
~- [ ] Open SGID (assigned to)~
~- [ ] Google Drive (assigned to)~
~- [ ] Open data (assigned to)~
~- [ ] Mapserv (assigned to)~
- Retire SQL Server databases. We should probably confirm with Paul Inkenbrandt before doing this. (@nathankota)
	- [ ] Prod: `SERVER=ugswaterchemistry.agrc.utah.gov;DATABASE=UGSWaterChemistry`
	- [ ] Test: `SERVER=itdb112sp.dts.utah.gov\mspd14;DATABASE=UGSWaterChemistry`

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

~- [ ] gis.utah.gov data pages (assigned to)~
~- [ ] Stewardship doc and sgid-index (assigned to)~
~- [ ] `SGID.META.AGOLItems` (assigned to)~
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
~- [ ] `SGID.META.ChangeDetection` (assigned to)~

# Is there a website?

- [x] Archive source code repository (@stdavis)
	- https://github.com/agrc/ugs-db
	- https://github.com/agrc/ugs-chemistry
~- [ ] Remove from the web server (assigned to)~

# Is there a map service?

~- [ ] Stop (assigned to)~
~- [ ] Delete (assigned to)~

# Is there a forklift pallet?

- [x] Remove repo (@stdavis)
- [x] Remove stale data from forklift hashing and receiving (@stdavis)

# Are there service dependencies?

~- [ ] Validate that the web api does not query it (assigned to)~
~- [ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

~- [ ] Blog post (assigned to)~
~- [ ] Twitter (@steveoh)~
  ~- [ ] Intent~
  ~- [ ] Completed~

**Comment by stdavis** [comment]
This app is hosted completely on UGS servers so we don't need to coordinate anything with them.

I believe that all we need to do is archive the repos and remove it from forklift. I've updated the description for this issue.

**Comment by stdavis** [comment]
I added a task for retiring the SQL server databases associated with this project. We should probably check with Paul before we trash them to see if he wants to archive the data somewhere. @nathankota Do you want to check with him?

**Comment by nathankota** [comment]
/remind me to check in with Paul if I haven't heard from him on July 9th

**Comment by nathankota** [comment]
Paul:

> Yes, that would be great. Is there Google Folder or network drive that you could back it up to so I can archive a copy for myself?

@stdavis @MichaelAGRC could we put a copy in the `agrc_public_share` for him to retrieve?

**Comment by stdavis** [comment]
I sent an email to dbase requesting the backup.

**Comment by nathankota** [comment]
any response from dbase yet?

**Comment by stdavis** [comment]
I pinged them again on it. Thanks for the reminder.

**Comment by stdavis** [comment]
I guess that I had to fill out a SN form. I do so: REQ0093762

**Comment by nathankota** [comment]
/remind me to check on REQ0093762 on July 20

**Comment by nathankota** [comment]
The reminder bot worked! The request is hung up on Paul Inkenbrandt's approval. I dinged him.

**Comment by nathankota** [comment]
/remind me to check in with Paul about approval of REQ0093762 on July 22

**Comment by nathankota** [comment]
RITM0124562 approved by Paul and sent to Wade Kloos and DNR Security

/remind me to check on RITM0124562 on July 27

**Comment by nathankota** [comment]
IChing:

> Database has been taken offline. It will take few days to delete permanently.

/remind me to confirm on August 12 at 8:30 a.m.

**Comment by nathankota** [comment]
Dbase deleted UGSWaterChemistry db from itdb112sp and itdb108sp. Confirmed by @MichaelAGRC.
