### ISSUE TITLE
Removing printproxy from cloud function dns

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#52]
# Summary

This is to inform you that the print proxy has been upgraded to support a more permanent and descriptive DNS: `print.agrc.utah.gov` and the `https://us-central1-utahkoopserver.cloudfunctions.net/printproxy` DNS is being **deprecated** on **September 1**. 

The new DNS is active and ready for production use. 

Please update your AGOL organization default print service (_Settings -> Utility services_) and any other apps that use the print proxy to use this new DNS by Sept 1st. 

Here is an example of what the upgrade would look for account number `7`:

Old (planned shut off date of Sept 1st):

- `https://us-central1-utahkoopserver.cloudfunctions.net/printproxy/7/arcgis/rest/services/GPServer/export`

New: 

- `https://print.agrc.utah.gov/7/arcgis/rest/services/GPServer/export`

# Notification

- [x] Twitter (@steveoh)
  - [x] Intent
  - [x] Completed

**Comment by steveoh** [comment]
/remind me to check the usage logs for the old service on September 8.

**Comment by stdavis** [comment]
Thanks for opening this issue. 🙌

**Comment by stdavis** [comment]
See latest updates in: https://github.com/agrc/serverless-print-proxy/issues/22

**Comment by steveoh** [comment]
wri update was pushed to production. removing the blocked label

**Comment by stdavis** [comment]
This is done. @steveoh Do you want to tweet one more time or are we good to close this issue?
