### ISSUE TITLE
Duplicate Utah County LIR Parcels AGOL Items

### ISSUE THREAD

**Issue by jacobdadams** [agrc/porter#54]
# Summary

1. http://utah.maps.arcgis.com/home/item.html?id=62b0357b8d1646cc919a91423b5fa15d
2. http://utah.maps.arcgis.com/home/item.html?id=69477c1143924bc9990cdb930b033fb5

Item `2` seems to be the one in the metatable (it's being updated by auditor) and is shared via OpenData. It seems to have come into existence back in November when we started the new AGOL/OpenData push. 

Item `1` reports last being updated on July 27, but my auditor logs show that auditor fixed its tags on that date (which it does for any feature service, not just ones in the metatable) but didn't fix anything else (consistent with it not being in the metatable). 

This process is a little non-standard for this template; triagers, as part of your triage please identify which of these layers you are using and if either can be deleted. Once that is determined, go through the normal checks below for the one to be deleted.

# Triage

- [x] Data Team Triage (@rkelson )
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage~

# Remove data from the following areas

- [x] ArcGIS Online (@jacobdadams)
~- [ ] Internal SGID (assigned to)~
~- [ ] SGID10 (assigned to)~
~- [ ] Open SGID (assigned to)~
~- [ ] Google Drive (assigned to)~
~- [ ] Open data (assigned to)~
~- [ ] Mapserv (assigned to)~
~- [ ] Retire application-specific prod and test SQL Databases (assigned to)~

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

~- [ ] gis.utah.gov data pages (assigned to)~
~- [ ] Stewardship doc and sgid-index (assigned to)~
~- [ ] `SGID.META.AGOLItems` (assigned to)~
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
~- [ ] `SGID.META.ChangeDetection` (assigned to)~

# Is there a website?

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
or
~- [ ] Replace app with a static page with information (assigned to)~
or
~- [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

~- [ ] Stop (assigned to)~
~- [ ] Delete (assigned to)~

# Is there a forklift pallet?

~- [ ] Remove repo (assigned to)~
~- [ ] Remove stale data from forklift hashing and receiving (assigned to)~
~- [ ] Remove row from `data/hashed/changedetection.gdb/TableHashes`~

# Are there service dependencies?

~- [ ] Validate that the web api does not query it (assigned to)~
~- [ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

~- [ ] Blog post (assigned to)~
- [x] Twitter (@steveoh)
  - [ ] Intent
  - [x] Completed

**Comment by gregbunce** [comment]
during the data team meeting, we decided to tackle this after we id all the duplicates in agol.

**Comment by rkelson** [comment]
Item 1 (below) should be removed. Unlike Item 2, Item 1 does not reflect 4 years of updates

http://utah.maps.arcgis.com/home/item.html?id=62b0357b8d1646cc919a91423b5fa15d

**Comment by steveoh** [comment]
duplicate has been deleted. We will open a new issue with all the remaining duplicates
