### ISSUE TITLE
Ping team lead if triage is unchecked

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#56]
Pint a team lead if triage checkbox is unchecked and therefore not completed.

Define who the team leads are and define what ping means.

Is this something we want to add to conductor? cc @stdavis @jacobdadams

**Comment by stdavis** [comment]
Proposed team lead triagers:
| Data | @gregbunce |
| Dev | @steveoh |
| Cadastre | @rkelson |

Happy to make whatever changes are needed. We just need to make a decision on this before this feature is implemented. Thoughts?

@steveoh My thought was that you could triage and I could do more/most of the tasks...

**Comment by stdavis** [comment]
Proposed report format:
| check | status |
| - | :-: |
| triage - Data Team | :no_entry: @stdavis has not yet performed triage for this issue |
| triage - Dev Team | :+1: |
| triage - Cadastre Team | :+1: |
