### ISSUE TITLE
Remove Society.Schools from SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#60]
# Summary

~NOTE: WAIT TO REMOVE THIS LAYER until after the [new higher ed layer](https://github.com/agrc/porter/issues/61) has been added to SGID.~

The SGID Society.Schools layer can be deprecated as it has been replaced by Society.Schools_PreKto12 and the soon to be added higher education schools layer.  The data and attributes in this existing school layer are represented in the new data, so this layer can be removed and deleted: it has no added value.

Here's the AGOL Item ID: 9e700ba2de90451d9c16c176d58e0b68
AGOL Name: Utah Schools
http://utah.maps.arcgis.com/home/item.html?id=9e700ba2de90451d9c16c176d58e0b68

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage~

# Remove data from the following areas

- [x] ArcGIS Online (assigned to @gregbunce )
- [x] Internal SGID (assigned @ZachBeck )
- [x] SGID10 (assigned @ZachBeck )
- [ ] Open SGID (assigned to @steveoh )
- [x] Google Drive (assigned to @gregbunce )
- [x] Open data (assigned to @gregbunce )
~- [ ] Mapserv (assigned to)~
~- [ ] Retire application-specific prod and test SQL Databases (assigned to)~
- [x] Backseat Driver (@stdavis)
- [ ] Update Base Map Cache MXDs (@ZachBeck)

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

~- [ ] gis.utah.gov data pages (assigned to)~
- [x] Stewardship doc and sgid-index (@steveoh)
- [x] `SGID.META.AGOLItems` (assigned to @ZachBeck )
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
- [x] `SGID.META.ChangeDetection` (assigned to @ZachBeck or @steveoh )

# Is there a website?

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
or
~- [ ] Replace app with a static page with information (assigned to)~
or
~- [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~
- [x] Update existing map service (@stdavis)

# Is there a forklift pallet?

- [x] Remove repo (@stdavis)
- [x] Remove stale data from forklift hashing and receiving (@stdavis)
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes`~

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh)

# Notification

- ~[ ] Blog post (assigned to)~
- [x] Twitter (@steveoh ) 
  - [x] Intent (though I think we already did this, right?)
  - [x] Completed

**Comment by gregbunce** [comment]
i'm unsure about the map service, forklift pallet, and service dependencies sections.  can someone (@steveoh or @stdavis ) update those sections (assign or cross out)?   thanks!

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/91323559-3f2c8800-e77e-11ea-95c1-d3d3f2dfafcf.png)
If these haven't been done yet, they should not have a checkbox. As far as I understand it, the person assigned checks the box.

**Comment by gregbunce** [comment]
that makes sense

**Comment by gregbunce** [comment]
@ZachBeck now thinking about it, should we add the new higher ed layer before we remove this one?  does the order matter here?

**Comment by steveoh** [comment]
@stdavis would you please inventory forklift pallets for the schools layer and come up with a plan for migrating application use.

@ZachBeck Will you able to inventory the base maps and come up with a plan for migrating their use.

@gregbunce This deprecation may be blocked by the missing higher ed layer to create a replacement for applications that are currently using schools.

**Comment by gregbunce** [comment]
yup, good call.  let's get the new layer in first.  thanks!

**Comment by ZachBeck** [comment]
USHE sent me addresses for technical colleges last night but I haven't had a chance to compare it to what we have. I'm still waiting on addresses for degree granting colleges.

**Comment by gregbunce** [comment]
i'll put in an issue to add the layer, knowing were still working out the details.  

also, i added some text at the top to say wait to remove this layer until the higher ed layer has been added.

**Comment by stdavis** [comment]
@ZachBeck The base map mxd's will have to be updated, correct?

**Comment by stdavis** [comment]
> @stdavis would you please inventory forklift pallets for the schools layer and come up with a plan for migrating application use.

@steveoh The only use of this data in forklift that I could find was in locate. It should be a fairly straightforward switch. [I created an issue](https://github.com/agrc/locate/issues/199).

**Comment by ZachBeck** [comment]
@stdavis, yep the mxd's will need to be updated.

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by stdavis** [comment]
## conductor results for triage

| check | status |
| - | :-: |
| triage - Data Team | :no_entry: No triage task found for team: Data |
| triage - Dev Team | :no_entry: No triage task found for team: Dev |
| triage - Cadastre Team | :no_entry: No triage task found for team: Cadastre |

**Comment by stdavis** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by stdavis** [comment]
I've switched locate to point at the new Schools_HigherEducation layer.

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by steveoh** [comment]
> I've switched locate to point at the new Schools_HigherEducation layer.

Was that the blocker issue?

**Comment by stdavis** [comment]
> Was that the blocker issue?

Yes, I believe it was _a_ blocker issue. Not sure if it's the only one. The only other one that I can think of is base map MXDs, but I don't think that should stop us from removing it from SGID.

**Comment by steveoh** [comment]
Ok I think the main reason was the completion of the higher ed layer. I will remove the blocked label and we can start the removal process.

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table | :no_entry: |
| open sgid | :no_entry: |
| open data | :no_entry: |
| arcgis online | :no_entry: |
| stewardship |  |
| - deprecation issue link | :no_entry: |

**Comment by gregbunce** [comment]
i backed up the agol/opendata layer to agrc google drive
Shared drives\AGRC Projects\SGID\deprecated layers

**Comment by steveoh** [comment]
base map replacement status

- [x] lite base map
- [ ] terrain 
- [ ] overlay

**Comment by steveoh** [comment]
waiting for conductor to verify completion
