### ISSUE TITLE
Add Society.Schools HigherEducation to SGID

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#61]
# Summary
This dataset contains point locations of higher education institutions in Utah: colleges and universities.  It's one of two new layers (the other being Society.Schools_PreKto12)  that will [replace Society.Schools](https://github.com/agrc/porter/issues/60). 

- **Proposed Dataset Name**: Schools_HigherEducation
- **Proposed ArcGIS Online Name**: Utah Schools Higher Education
- **Proposed ISO Category**: Society
- **Data Description**: This layer contains higher education institutions in the state of Utah: colleges and universities.
- **Source Agency/Entity**: AGRC, USHE, and USBE
- **Contact**: AGRC
- **Update Frequency**: Annually

# Triage

- [ ] Data Team Triage (@ZachBeck)
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage ()~

# We are introducing data

The data was or will be added TBD (week of 8/24 or 8/31) to the following areas

- [x] Internal SGID
- [x] SGID10
- [x] ArcGIS Online

# The data is high quality

- [x] Sweeper checks have run and passed (@ZachBeck )
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce )
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@ZachBeck )

# The data should propagate automatically to

- [x] ArcGIS Online
- [x] SGID10
- [x] Open SGID
- [x] Open data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)
- [x] `SGID.META.AGOLItems`

# We have verified the data is live 

- [x] ArcGIS Online (@gregbunce on `9/14/2020`)
- [x] Internal SGID (@ZachBeck on `9/1/2020`)
- [x] SGID10 (@ZachBeck on `9/14/2020`)
- [x] Open SGID (@gregbunce on `9/14/2020`)
- [x] [Open data](https://opendata.gis.utah.gov) (@gregbunce on `9/16/2020`)
- [x] gis.utah.gov data pages (@gregbunce on `9/17/2020`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@ZachBeck on `9/1/2020`)
- [x] `SGID.META.AGOLItems` (@ZachBeck on `9/1/2020`)
- [ ] `SGID.META.ChangeDetection` (@ZachBeck on ``)
- [ ] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on ``)

# Notification

- [ ] Blog post (@assigned)
- [x] Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools_HigherEd

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship | :no_entry: Did not find Society.Schools_HigherEd in the worksheet |

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools_HigherEd

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship | :no_entry: Did not find Society.Schools_HigherEd in the worksheet |

**Comment by stdavis** [comment]
## conductor results for Society.Schools_HigherEd

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| sgid10 | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| stewardship | :no_entry: Did not find Society.Schools_HigherEd in the worksheet |

**Comment by steveoh** [comment]
the dataset name is incorrect in conductor. The next run will have the accurate table name.

**Comment by gregbunce** [comment]
just an fyi: i'm working on the data page now.  hope to do a pr today.

**Comment by gregbunce** [comment]
@ZachBeck I think my piece is done. @jacobdadams we may want to run auditor again (or just wait till the next run, either way) - as i slightly reordered zach's info to match our guidelines.  nothing huge though, just added last update date, summary duplicated in the description, and added one tag.

**Comment by steveoh** [comment]
Yup, let's let auditor run and then conductor on monday and we'll see how things look to close it then. cc @brigsz as an FYI.

**Comment by agrc-conductor** [comment]
## conductor results for Society.Schools_HigherEducation

| check | status |
| - | :-: |
| internal sgid | :+1: |
| sgid10 | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Website URL | :no_entry: |
| - Endpoint | :no_entry: |
| - Description | :+1: |
| - Data Source | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment]
@ZachBeck it looks like there are two more items to add to the stewardship spreadsheet before we can close this.

**Comment by ZachBeck** [comment]
Done.
