### ISSUE TITLE
Add Geochronology layers from UGS to agol

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#64]
# Summary

- **Proposed Dataset Name**: NA
- **Proposed ArcGIS Online Name**: Utah Geochronology Cosmogenic, Utah Geochronology Fission Track, Utah Geochronology Rubidium Strontium, Utah Geochronology Tephrochronology, Utah Geochronology Tritium, Utah Geochronology Uranium Thorium Lead
- **Proposed ISO Category**: Geoscience
- **Data Description**: Geochronology dating methods
- **Source Agency/Entity**: UGS
- **Contact**: Gordon Douglass
- **Update Frequency**: As requested

# Triage

- [x] Data Team Triage ()
- [x] Dev Team Triage Complete (assigned to)
- [x] Cadastre Team Triage ()

# We are introducing data

The data was or will be added on `2020/09/01` to the following areas

~- [ ] Internal SGID~
~- [ ] SGID10~
- [x] ArcGIS Online

# The data is high quality

- [x] Sweeper checks have run and passed
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] ArcGIS Online
- ~[ ] SGID10~
- ~[ ] Open SGID~
- [x] Open data
~- [ ] `SGID.META.ChangeDetection`~

# References to the data need to be manually added to

- [x] gis.utah.gov data pages
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) (@ZachBeck) 
- ~[ ] `SGID.META.AGOLItems`~
- [x] AGOLItems_shelved [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec)

# We have verified the data is live 

- [x] ArcGIS Online (@ZachBeck  on `9/3/2020`)
- ~[ ] Internal SGID (@assigned on ``)~
- ~[ ] SGID10 (@assigned on ``)~
- ~[ ] Open SGID (@assigned on ``)~
- [x] [Open data](https://opendata.gis.utah.gov) (@ZachBeck  on `9/3/2020`)
- [x] gis.utah.gov data pages (@steveoh [open pull request](https://github.com/agrc/gis.utah.gov/pull/1488))
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@ZachBeck on `9/14/2020`)
- ~[ ] `SGID.META.AGOLItems` (@ZachBeck on ``)~
- ~[ ] `SGID.META.ChangeDetection` (@assigned on ``)~
- [x] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on `0/29/2020`)

# Notification

- [ ] Blog post (@assigned)
- [ ] Twitter (@steveoh)

**Comment by steveoh** [comment]
These datasets will need to be in the stewardship doc. Jake mentioned these tables are shelved? Jakes `AGOLItems_shelved` will need to be populated.

**Comment by brigsz** [comment]
Zach, can you add the names of the other UGS layers? As part of my outreach, I think I am going to contact the head of whatever division telling them thanks and giving them a little info about the SGID

**Comment by gregbunce** [comment]
we had some discussion on this during the data team meeting today, and we decided that it's best to use this as an opportunity to better define sgid curation.  as a result, we will be updating the policy page to reflect these criteria.  additionally, we will then set up a call with UGS (next week) and set a path to move forward (for these layers and future layers alike).

**Comment by steveoh** [comment]
@gregbunce have you set up the call with UGS? Now that the policy is published it seems like everything is ready.

**Comment by ZachBeck** [comment]
We're working on it. Gordon will be out of town on the day that works best for us next week, hopefully another day will work.

**Comment by ZachBeck** [comment]
Greg and I will be talking to Gordon on 10/20

**Comment by nathankota** [comment]
@ZachBeck @gregbunce  Is this still blocked?

**Comment by ZachBeck** [comment]
Gordon shared this with Geoscience today:
http://utah.maps.arcgis.com/home/item.html?id=58644df8f99d491d8bbc2f6261da7b4c

It's a group of feature layers, I'm not sure how it will work with opendata.

**Comment by jacobdadams** [comment]
It looks like it comes through as a single page, and then you have to
select the layer you want before you can download or look at the table.
Seems to work ok:
https://opendata.gis.utah.gov/datasets/utahDNR::utah-geochronology/

**Comment by nathankota** [comment]
I bet he'd be willing to adopt our license
![image](https://user-images.githubusercontent.com/15659642/99447108-5c37a980-28dc-11eb-83fc-221cff465e43.png)

**Comment by steveoh** [comment]
> For data to be shared within the SGID, we prefer to share single feature type feature layers. This means, one data type and theme within a feature layer. This allows the greatest flexibility for the end users of the data.

I guess this is a preference and not a policy but if we are coaching DNR on how to do this should we request they split these out? 

Are we setting them up for issues keeping the data updated yada yada? I'm do not fully understand why we have that preference. 

@MichaelAGRC those are your words, do you have any thoughts or clarification?

**Comment by MichaelAGRC** [comment]
I think this comes from more of an old school view of GIS data.  A single data type per layer.  I'm not sure that it's necessary anymore in light of the agencies managing their own data in AGOL that they're sharing with us.  If Jake and Zach have signed off on it, I think we'll be good.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 64

| check | status |
| - | :-: |
| ZachBeck has completed **3** out of **3** tasks | :+1: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by ZachBeck** [comment]
@steveoh what do you think about getting rid of our [geochronology page](https://gis.utah.gov/data/geoscience/geochronology/) and linking directly to open data from the [geoscience overview](https://gis.utah.gov/data/geoscience/)?

**Comment by steveoh** [comment]
Are there open data samples to look at to help make that decision?

**Comment by ZachBeck** [comment]
yep

**Comment by steveoh** [comment]
Yeah lets do that

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 64

| check | status |
| - | :-: |
| @ZachBeck has completed **3** out of **4** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 64

| check | status |
| - | :-: |
| ZachBeck has completed **4** out of **4** tasks | :+1: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by steveoh** [comment]
[Geochronology](https://gis.utah.gov/data/geoscience/) added to the index page with a link to their open data which is shared in geoscience.
