### ISSUE TITLE
Remove "Utah Land Ownership (SITLA)" from AGOL (AGRC org)

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#66]
# Summary

Now that we have added [SITLA's AGOL Item](https://utah.maps.arcgis.com/home/item.html?id=e3ac7d18df544bd9873a22a0020b8e57) to [our Open Data site](https://opendata.gis.utah.gov/datasets/SITLA::ut-sitla-ownership-landownership-wm-1) it's time to deprecate [our item](https://utah.maps.arcgis.com/home/item.html?id=de66bcfeb8ef45ec8d9c72d6916ab61a) which actually just points at SITLA's feature service.

One possible issue: Is it a big deal that when someone searches for "Land Ownership" in just our content, they would get nothing? For example https://utah.maps.arcgis.com/home/search.html?q=land%20ownership

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- [x] ArcGIS Online (assigned to)
~- [ ] Internal SGID (assigned to)~
~- [ ] SGID10 (assigned to)~
~- [ ] Open SGID (assigned to)~
~- [ ] Google Drive (assigned to)~
~- [ ] Open data (assigned to)~
~- [ ] Mapserv (assigned to)~
~- [ ] Retire application-specific prod and test SQL Databases (assigned to)~

# Copy data to the following areas

- [x] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)
- [x] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)

# Update information in the following areas

- [x] gis.utah.gov data pages (assigned to)
- [x] Stewardship doc and sgid-index (assigned to)
- [x] `SGID.META.AGOLItems` (@stdavis)
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)
~- [ ] `SGID.META.ChangeDetection` (assigned to)~
~- [ ] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to)~

# Notification

- [ ] Blog post (assigned to)
- [ ] Twitter (@steveoh)
  - [ ] Intent
  - [ ] Completed

**Comment by steveoh** [comment]
data was not shared publicly website and everything is pointing to correct place.
