### ISSUE TITLE
Remove CADASTRE.LandOwnership_WeeklyUpdate from SGID

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#67]
# Summary

Since we are now [pulling LandOwnership data directly from the SITLA service via forklift](https://github.com/agrc/warehouse/pull/115), we no longer need to have Barry run his script to update SGID. I've let Barry know that he can stop running the script. We just need to clean up `LandOwnership_WeeklyUpdate`.

Note that this dataset is only visible to the Cadastre user so far as I can tell...

# Triage

- [x] Data Team Triage (@gregbunce )
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- ~[ ] ArcGIS Online (assigned to)~ (taken care of in #55)
- [x] Internal SGID (assigned to @ZachBeck '9/17/2020' )
- [x] SGID10 (assigned to @ZachBeck '9/17/2020' )
- ~[ ] Open SGID (assigned to)~
- ~[ ] Google Drive (assigned to)~
- ~[ ] Open data (assigned to)~
- ~[ ] Mapserv (assigned to)~
- ~[ ] Retire application-specific prod and test SQL Databases (assigned to)~

# Copy data to the following areas

- ~[ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
- ~[ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
- ~[ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- ~[ ] gis.utah.gov data pages (assigned to)~
- ~[ ] Stewardship doc and sgid-index (assigned to)~
- ~[ ] `SGID.META.AGOLItems` (assigned to)~
- ~[ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
- ~[ ] `SGID.META.ChangeDetection` (assigned to)~
- ~[ ] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to)~

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
      or
- ~[ ] Replace app with a static page with information (assigned to)~
      or
- ~[ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~

# Is there a forklift pallet?

- ~[ ] Remove repo (assigned to)~
- ~[ ] Remove stale data from forklift hashing and receiving (assigned to)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes`~

# Are there service dependencies?

- ~[ ] Validate that the web api does not query it (assigned to)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

- ~[ ] Blog post (assigned to)~
- ~[ ] Twitter (@steveoh)~
  - ~[ ] Intent~
  - ~[ ] Completed~

**Comment by stdavis** [comment]
I don't know of any dependencies. From my perspective, you are clear to remove it.

**Comment by gregbunce** [comment]
I checked with rick and he gave me the go-ahead to check-off the cadastre team triage box.

**Comment by gregbunce** [comment]
the items have been removed from both databases.  i'm closing it out. sayonara!
