### ISSUE TITLE
Remove UtahEM service and UDES database

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#68]
# Summary

Utah DEM has replaced all links to the [UtahEM map service layers](http://mapserv.utah.gov/arcgis/rest/services/UtahEM/MapServer) in their WebEOC software. The service can be stopped immediately and will remain unavailable during a "brown out" period while DEM tests WebEOC mapping capabilities with the replacement services. A testing schedule will be determined in conjunction with DEM and a reminder will be set within this issue to delete the service, based on the testing schedule. 

Once the service is deleted the UDES SQL database, upon which the UtahEM service relies, can then be removed. 

# Triage

~- [x] Data Team Triage (@gregbunce)~
- [x] Dev Team Triage (@steveoh)
~- [ ] Cadastre Team Triage (@rkelson)~

# Remove data from the following areas

~- [ ] ArcGIS Online (assigned to)~
~- [ ] Internal SGID (assigned to)~
~- [x] SGID10 (assigned to)~
~- [x] Open SGID (assigned to)~
~- [x] Google Drive (assigned to)~
~- [x] Open data (assigned to)~
- [ ] Mapserv (assigned to)
- [x] Retire ~application-specific prod and test~ SQL Database (@MichaelAGRC )

~# Copy data to the following areas~

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

~# Update information in the following areas~

~- [ ] gis.utah.gov data pages (assigned to)~
~- [ ] Stewardship doc and sgid-index (assigned to)~
~- [ ] `SGID.META.AGOLItems` (assigned to)~
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
~- [ ] `SGID.META.ChangeDetection` (assigned to)~
~- [ ] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to)~

~# Is there a website?~

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
     ~or~
~- [ ] Replace app with a static page with information (assigned to)~
      ~or~
~- [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- [x] Stop (assigned to @steveoh)
- [x] Delete (assigned to @steveoh)

# Is there a forklift pallet?

- [x] Remove repo (assigned to @steveoh)
- [x] Remove stale data from forklift hashing and receiving (assigned to @stdavis)
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes` (assigned to @stdavis)

~# Are there service dependencies?~

~- [ ] Validate that the web api does not query it (assigned to)~
~- [ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

~- [ ] Blog post (assigned to)~
~- [ ] Twitter (@steveoh)~
~- [ ] Intent~
~- [ ] Completed~

**Comment by joshgroeneveld** [comment]
This sounds like a good plan to me.  Would it be ok to have a testing period of about a month?  This would allow the service to be removed around 11/5.

**Comment by nathankota** [comment]
/remind to delete the UtahEM service and UDES database on November 5, 2020

**Comment by nathankota** [comment]
/remind us to delete the service and database on November 5, 2020

**Comment by steveoh** [comment]
/remind me to delete the service and database on November 5, 2020

**Comment by steveoh** [comment]
/remind me to delete the service and database on November 5, 2020

**Comment by stdavis** [comment]
I've removed stale data from forklift hashing. There was no data to remove in receiving. We'll need to clean up the data on the production servers after the service is shut down.

**Comment by steveoh** [comment]
/remind me to delete the service and database on November 5, 2020

**Comment by joshgroeneveld** [comment]
We've completed testing links to updated data.  From our end, we're ok to proceed with deprecation.  Thanks for all of your help!

**Comment by nathankota** [comment]
@MichaelAGRC please go ahead and remove the UDES db and check the box 
![image](https://user-images.githubusercontent.com/15659642/98278880-71185280-1f56-11eb-9da2-ada1b849be72.png)

@steveoh please delete the UtahEM service
![image](https://user-images.githubusercontent.com/15659642/98278956-8d1bf400-1f56-11eb-9049-086123386c8c.png)

**Comment by steveoh** [comment]
the service has been deleted. @MichaelAGRC will you comment when the last task is completed and we can close the issue. Thanks!

**Comment by steveoh** [comment]
looks like micahel checked the box. closing!
