### ISSUE TITLE
Remove duplicate state fuel site from arcgis online

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#72]
# Summary

It looks like there are two state fuel site items. Please determine which is the maintained version and deprecate the other.

1. [StateFuelSites](https://utah.maps.arcgis.com/home/item.html?id=bbad0291cb754be48ae91dc7d82f6f5c) (item id: bbad0291cb754be48ae91dc7d82f6f5c)
1. [Utah State Fuel Sites](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5) (item id: 34fbc5c654ee44c4bfb14c8d9fc73fc5)

UPDATE
We have gotten new data from the fleet folks. This will be used to replace the existing layer's per @gregbunce's comment on 15 Dec. 

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- ~[ ] Cadastre Team Triage (@rkelson)~

# Remove [StateFuelSites](https://utah.maps.arcgis.com/home/item.html?id=bbad0291cb754be48ae91dc7d82f6f5c) from the following areas

- [x] ArcGIS Online (@gregbunce )

# Deprecate/brownout [Utah State Fuel Sites](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5) from the following areas:

- [x] Mark ArcGIS Online Item as deprecated (@gregbunce )
- [ ] Brownout ArcGIS Online Item (@gregbunce )
- [ ] Deprecate the ArcGIS Online item (@gregbunce )

# Add new data to the following areas:

- [x] SGID Internal (@jacobdadams )

# Update information to reflect the new data in the following areas

- [x] gis.utah.gov data pages (@gregbunce  )
- [x] Stewardship doc and sgid-index (@jacobdadams )
- [x] `SGID.META.AGOLItems` (@jacobdadams )
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (@jacobdadams )
- [x] `SGID.META.ChangeDetection` (assigned to)

# Verify the new data is live in the following areas:

- [x] AGOL (@gregbunce )
- [x] SGID Internal (@jacobdadams )
- [x] Open Data (@jacobdadams )
- [x] OpenSGID (@steveoh on `2021/01/07`)

# Notification

- [x] Twitter (@steveoh)

**Comment by steveoh** [comment]
It also looks like auditor hasn't updated the thumbnail for either? cc @jacobdadams

**Comment by jacobdadams** [comment]
`Utah State Fuel Sites` is in the AGOLItems_Shelved table, which is why it's showing up in shelved, with an origin of SGID.SOCIETY.StateFuelSites. It doesn't look like `StateFuelSites` is in either metatable, and I'm not sure when/how it was uploaded to AGOL.

As of now, auditor doesn't update thumbnails for shelved items. Items that have been moved to the shelf since we started running auditor regularly may still have their old branded thumbnails.

**Comment by gregbunce** [comment]
@brigsz do you have a good contact for this layer? I think we'll need to reach out to them in order to determine the correct layer. it appears the unofficial layer is getting use, while the authoritative layer is not.

**Comment by jacobdadams** [comment]
It seems like over the last 6 months they're both getting the same amount of use- about 5 requests/day.

**Comment by nathankota** [comment]
> @brigsz do you have a good contact (person/agency) for this layer? maybe fleet operations?
> 
> I think we'll need to reach out to the steward in order to determine the correct layer. it appears the unofficial layer is getting use, while the authoritative layer is not.

I'll start with Fleet Ops

**Comment by nathankota** [comment]
I contacted Fleet Ops to see if they can help determine which layer is most accurate.

**Comment by nathankota** [comment]
**Robert Slade
Assistance Director & State Fuel Network Manager
Division of Fleet Operations**

>Below is the spreadsheet with the lat long of all state fuel sites with card readers. We have a new site in Milford, Utah that is not on the spreadsheet and the lat. long is 38.404014, -113.010081.
This should help to ensure the map is accurate as we discovered many locations were not exact or far off. I had my team pin drop and get lat. long coordinates at each location. 

https://docs.google.com/spreadsheets/d/1er49qTwC5iE8PuA1psa74BcSlejHaWJDxhOr_e3gwtc/edit#gid=916419563

**Comment by gregbunce** [comment]
thanks, nathan.  i created a utm12 feature class from the table and put it [here](https://drive.google.com/drive/u/1/folders/1c7bs5U5KJWZWFCQIqY1A2IIFhkDWwExD).  I'll do some comparison on it between the existing sgid data and see what i find.

**Comment by gregbunce** [comment]
a couple of immediate observations show that the new data they sent is focused on northern utah.  see the map below where the green stars are the new data and the black outlines is the existing agol data.  also, the new data seems to be more precise with location, but the schema is not as robust.  @nathankota is Robert Slade the best contact?  do you want to reach out to him or should I?  essentially, we need to know:
1. is this new data the complete list of sites in Utah (99 records - opposed to the existing 106)?
2. is this new data the official schema for the layer?
3. should we replace the existing data with this new data?

![image](https://user-images.githubusercontent.com/16906316/97230886-4f71db00-17a0-11eb-8695-4de69cc3c39b.png)

**Comment by gregbunce** [comment]
Okay, we can do better than screenshots.  here's a quick agol map with the new layer and the two existing layers.  
http://arcg.is/9TPSK

**Comment by steveoh** [comment]
> here's a quick agol map 

do you want to switch to the imagery base map before sharing that?

**Comment by gregbunce** [comment]
yeah, i could.  i went back and forth.  see what you think... can you see the symbols well enough?  i could also do imagery only (not the hybrid).  
http://arcg.is/9TPSK

**Comment by nathankota** [comment]
Thanks for taking the time to build the map - it will be helpful to show Robert the issue. I just heard from him about 20 minutes ago that "There should be a total of 124 card reader sites and 115 State Park sites that only DNR has access to.", but the list he provided only had 99 records (minus some sites that are being removed). I will get in touch with him tomorrow and try to get closer to the bottom of it.

**Comment by gregbunce** [comment]
i know it's been out there for some time, but should this info be public?  also, is it relevant to anyone outside of state agencies?  we could host it and make it private.

**Comment by nathankota** [comment]
**update:** 

- Still in contact with Fleet Ops about relevance and/or restrictions about it being public, and obtaining the most updated and comprehensive data. 

- Contacted DFCM about them being possible source of existing fuel site data, but they deferred to Fleet.

**Comment by nathankota** [comment]
/remind me to ding Robert on November 3, 2020 (this is a test of the reminder bot too)

**Comment by nathankota** [comment]
/remind me to ding Robert on November 4, 2020 (this is a test of the reminder bot too)

**Comment by nathankota** [comment]
/remind me again on November 9, 2020

Robert supplied a new list, but it has way more than we need. He is willing to pare it down to just the fueling sites.

**Comment by nathankota** [comment]
Still working with Robert at Fleet to obtain updated data and compare to what we have.

**Comment by nathankota** [comment]
/remind me to ding Robert again on November 19, 2020

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 72

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **2** tasks | :no_entry: |
| @rkelson has completed **1** out of **2** tasks | :no_entry: |

**Comment by nathankota** [comment]
/remind me to check in again with Robert on December 7, 2020

This is still blocked - Robert expects to have some time to look at their data after Thanksgiving.

**Comment by nathankota** [comment]
New data set received late last week. About 30 more locations than current data set(s), and looks like some addresses won't geocode. Data triage planning is in the works.

**Comment by gregbunce** [comment]
nathan, jake, and I chatted about next steps:
1. remove the duplicate layer: we feel that "[StateFuelSites](https://utah.maps.arcgis.com/home/item.html?id=bbad0291cb754be48ae91dc7d82f6f5c) (item id: bbad0291cb754be48ae91dc7d82f6f5c)" should be removed now (it's most likely a remnant of data before what jake has coined the 'great agol migration of 2019').  we feel like [Utah State Fuel Sites](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5) (item id: 34fbc5c654ee44c4bfb14c8d9fc73fc5) is the one we need to replace.
2. add the new state fuel sites data - bring into Internal and proceed without the 'shelved' status - b/c it will be looked at annually.
3. notify via blog post and twitter that this exiting shelved agol layer will be replaced.  run both layers concurrently for one month and do brownout.
4. remove the old, agol shelved [existing layer](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5)
5. done

**Comment by steveoh** [comment]
Ok. Go!

**Comment by gregbunce** [comment]
StateFuelSites has been deleted from AGOL and a copy of the data has been backup in the sgid [deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS) in google drive.

**Comment by gregbunce** [comment]
@jacobdadams and/or others - i noticed i was assigned "Deprecate/brownout Utah State Fuel Sites from the following areas".

do i need to do anything other than get a blog post going with the details and then mark the agol items as 'deprecated'?

**Comment by nathankota** [comment]
> also, i'm thinking i should wait to mark it as deprecated until we have the new layer in agol and blog post published. agreed?

agreed

**Comment by jacobdadams** [comment]
I'd say go ahead and mark it as deprecated now—it doesn't change how people
use it beyond (I think) making it rank lower in search results. I'll try
and get the new stuff uploaded soon.

**Comment by gregbunce** [comment]
marked [Utah State Fuel Sites](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5) as deprecated in AGOL.

**Comment by jacobdadams** [comment]
Ok, the new data is in SGID internal as SGID.SOCIETY.StateFuelSites. Meta tables and stewardship doc have been updated.

Question: There is a spurious SGID.TRANSPORTATION.StateFuelSites entry in the stewardship doc. Am I safe to delete this?

**Comment by gregbunce** [comment]
@jacobdadams I'm not familiar with the SGID.TRANSPORTATION.StateFuelSites entry.  From my perspective, it can be deleted.

**Comment by gregbunce** [comment]
I'm working on a blog post now.  @nathankota are we replacing our current-version of this layer b/c it was out of date?  just getting the story in-line for the post.

**Comment by jacobdadams** [comment]
I'll nuke the transportation entry.

FYI, I forgot to set the permissions on the new SGID table. I'll fix that today.

**Comment by nathankota** [comment]
> I'm working on a blog post now. @nathankota are we replacing our current-version of this layer b/c it was out of date? just getting the story in-line for the post.

In short, yes. Once we started digging to try to find out which of the duplicate AGOL items was most correct, it was realized that they were both outdated.

**Comment by gregbunce** [comment]
also, @jacobdadams do you have a rough idea when the new layer will propagate to agol/opendata?

**Comment by stdavis** [comment]
> also, @jacobdadams do you have a rough idea when the new layer will propagate to agol/opendata?

If the permissions get fixed today, then it should be lifted tomorrow morning and pushed to AGOL tomorrow evening.

**Comment by jacobdadams** [comment]
Permissions have been fixed.

**Comment by gregbunce** [comment]
_I’ve not convinced this layer warrants a blog post.  To me, based on its usage, it's more of a tweet or newsletter mention. but if we want to do it I would say it goes something like this..._

```
There's a new [State Fuel Sites](waiting for link) layer in the SGID. This dataset will replace the existing ArcGIS Online [hosted feature service](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5). AGRC worked with the Utah [Division of Fleet Operations](https://fleet.utah.gov/) to update and improve this data.

A few things to note

- There has been a change to the schema
- The new dataset will receive periodic updates
- The old layer has been marked as deprecated but, as a courtesy, will remain available until 00/00/2021
- Additionally, we will conduct a brownout on the deprecated layer on 00/00/2121

We suggest migrating your maps and apps to the new layer as soon as possible.

```

Thoughts on if we need one?  If so, I can get that draft cleaned up.

**Comment by jacobdadams** [comment]
I just want to know who'll be around in 2121 to finally nuke it 😆

**Comment by gregbunce** [comment]
I'll keep an eye for the new layer in AGOL/Open Data today (it's not showing yet), and then I'll update the data page with the new info - Rick you're off the hook.  

Let's bail on the blog post.  I think it might make us look silly.  We can roll with a tweet based on the info above, but let's wait till the data is live in AGOL/Open Data.

I'll keep an eye on it.

**Comment by jacobdadams** [comment]
The AGOL item is live and I've run auditor against it, so it is also live in Open Data with the appropriate info. 

However, the metadata didn't seem to come across. I'll troubleshoot that bit.

**Comment by gregbunce** [comment]
@steveoh what do you think about tweeting some variation of this info out?  the data is now live.

There's a new [State Fuel Sites](https://opendata.gis.utah.gov/datasets/utah-state-fuel-sites) layer in the SGID. This dataset will replace the existing ArcGIS Online [hosted feature service](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5). AGRC worked with the Utah [Division of Fleet Operations](https://fleet.utah.gov/) to update and improve this data.

A few things to note

- There has been a change to the schema (we went from 17 to now 5 fields)
- The new dataset will receive periodic updates
- The old layer has been marked as deprecated but, as a courtesy, will remain available until 00/00/2021
- Additionally, we will conduct a brownout on the deprecated layer on 00/00/2121

We suggest migrating your maps and apps to the new layer as soon as possible.

**Comment by steveoh** [comment]
I am happy to tweet but it is much too long. Do you want try to trim it down and then I can hack it to fit in a tweet?

**Comment by gregbunce** [comment]
maybe something like this...
There's a new [State Fuel Sites](https://opendata.gis.utah.gov/datasets/utah-state-fuel-sites) layer in the SGID. This layer has replaced the existing ArcGIS Online [hosted feature service](https://utah.maps.arcgis.com/home/item.html?id=34fbc5c654ee44c4bfb14c8d9fc73fc5), which will be officially deprecated on 01/23/2021. Please migrate your maps and apps to the new layer.

**Comment by gregbunce** [comment]
also, how can set a reminder here?

I need to set two reminders for this issue and also mark it as 'waiting'

- brownout on Jan 20th 
- official deprecation on Jan 22nd.

**Comment by gregbunce** [comment]
i see how to add the label.  is everyone okay if I mark it 'waiting'?  I'll do that right after i update the data page.

**Comment by steveoh** [comment]
i just sent 3 tweets.

```
Use the /remind slash command to set a reminder on any comment box on GitHub and you'll get a ping about it again when the reminder is due.

Use any form of /remind me [what] [when], such as:

/remind me to deploy on Oct 10
/remind me next Monday to review the requirements
/remind me that the specs on the rotary girder need checked in 6 months
```

**Comment by steveoh** [comment]
this hasn't made it to the open sgid yet from my last check

**Comment by gregbunce** [comment]
/remind me to brownout deprecated layer on Jan 20

**Comment by gregbunce** [comment]
/remind me to officially deprecate/delete the older algo layer on Jan 22

**Comment by gregbunce** [comment]
@jacobdadams are you able to conduct the brownout on Jan 20th?  If not, just let me know your process and I'll take care of it.

**Comment by gregbunce** [comment]
after reading the github label descriptions it seems like 'blocked' describes the current status of this issue.  we're waiting till Jan 22nd to move forward and close this out.

**Comment by steveoh** [comment]
> just let me know your process and I'll take care of it.

i think you update sharing for the item and call it good.

**Comment by gregbunce** [comment]
> i think you update sharing for the item and call it good.

that makes sense.  thx.  I can handle that.

**Comment by steveoh** [comment]
meeting update

brownout on 20th
delete on the 22nd

fix cloudb to import new table correctly

**Comment by nathankota** [comment]
- Downloaded and backed-up in [AGRC Projects > SGID > deprecated layers](https://drive.google.com/drive/u/1/folders/1JT4XzZz3wX95nJc95iOcQ2T3Zd_4GtAS)
- Deleted February 4, 2021
