### ISSUE TITLE
Remove "removed" sgid10 layers from website/sgid index for water category

### ISSUE THREAD

**Issue by steveoh** [agrc/porter#73]
# Summary

Remove the following from the SGID index and all data pages

- [x] SGID10.WATER.DamsGNIS
- [x] SGID10.WATER.HydrologicFeaturesGNIS
- [x] SGID10.WATER.WaterRightsRegions

# Update information in the following areas

- [x] gis.utah.gov data pages (@steveoh)
- [x] Stewardship doc and sgid-index (@rkelson )

# Notification

- [x] Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 73

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 73

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |
