### ISSUE TITLE
Add Utah Quaternary Faults from UGS replacing existing faults in AGOL

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#75]
# Summary
[UGS Utah Quaternary Faults](https://utah.maps.arcgis.com/home/item.html?id=9c85978d0fb54570bc60bec467e2fa7f) are to be shared with the AGOL Geoscience group. This shared feature layer will replace the exiting AGRC version of Quaternary Faults in AGOL and will need to be pulled into SDE as well

- **Proposed Dataset Name**: Quaternary Faults
- **Proposed ArcGIS Online Name**: Utah Quaternary Faults
- **Proposed ISO Category**: Geoscience
- **Data Description**: Quaternary faults in Utah
- **Source Agency/Entity**: UGS
- **Contact**: Gordon Douglass
- **Update Frequency**: As needed

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# We are introducing data

The data was or will be added on `2020/11/09` to the following areas

- [x] Internal SGID
- ~[ ] SGID10~
- [x] ArcGIS Online

# The data is high quality

- [x] Sweeper checks have run and passed (on their service, prior to coming into internal) (@gregbunce) 
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/)

# The data should propagate automatically to

- [x] Internal via Forklift (@stdavis) 
- ~[ ] ArcGIS Online~
- ~[ ] SGID10~
- [x] Open SGID
- [x] Open data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages (@ZachBeck) 
- [x] [Stewardship doc](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)(@ZachBeck )
- [x] `SGID.META.AGOLItems` (@stdavis) 
- ~[ ] `AGOLItems_shelved` [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) (AGOL version of the metatable for any `static` or `shelved` items)~

# We have verified the data is live

- [x] ArcGIS Online (@ZachBeck  on `11/17/2020`)
- [x] Internal SGID (@ZachBeck  on `1/11/2021`)
- [x] Open SGID (@steveoh  on `2021/01/11`)
- [x] [Open data](https://opendata.gis.utah.gov) (@ZachBeck on `11/17/2020`)
- [x] gis.utah.gov data pages (@ZachBeck  on `12/1/2020`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@ZachBeck on `11/17/2020`)
- [x] `SGID.META.AGOLItems` (@ZachBeck on `11/17/2020`)
- [x] `SGID.META.ChangeDetection` (@stdavis on ``)
- ~[ ] [agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on ``)~

# Notification

- [ ] Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| @ZachBeck has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| @ZachBeck has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **1** out of **4** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @ZachBeck has completed **2** out of **5** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
@gregbunce Have sweeper checks been run on this service? Am I good to wire it up forklift to start pulling data into SGID?

**Comment by stdavis** [comment]
@ZachBeck Just want to confirm: I'm wiring forklift to pull data from the UGS AGOL item to `SGID.GEOSCIENCE.QuaternaryFaults`, correct?

**Comment by ZachBeck** [comment]
yep

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @ZachBeck has completed **5** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
blocked by sweeper checks

**Comment by gregbunce** [comment]
sweeper checks:
no empties were found, but [67 duplicates were found](https://docs.google.com/spreadsheets/d/1ZmQipPb8196qvz8arLMeQwSLBTDN9zGe7ZWyFZviwuw/edit?usp=sharing).  I'll contact Gordon and let him know.

**Comment by gregbunce** [comment]
Gordon is looking into the duplicates now and will republish the layer.

**Comment by gregbunce** [comment]
update: the new feature layers has the same duplicates.  They are looking into it.  

Also, the URL changed ([new URL](https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Utah_Quaternary_Faults_20201207/FeatureServer)), which will be an issue for everything we've wired up already, right?

**Comment by steveoh** [comment]
Yeah probably. Do you want to teach them how to overwrite a dataset so this isn't an issue in the future?

**Comment by gregbunce** [comment]
I'm still working with Gordon to get this resolved.  He sent me the source data (via fgdb) to check and sweeper found the same issues.  I reported that back to them.  I also the ESRI FindIdentical tool, which also found the duplicates.  For some reason, they are not able to find them on this end.  I supplied them with the [list of OIDs](https://docs.google.com/spreadsheets/d/1ZmQipPb8196qvz8arLMeQwSLBTDN9zGe7ZWyFZviwuw/edit#gid=18852944) from both the AGOL feature service and the fgdb.  

I asked how we can assist.  We will wait to hear back.

I also asked if we could get the original URL back - as we've wired up some stuff on our side based on that itemid.

**Comment by gregbunce** [comment]
just heard back from Gordon: they are removing the duplicates and will republish, however, it sounds like the original URL (agol itemid) is gone.  I mentioned they'll need to persist the feature service (itemid) in the future. 

@ZachBeck @stdavis sounds like we'll have to rewire up the ItemID stuff based on the new ID.  But, let's wait until I confirm with them that it's the final ID.

**Comment by gregbunce** [comment]
this layer has not passed our sweeper checks - "No issues found!"

However, it's a new layer.  the new item ID is "9c85978d0fb54570bc60bec467e2fa7f"
https://utahdnr.maps.arcgis.com/home/item.html?id=9c85978d0fb54570bc60bec467e2fa7f
https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Utah_Quaternary_Faults_20201207/FeatureServer

@ZachBeck @stdavis - sorry to do this to you, but it will need to be rewired based on the new ItemID.

Gordon said he will overwrite the data next time that way we can preserve the ItemID.

**Comment by steveoh** [comment]
When that is done we can close this?

**Comment by gregbunce** [comment]
I believe so.

**Comment by stdavis** [comment]
With the merging of [this PR](https://github.com/agrc/warehouse/pull/120), forklift has been wired up for this isue.

**Comment by steveoh** [comment]
This is ready for closing?

**Comment by ZachBeck** [comment]
No. It looks like the faults in AGOL/Open Data aren't making their way to internal sgid and open sgid

**Comment by steveoh** [comment]
> No. It looks like the faults in AGOL/Open Data aren't making their way to internal sgid and open sgid

How are you verifying that?

ping @stdavis

**Comment by ZachBeck** [comment]
by the number of records in agol vs internal sgid and open sgid.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @ZachBeck has completed **6** out of **7** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
The data wasn't being updated for this dataset because of [this](https://github.com/agrc/warehouse/pull/124). I'll check again in a few days.

/remind me to check the data in sgid in two days.

**Comment by jacobdadams** [comment]
I need to check the Meta table entry for this to make sure auditor is checking it properly.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @ZachBeck has completed **6** out of **7** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
> The data wasn't being updated for this dataset because of [this](https://github.com/agrc/warehouse/pull/124). I'll check again in a few days.

The counts are now matching. 👍

**Comment by steveoh** [comment]
> The counts are now matching. 👍

what is the correct count for the rest of us?

**Comment by stdavis** [comment]
> what is the correct count for the rest of us?

6515

**Comment by steveoh** [comment]
great. open sgid updated ✅

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 75

| check | status |
| - | :-: |
| gregbunce has completed **2** out of **2** tasks | :+1: |
| @steveoh has completed **2** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| ZachBeck has completed **7** out of **7** tasks | :+1: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
@jacobdadams the last box is yours!

**Comment by jacobdadams** [comment]
Since we are not hosting the AGOL item, Auditor doesn't need to do anything here. I'm going to close the issue 🎉
