### ISSUE TITLE
Remove AGRC version of Utah Quaternary Faults from AGOL

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#76]
# Summary

Current AGRC version of Utah Quaternary Faults need to be removed from AGOL, they are being replaced by a version from UGS that is shared to the Geoscience group.

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- [x] ArcGIS Online (@ZachBeck )
- ~[ ] Internal SGID (assigned to)~
- ~[ ] SGID10 (assigned to)~
- ~[ ] Open SGID (assigned to)~
- [x] Google Drive (@ZachBeck)
- ~[ ] Open data (assigned to)~
- ~[ ] Mapserv (assigned to)~
- ~[ ] Retire application-specific prod and test SQL Databases (assigned to)~

# Copy data to the following areas

- [x] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (@ZachBeck) OR
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (@ZachBeck ) OR
- ~[ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets)~

# Update information in the following areas

- [x] gis.utah.gov data pages (@ZachBeck)
- ~[ ] Stewardship doc and sgid-index (assigned to)~
- [x] `SGID.META.AGOLItems` (@ZachBeck)
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (@ZachBeck)
- ~[ ] `SGID.META.ChangeDetection` (assigned to)~
- ~[ ] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to)~

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
      or
- ~[ ] Replace app with a static page with information (assigned to)~
      or
- ~[ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~

# Is there a forklift pallet?

- ~[ ] Remove repo (assigned to)~
- ~[ ] Remove stale data from forklift hashing and receiving (assigned to)~
- ~[ ] Remove row from `data/hashed/changedetection.gdb/TableHashes`~

# Are there service dependencies?

- ~[ ] Validate that the web api does not query it (assigned to)~
- ~[ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

- [ ] Blog post (assigned to)
- [x] Twitter (@steveoh)
  - [x] Intent
  - [ ] Completed

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 76

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 76

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **2** out of **2** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **6** out of **6** tasks | :+1: |
