### ISSUE TITLE
Remove "removed" sgid10 layers from website/sgid index for Health category

### ISSUE THREAD

**Issue by rkelson** [agrc/porter#77]
# Summary

Remove the following from the SGID index and all data pages

- [x] SGID10.HEALTH.EmergencyRegions

# Update information in the following areas

- [x] gis.utah.gov data pages (@steveoh)
- [x] gis.utah.gov index page links (@rkelson )
- [x] Stewardship doc and sgid-index (@rkelson )

# Notification

- [x] Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 77

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 77

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **1** tasks | :no_entry: |
