### ISSUE TITLE
Remove Vista Ballot Areas Proposed from AGOL

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#79]
# Summary

`SGID.political.VistaBallotAreas_Proposed` is a test version of `SGID.political.VistaBallotAreas`. From @mheagin:
> The only ones who use VistaBallotAreas_Proposed are the guys upstairs to do some testing occasionally when a county requests it. They do that before we move it into the main VistaBallotAreas. Nobody else is using it but them and possibly someone from the county.  So it's in SGID so I can do updates to it and they can still access it when they need it.

This data should be removed from AGOL, and OpenData, since it is not intended for public consumption and can (already has?), led to confusion. It needs to stay in Open SGID for now because Vista could still possibly use it via their python script for updating precincts.

# Triage

- [ ] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- [x] ArcGIS Online (@stdavis)
~- [ ] Internal SGID (assigned to)~
~- [ ] SGID10 (assigned to)~ (just leave it until SGID10 is retired at the end of the year)
~- [x] Open SGID (@steveoh)~ (this probably just needs to stay for now)
~- [ ] Google Drive (@gregbunce)~
- [x] Open data (@stdavis)
~- [ ] Mapserv (assigned to @stdavis )~ We need the mapserv service to continue since it is used by the vista folks.
~- [ ] Retire application-specific prod and test SQL Databases (assigned to)~

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
~- [ ] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

~- [ ] gis.utah.gov data pages (assigned to)~
- [x] Stewardship doc and sgid-index (assigned to @steveoh )
- [x] `SGID.META.AGOLItems` (@stdavis)
	- update value in `AGOL_ITEM_ID` to be something like "excluded"
~- [ ] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
~- [ ] `SGID.META.ChangeDetection` (assigned to)~
- [x] [Backseat Driver](https://github.com/agrc/backseat-driver) (@stdavis)

# Is there a website?

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
      or
~- [ ] Replace app with a static page with information (assigned to)~
      or
~- [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

~- [ ] Stop (assigned to)~
~- [ ] Delete (assigned to)~

# Is there a forklift pallet?

~- [ ] Remove repo (assigned to)~
~- [ ] Remove stale data from forklift hashing and receiving ()~
~- [ ] Remove row from `data/hashed/changedetection.gdb/TableHashes`~

# Are there service dependencies?

- [x] Validate that the web api does not query it (assigned to)
- [x] Validate that AGRC or applications widgets do not reference it (assigned to)

# Notification

- [x] Twitter (@steveoh)

**Comment by steveoh** [comment]
my triage is complete

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 79

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **1** out of **2** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |

**Comment by rkelson** [comment]
no triage needed from me

**Comment by stdavis** [comment]
Unfortunately, there has been some usage of the AGOL Item:
![image](https://user-images.githubusercontent.com/1326248/99466531-cd398a00-28f9-11eb-97c7-5a851440ad62.png)

I've marked it as deprecated and will delete it in two weeks.

/remind me to delete the AGOL item in two weeks

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 79

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **1** out of **3** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **2** out of **4** tasks | :no_entry: |

**Comment by stdavis** [comment]
I've deleted this item from AGOL/OpenData and verified that it's marked as `exclude` in the AGOLItems table.

**Comment by stdavis** [comment]
I just realized that the Vista folks _might_ need this in OpenSGID so it should stay there for now.

**Comment by steveoh** [comment]
meeting update

once opensgid contains table can close

**Comment by steveoh** [comment]
data is back on open sgid.
