### ISSUE TITLE
Remove AGRC version of Utah Oil Gas Fields from AGOL+Open SGID

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#84]
# Summary

The [AGRC version](https://opendata.gis.utah.gov/datasets/utah-oil-gas-fields?geometry=-119.033%2C36.449%2C-103.279%2C42.384) of Utah Oil Gas Fields need to be removed from AGOL and Open SGID. An [updated layer](https://opendata.gis.utah.gov/datasets/utahDNR::utah-oil-and-gas-fields) has been shared by OGM to the Energy group. 

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- [x] ArcGIS Online (assigned to @jacobdadams )
- [x] Internal SGID (assigned to @ZachBeck )
- [x] SGID10 (assigned to @ZachBeck )
- [x] Open SGID
- [x] Google Drive (assigned to @gregbunce )
- [x] Open data (assigned to @jacobdadams )
- [ ] ~Mapserv (assigned to)~
- [ ] ~Retire application-specific prod and test SQL Databases (assigned to)~
- [x] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (assigned @stdavis )

# Copy data to the following areas

- [ ] ~Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to)~
- [ ] ~Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to)~
- [ ] ~Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- [x] gis.utah.gov data pages (assigned to @steveoh)
- [x] Stewardship doc and sgid-index (assigned to @steveoh)
- [x] `SGID.META.AGOLItems` (assigned to @stdavis )
- [ ] ~`AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to)~
- ~[ ] `SGID.META.ChangeDetection` (assigned to @stdavis )~
- [x] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to @stdavis )

# Is there a forklift pallet?

- [x] Update forklift pallet to pull into internal (assigned to @stdavis)

# Notification

- [x] Twitter Intent (@steveoh)
- [x] Twitter Completed

**Comment by steveoh** [comment]
Will the schemas match here?

**Comment by nathankota** [comment]
Yes, the schemas now match.

**Comment by steveoh** [comment]
My triage is complete ✅

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 84

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| steveoh has completed **1** out of **1** tasks | :+1: |

**Comment by stdavis** [comment]
I marked the [AGRC AGOL Item](https://utah.maps.arcgis.com/home/item.html?id=7788ca033769450185e426686fcc0e09) associated with this issue as deprecated today.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 84

| check | status |
| - | :-: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| steveoh has completed **2** out of **2** tasks | :+1: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by nathankota** [comment]
Changed AGOL share setting to Organization only. Will set reminder to delete from AGOL in two weeks.

**Comment by nathankota** [comment]
/remind to delete AGOL item on December 21, 2020 

https://utah.maps.arcgis.com/home/item.html?id=7788ca033769450185e426686fcc0e09#overview

**Comment by nathankota** [comment]
Fgdb saved to AGRC Projects > SGID > deprecated layers. 
Layer deleted from AGRC AGOL org.
Tweet requested in #social-media Slack channel.
@steveoh please check the `Twitter Completed` box and close this issue when you have a chance.
