### ISSUE TITLE
Add Utah Oil and Gas Fields from OGM replacing existing data in AGOL and Open SGID

### ISSUE THREAD

**Issue by nathankota** [agrc/porter#85]
# Summary

[OGM Utah Oil and Gas Fields](https://opendata.gis.utah.gov/datasets/utahDNR::utah-oil-and-gas-fields)
are an updated version and are being shared to the AGOL Energy group. This shared feature layer will replace the exiting [AGRC version](https://opendata.gis.utah.gov/datasets/utah-oil-gas-fields?geometry=-119.033%2C36.449%2C-103.279%2C42.384) of Oil and Gas Fields in AGOL and will also need to be pulled into the internal SDE for distribution to Open Data.

- **Proposed Dataset Name**: Oil and Gas Fields
- **Proposed ArcGIS Online Name**: Utah Oil and Gas Fields
- **Proposed ISO Category**: Energy
- **Data Description**: Oil and Gas Fields in Utah (there is also a short description provided by OGM in the Open Data overview) 
- **Source Agency/Entity**: OGM
- **Contact**: Michael Van Hatten
- **Update Frequency**: Rarely

# Triage

- [x] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# We are introducing data

The data was or will be added on `2020/00/00` to the following areas

- [x] Internal SGID
- [x] SGID10
- [ ] ~ArcGIS Online~

# The data is high quality

- [x] Sweeper checks have run and passed (@gregbunce)
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce)

# The data should propagate automatically to

- [ ] ~ArcGIS Online~
- [x] SGID10
- [x] Open SGID
- [x] Open data
- [x] `SGID.META.ChangeDetection`

# References to the data need to be manually added to

- [x] gis.utah.gov data pages (@steveoh)
- [x] [Stewardship doc] (@steveoh)(https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)
- [x] `SGID.META.AGOLItems` (@stdavis)
- [ ] ~`AGOLItems_shelved` [metatable](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) (AGOL version of the metatable for any `static` or `shelved` items~

# We have verified the data is live

- [x] ArcGIS Online (@steveoh on `11/19/20`)
- [x] Internal SGID (@ZachBeck  on `12/7/2020`)
- ~[ ] SGID10 (@ZachBeck  on ``)~
- [x] Open SGID (@steveoh on `12/7/20`)
- [x] [Open data](https://opendata.gis.utah.gov) (@steveoh on `11/19/20`)
- [x] gis.utah.gov data pages (@steveoh on `11/19/20`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `11/19/20`)
- [x] `SGID.META.AGOLItems` (@stdavis on ``)
- [x] `SGID.META.ChangeDetection` (@stdavis on ``)
- [ ] ~[agol-validator](https://github.com/agrc/agol-validator) items (@jacobdadams on ``)~

# Notification

- [ ] ~Blog post (@assigned)~
- [x] Intent Twitter (@steveoh)
- [x] Compete Twitter (@assigned)

**Comment by steveoh** [comment]
Will this use the same schema as our current data

**Comment by nathankota** [comment]
Yes, the schemas are the same between our layer and OGM's layer.

**Comment by steveoh** [comment]
My triage is done. 

All references to 
https://opendata.gis.utah.gov/datasets/utah-oil-gas-fields
7788ca033769450185e426686fcc0e09

will be replaced by

https://opendata.gis.utah.gov/datasets/utahDNR::utah-oil-and-gas-fields
5bb6d8d0ea7440568764dc5a28418be8

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 85

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **7** out of **8** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |
| steveoh)(https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1 has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **0** out of **3** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **2** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment]
✔️ Updated AGOLItems table to show `hosted by DOGM` for this dataset.

**Comment by gregbunce** [comment]
@eneemann (or whomever else has the magic) can you assist me with getting the correct syntax for running sweeper on an agol and/or open data layer?  I tried a few different configurations but I can't seem to get the right syntax.   thanks!

**Comment by eneemann** [comment]
After initially thinking a bit, I wasn't sure if Sweeper would work based on our workspace/table name construct.  However, if you don't attempt to save a report and provide a blank workspace, it appears to work okay.

'''py python -m sweeper sweep duplicates --workspace= --table-name=https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Oil_and_Gas_Fields/FeatureServer/0

python -m sweeper sweep empties --workspace= --table-name=https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Oil_and_Gas_Fields/FeatureServer/0'''

**Comment by eneemann** [comment]
I got the service URL by plugging in the AGOL ID that Steve listed above and visiting the item's AGOL page: [](http://utah.maps.arcgis.com/home/item.html?id=5bb6d8d0ea7440568764dc5a28418be8)

**Comment by gregbunce** [comment]
@eneemann nice work.  Yeah, I guess my issues were supplying a workspace and trying to save a report.  the workspace makes sense, but i wonder why we can't output a report.  thanks!

**Comment by eneemann** [comment]
@gregbunce I think it's because the table name is built into the filename of the report, which causes problems when the table name is a URL:

```OSError: [Errno 22] Invalid argument: 'c:\\\\Temp\\sweeper_run_20201130_0842\\https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Oil_and_Gas_Fields/FeatureServer/0_DuplicateTest_0.txt'```

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 85

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **4** tasks | :no_entry: |
| @steveoh has completed **7** out of **8** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| steveoh)(https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1 has completed **1** out of **1** tasks | :+1: |
| @stdavis has completed **2** out of **3** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by gregbunce** [comment]
@nathankota how well do you know Michael Van Hatten?  is it best to email or set up a chat?  I wanted to chat with him about some metadata ideas.

**Comment by nathankota** [comment]
@gregbunce I'll ping you about this

**Comment by gregbunce** [comment]
status update on domains and metadata: i sent Michael an email with a few suggestions for additional metadata/domain content.  also, mentioned we would carry that over to the sgid data page for that layer.

**Comment by gregbunce** [comment]
@ZachBeck i think this can be brought into Internal and the meta table now.  the data passed the sweeper checks.  

I'll work with Michael Van Hatten to expand the metadata a bit.  but, that shouldn't affect Internal, right @stdavis -- when we ingest data into Internal from another agency's hosted feature layer, we don't import the metadata, right?

**Comment by ZachBeck** [comment]
I guess I don't understand how it will get into Internal, someone set the AGOL_ITEM_ID to `hosted by DOGM`

**Comment by steveoh** [comment]
> @ZachBeck i think this can be brought into Internal and the meta table now. 
>
> I guess I don't understand how it will get into Internal, someone set the AGOL_ITEM_ID to `hosted by DOGM` in the meta table

I think this will be a forklift responsibility.

The `AGOL_ITEM_ID` is set that way so we do not upload our own version to arcgis online.

**Comment by gregbunce** [comment]
@stdavis this can be brought into Internal now (see the last three comments) - the data passed our sweeper checks.

**Comment by gregbunce** [comment]
status update on domains and metadata: 
Michael Van Hatten replied saying he will work on getting the metadata/domain suggestions we made into their hosted feature service.

**Comment by stdavis** [comment]
Forklift was [already wired up to pull this data into internal](https://github.com/agrc/warehouse/commit/4d14118283fb6ca6f20ffc7cd9d04f8eb252e28a). ✔️

**Comment by steveoh** [comment]
What is the best way to verify that this data is live in open data and internal?

**Comment by stdavis** [comment]
Maybe compare record counts between the OGM AGOL item and open data/internal?

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 85

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **4** tasks | :no_entry: |
| @steveoh has completed **7** out of **8** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| steveoh)(https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1 has completed **1** out of **1** tasks | :+1: |
| stdavis has completed **3** out of **3** tasks | :+1: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
I've verified this is in open sgid.

**Comment by ZachBeck** [comment]
looks like it hasn't made it's way to Internal

**Comment by steveoh** [comment]
> looks like it hasn't made it's way to Internal

How did you verify that?

**Comment by ZachBeck** [comment]
SGID.ENERGY.DNROilGasFields has the same number of records and what appears to be the same geometry as the AGOL version, it also has an empty Shape__Area field and Shape__Length field as well.

**Comment by gregbunce** [comment]
I reached out to Michael Van Hatten today and he's working on the metadata now.  I think we're close on this one.

**Comment by nathankota** [comment]
Auditor validation crossed-out. Since this is an externally-hosted layer, Auditor will not touch it. Metadata requirements and domain rules compliance are the final pieces.

**Comment by gregbunce** [comment]
... still waiting.  Michael mentioned he is understaffed.  I asked how we can assist.  I'll follow up again with him this afternoon.

**Comment by gregbunce** [comment]
Micheal got me the items i requested for our sgid data page.  I'll get that page updated and we can move forward.  He is happy with the metadata as-is on their agol page.  I asked him to put a link on their agol page to our sgid data page if folks want more info.

**Comment by gregbunce** [comment]
from my perspective, after [this pr](https://github.com/agrc/gis.utah.gov/pull/1591) is merged, this issue can be closed.
