### ISSUE TITLE
Remove BOUNDARIES.USFSWilderness from SGID

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#99]
# Summary

BOUNDARIES.USFSWilderness needs to be deprecated and removed from databases and AGOL and replaced with an updated USFS/BLM combined wilderness data set.

# Triage

- [ ] Data Team Triage (@gregbunce)
- [x] Dev Team Triage (@steveoh)
- [x] Cadastre Team Triage (@rkelson)

# Remove data from the following areas

- [x] ArcGIS Online (assigned to @ZachBeck)
- [x] Internal SGID (assigned to @ZachBeck)
- [x] Open SGID (assigned to @steveoh)
- [x] Google Drive (assigned to @ZachBeck)
- [x] Open data (assigned to @jacobdadams)
-~ [ ] Mapserv (assigned to)~
-~[ ] Retire application-specific prod and test SQL Databases (assigned to)~
-~[ ] AGRC Projects team drive [folder](https://drive.google.com/drive/folders/0AIVByxAYHd4oUk9PVA) (assigned to)~

# Shelve/Static

- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (assigned to @ZachBeck)
      or
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (assigned to @ZachBeck)
      or
- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)

# Update information in the following areas

- [x] gis.utah.gov data pages (assigned to @ZachBeck)
- [x] Stewardship doc and sgid-index (assigned to @ZachBeck)
- [x] `SGID.META.AGOLItems` (assigned to @ZachBeck)
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (assigned to @ZachBeck)
- [x] `SGID.META.ChangeDetection` (assigned to @steveoh)
-~[ ] [Backseat Driver](https://github.com/agrc/backseat-driver) (assigned to)~

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
      or
-~ [ ] Replace app with a static page with information (assigned to)~
      or
-~ [ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
-~ [ ] Delete (assigned to)~

# Is there a forklift pallet?

- ~[ ] Remove repo (assigned to)~
- ~[ ] Remove stale data from forklift hashing and receiving (assigned to)~
- [x] Remove row from `data/hashed/changedetection.gdb/TableHashes`

# Are there service dependencies?

- [x] Validate that the web api does not query it (assigned to @steveoh)
- ~[ ] Validate that AGRC or applications widgets do not reference it (assigned to)~

# Notification

- [x] Intent Twitter (@steveoh)

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 99

| check | status |
| - | :-: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **4** out of **5** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |
| ZachBeck has completed **9** out of **9** tasks | :+1: |
| jacobdadams has completed **1** out of **1** tasks | :+1: |

**Comment by agrc-conductor** [comment]
## conductor results for BOUNDARIES.USFSWilderness

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table | :+1: |
| stewardship | :no_entry: Did not find BOUNDARIES.USFSWilderness in the worksheet |
